### ISSUE TITLE
z-index issue when including links in blog description

### ISSUE THREAD

**Issue by hannawallach** [TryGhost/Casper#134]
Hi, 

The current recommended way to include links in the blog description is to replace {{@blog.description}} with {{{@blog.description}}} in index.hbs (see <a href="https://github.com/TryGhost/Ghost/issues/1517">here</a> for more discussion). However, when I do this with the default Casper theme, I run into (what I think are) z-index issues. Specifically, the resultant links work fine on my computers (Linux w/ Firefox, Windows w/ IE) but they do not work at all on my cell phone (Android w/ Chrome). Since adding in any link (via an `<a>` tag) immediately below the HTML that includes the blog description results in the same problem, I think that this is probably a z-index issue, maybe involving the "Subscribe" link, which works just fine. (Possibly related: the bouncing arrow icon does not appear either, but maybe this is intentional for mobile display.)

I'm not a CSS expert, so I'd love some input on how best to fix this issue. More generally, this issue should probably be fixed in future versions of Casper, if replacing {{@blog.description}} with {{{@blog.description}}} in index.hbs continues to be the recommended way to include links in the blog description.

Thanks!
Hanna

**Comment by novaugust** [comment]
The new ghost navigation settings is now the best way to put links on your blog; I'm going to close this with that in mind :)
