### ISSUE TITLE
Line number of embedded gists

### ISSUE THREAD

**Issue by janoskk** [TryGhost/Casper#162]
The line numbers of embedded gists are not aligned to the code.

![screen shot 2015-01-21 at 23 38 59](https://cloud.githubusercontent.com/assets/1554533/5846766/ca9bb8a6-a1c6-11e4-824c-28bbe6915c50.png)

I have an installation of Ghost 0.5.8 + Casper 1.1.5 and tested in Chrome 39 and FF 35 (both under OS X).

**Comment by JohnONolan** [comment]
Ah Github must've updated their Gist CSS or something, so now the custom CSS in casper for Gists is wrong. If you have a fix - feel free to PR and I'll be happy to merge :)

**Comment by janoskk** [comment]
Here we go ;-)

**Comment by JohnONolan** [comment]
Fixed in #163
