### ISSUE TITLE
Ligatures unused although it appears you guys want to be using them

### ISSUE THREAD

**Issue by AlexanderGalen** [TryGhost/Casper#167]
Although to the best of my knowledge the font used for body text, "Merriweather", doesn't have ligatures, I noticed you have set `font-feature-settings: 'liga' 1, 'onum' 1, 'kern' 1;`, but, at least in chrome(but probably most browsers), ligatures won't be enabled even with a font that has them without `text-rendering: geometricPrecision;` or `text-rendering: optimizeLegibility` set.

I guess it's not very important, but just something I noticed.

**Comment by JohnONolan** [comment]
Happy to accept a PR if you can recommend the best way to resolve this

**Comment by AlexanderGalen** [comment]
Just sent a PR.

**Comment by novaugust** [comment]
Hey @AlexanderGalen, it's helpful if part of your commit message includes the text "Closes #167" so that merging it automatically closes this issue at the same time ;)

Fixing up your commit:
```
git commit --amend
git push -f
```

Thanks for taking the time!

**Comment by AlexanderGalen** [comment]
Good idea. I've never really done a pull request before so I'm still figuring it out. Thanks for the tip!
