### ISSUE TITLE
Non-standard definition of transitions

### ISSUE THREAD

**Issue by mankittens** [TryGhost/Casper#168]
Transitions are defined like the following: 

```css
transition: color ease 0.3s;
```

ref: https://github.com/TryGhost/Casper/blob/master/assets/css/screen.css#L237

However, the duration time should be placed before the timing function, like this:

```css
transition: <property> <duration> <timing-function> <delay>;
```

ref: https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Using_CSS_transitions

**Comment by JohnONolan** [comment]
Happy to accept a PR for this

**Comment by mankittens** [comment]
I created a branch in the GitHub client and committed the changes but can't sync the new brach back to Casper. I get the following error:
```
You may not have permission to access Casper. Check Preferences to make sure you’re still logged in.
```
Is it possible I'm doing something wrong, or do I need some kind of permissions to submit a new branch?

Thanks.

**Comment by JohnONolan** [comment]
You need to Fork the Casper repo, check it out, create a branch, make your changes, push the branch back up to your repo. Then when you go to github there should be a nice big "submit pull request" button :)

**Comment by mankittens** [comment]
Hey, I really appreciate you taking the time to respond with detailed instructions, even for a minor thing like this.
