### ISSUE TITLE
Suggestion: Port to SASS

### ISSUE THREAD

**Issue by mankittens** [TryGhost/Casper#169]
I would be happy to rewrite the style file in .scss if it would be added to the repo.

**Pros:**

* Set global colors, fonts, sizes, and spacing with a single variable change
* Decrease lines of code (several hundred)
* Increase code consistency

Cons:

* Increased barrier to entry
* Lower code searchability

**Comment by ARomberg** [comment]
I think that's a good idea. :+1:

**Comment by JohnONolan** [comment]
Whether it's written in CSS or SASS only affects the person maintaining the file - nobody else. Right now, pretty much the only person maintaining the styles in Casper is me - so basically we're talking about a change which would affect nobody except me. This makes it largely a bikeshed / moot point.

The cons you listed are precisely the reason why it's currently in CSS. You also missed one: Smaller codebase.

The pros don't really apply. Want to change colours? Find/replace. You don't decrease lines of code, you increase them with more files (we can't ship casper without uncompiled CSS - that's very inaccessible) - and in such a small file I don't see any advantage to code consistency.

Sass is largely abused. It makes sense in a lot of contexts - there are also a lot of contexts where it makes no sense. This is one of them :)

So, for now at least, we're going to stick to CSS!
