### ISSUE TITLE
GitHub gist line-number line height not aligned to code line-data

### ISSUE THREAD

**Issue by jasonsturges** [TryGhost/Casper#176]
Recent updates to Casper theme now include some CSS for GitHub gists.

Line height is off, not aligning the line numbers and code, as seen here:

![image](https://cloud.githubusercontent.com/assets/1213591/6366829/1701a6f8-bc91-11e4-8a4e-6faf60952bee.png)

WIthin assets/css/screen.css under _Third Party Elements - Embeds from other services_ at [lines 1195-1197](https://github.com/TryGhost/Casper/blob/master/assets/css/screen.css#L1195-1197) line height should be something like:

    .gist .line-number {
        line-height: 1.9em;
    }

Line height should be 1.9em / 2rem / 20px to align.

**Comment by JohnONolan** [comment]
This was fixed in #163 and will be included in the next release - thanks for reporting!
