### ISSUE TITLE
Navigation in Firefox messed up

### ISSUE THREAD

**Issue by brennick** [TryGhost/Casper#178]
![screen shot 2015-02-28 at 5 41 33 pm](https://cloud.githubusercontent.com/assets/8314655/6429090/0d5d0276-bf72-11e4-9e13-f91ee7bd49d2.png)
Just thought I'd report this, not sure if it's just my computer or not. Seemed to be positioned fine in Chrome.

**Comment by JohnONolan** [comment]
@erisds this may require a new release...
