### ISSUE TITLE
'Vh' height not working. The button menu doesn't work.

### ISSUE THREAD

**Issue by kdelfour** [TryGhost/Casper#179]
Hello, the last commit e59dcaa256b07b7c63492c6d0f8792c9bc8376ea break Navigation menu. 
It seems that 'vh' doesn't work correctly instead of '%'. When I click on Menu, nothing appears, No overlay on Menu button. I have changed all 'vh' with '%' and it works correctly.

I'm using Chrome v40.0.2214.115 (64-bit) and Safari Version 5.1.10 (6534.59.10).

**Comment by arcador** [comment]
The last commit modifying screen.css fixes the menu for me. I had the same issue before this fix.

**Comment by novaugust** [comment]
Going to close as fixed; please speak up if this is still an issue
