### ISSUE TITLE
"Burger" font issue

### ISSUE THREAD

**Issue by crepererum** [TryGhost/Casper#186]
The burger (menu button) is implemented differently than all other icons. It uses a `span` + the direct Unicode character instead of a simple icon class element (which then is filled by CSS via `before` or `after`). The result is that it does get `Open Sans` instead of the `casper-icons` font and therefore is not rendered correctly on Android (both Chrome [get a crossed box] and Firefox [get a filled box]; both indicate something like "unknown character").

**Update:** It also seems that the burger character appears normal text and gets interpreted by textbrowser (like lynx) and screen readers. This should never ever be the case for symbols.

**Comment by PaulAdamDavis** [comment]
Good catch, @crepererum – This one is my fault. I've just submitted a PR to improve this.
