### ISSUE TITLE
Footnotes look hideous

### ISSUE THREAD

**Issue by HoddzDJ** [TryGhost/Casper#187]
Not sure if this is just me expecting too much, but the footnotes look hideous. In my eyes they should be a smaller font face and also closer together vertically. I have spent a bit of time trying to fix this but cannot fathom out where the styling is for them, or if there is even any CSS what so ever.

If someone wants to point me in the right direction I will happily have a closer look and see what I can fix up here. Or on the flip side, if everyone is happy to leave them how it is that's fine, just wanted to draw some attention to it more than anything.

**Comment by JohnONolan** [comment]
Agreed - I found this last week and meant to push the fix, done now!

**Comment by HoddzDJ** [comment]
Just downloaded and installed on a local blog, padding is still looking a bit too much, would you  not agree?
