### ISSUE TITLE
Return the old one "Subscribe" button to default theme.

### ISSUE THREAD

**Issue by keiga-san** [TryGhost/Casper#190]
Hello.

After update to new version with `{{navigation}}` there are no more cool hovered "Subscribe" button on the page. Now it's located in the navigation menu. So if i don't need a navigation menu there will be no subscribtion button.

Can you please return it to code if there are no navigation menu is set?

**Comment by JohnONolan** [comment]
Sounds like a sensible suggestion - PR welcome

**Comment by keiga-san** [comment]
Tried to make one.
#191

**Comment by JohnONolan** [comment]
Will come back to this in future
