### ISSUE TITLE
Set text-rendering: auto on code

### ISSUE THREAD

**Issue by kylelemons** [TryGhost/Casper#192]
Currently, in the Casper theme, if you write out `finally` (as an inline code font) you will get the `fi` ligature as a single glyph but the width of the inline block will be one glyph too long.  The solution is to set `text-rendering` to `auto` or `optimizeSpeed` (which disables ligatures), rather than the inherited `geometricPrecision`.

(this also happens in the post editor, but I can live with that)

**Comment by JohnONolan** [comment]
Done in https://github.com/TryGhost/Casper/commit/1196a13aefdfb9954fc85731ba8df361ee447966
