### ISSUE TITLE
Burger menu icon broken

### ISSUE THREAD

**Issue by jbfriedrich** [TryGhost/Casper#199]
It looks like the burger menu icon is broken, even on the demo site: 

## Firefox 37.0.1
![ff-01](https://cloud.githubusercontent.com/assets/1968991/7214584/6d755a3a-e5b2-11e4-992f-44160d2b7c41.png)
![ff-02](https://cloud.githubusercontent.com/assets/1968991/7214587/844e38a8-e5b2-11e4-988f-c2a858811bc1.png)

## Chrome 41.0.2272.118
![ch-01](https://cloud.githubusercontent.com/assets/1968991/7214588/896c6d46-e5b2-11e4-9d08-647bf91bd7ee.png)
![ch-02](https://cloud.githubusercontent.com/assets/1968991/7214589/92160826-e5b2-11e4-8394-4aa0b36bce59.png)

I get this issue with all latest versions of Safari, Chrome and Firefox. It looks like it happens only when the Ghost site is behind a web proxy. Local setups, using 127.0.0.1 work fine for me. Could this be related to isse #186?

**Comment by jbfriedrich** [comment]
Not sure if it is really a problem with the font or a problem with caching. One of my test sites magically started to work. I will put some more time into it to further test and debug this issue.

**Comment by PaulAdamDavis** [comment]
Hi @jbfriedrich, it looks like it might be the same bug you linked to. Could you try out the master version of Casper ([Download zip](https://github.com/TryGhost/Casper/archive/master.zip)) and see if that solves it?

**Comment by jbfriedrich** [comment]
The master version of Casper works out of the box for me. But now the old version works for me as well. It looks like it was a very weird caching issue. Even though the web server was restarted several times and several web browsers were used (and cache was emptied several times). The site http://demo.ghost.io still has a broken menu burger icon for me though.
