### ISSUE TITLE
No indentation when embedding Gist from GitHub - [Casper theme - Chrome]

### ISSUE THREAD

**Issue by alexellis** [TryGhost/Casper#204]
### Issue Summary

While using Chrome 42 on Windows 7 64-bit including an embedded gist from GitHub results in no indentation for the code example. Casper theme.

### Steps to Reproduce

1. Write a blog post
2. Include gist from following location with this code:
```<script src="https://gist.github.com/alexellis/0bb982253f3619e29f18.js"></script>```
3. Publish and review. 

Working example at:
http://quad.ae24.space/nasa-earth-imagery-api/

Any other information you want to share that is relevant to the issue being
reported. Especially, why do you consider this to be a bug? What do you expect to happen instead?

Indentation works fine with IE 11

There appears to be some CSS conflict between the embedded example and the base/Casper theme.

### Technical details:

* Ghost Version: Ghost 0.5 Casper theme
* Client OS: Windows 7
* Server OS: Linux quad 3.18.10-1-ARCH #1 SMP PREEMPT Wed Mar 25 20:03:15 MDT 2015 armv7l GNU/Linux
* Node Version: v0.12.2
* Browser: Chrome 42
* Database: SQLite

![image](https://cloud.githubusercontent.com/assets/6358735/7370631/5526e0a8-edb3-11e4-91a8-df6b982618b9.png)

**Comment by JohnONolan** [comment]
@alexellis Please update Ghost to 0.6.2 and Casper to 1.2.2

**Comment by alexellis** [comment]
It will take me some time to perform this upgrade due to having to add analytics and disqus on every upgrade (tedious exercise). In the meantime is anyone able to try to reproduce the issue to see if it's current? Or are you saying this has been addressed already?

**Comment by JohnONolan** [comment]
@alexellis We don't know - it's up to you to tell us. It's more time consuming for us to check bugs reported against old versions only to find that they've already been resolved than for you to update to the latest version.

You can now add Disqus's JS and analytics JS via code injection - which should make things easier in future: http://blog.ghost.org/code-injection/

Closing this for now - feel free to comment if it's still an issue when you find time to upgrade and we can reopen if it's still a problem.

**Comment by rajeevedmonds** [comment]
Tested with latest Ghost (0.6.2) and Casper (1.2.2) builds. The issue persists as reported above.

Google Chrome : 43.0.2357.37 beta-m (64-bit) - Win 8.1 64-bit

**Comment by alexellis** [comment]
Thanks @rajeevedmonds.

I have also confirmed issue persists on Ghost 0.6.2 / Casper 1.2.2 / Node: 0.12.2. 

@JohnONolan Suggest re-open.

**Comment by JohnONolan** [comment]
Excellent, in that case: PRs welcome.

**Comment by dbalders** [comment]
Huh, this is what it looks like for me (all working?):

Chrome:
![chrome](https://cloud.githubusercontent.com/assets/4715098/7549229/cbe669d0-f5e1-11e4-9337-d41176344b2c.png)

Firefox:
![firefox](https://cloud.githubusercontent.com/assets/4715098/7549230/d208d3de-f5e1-11e4-92fe-a077b6f2b75d.png)

Safari:
![safari](https://cloud.githubusercontent.com/assets/4715098/7549232/da7c75ac-f5e1-11e4-8671-0516a15939ae.png)

**Comment by mischkl** [comment]
@dbalders that looks like a file with tabs for indentation. my guess is it only applies to indentation using spaces.

**Comment by alexellis** [comment]
@dbalders  What OS and browser versions are you using? Looks exactly the same on Chrome 42.0.2311.135m (latest) with Windows 7 64-bit. Just taken another screenshot on home PC, same details as above

![image](https://cloud.githubusercontent.com/assets/6358735/7550044/3982e384-f64a-11e4-85f1-41d42d2240c6.png)

**Comment by dbalders** [comment]
@alexellis I am using Mac OS 10.10 and the latest of each of the 3 browsers. I am assuming that it looks normal for you when you go to https://gist.github.com/alexellis/0bb982253f3619e29f18#file-getnasaearth-js correct?

**Comment by intrd** [comment]
Just for note..
The casper solution `text-rendering: auto;` does not work on my theme. I solved the identation probblem by commenting `body { letter-spacing: -1px; }`

Before..
![image](https://cloud.githubusercontent.com/assets/2204686/21953978/34a8d5a4-da2c-11e6-901a-628f7f0ac431.png)

After..
![image](https://cloud.githubusercontent.com/assets/2204686/21953993/95d08642-da2c-11e6-9f60-bb51e247d860.png)

thanks btw.
