### ISSUE TITLE
Menu button border styles differ between index and single on mobile devices

### ISSUE THREAD

**Issue by novaugust** [TryGhost/Casper#205]
Originally posted by @jschaich

-----------------------------------------------

### Issue Summary

When opening a blogpost an a small screen or mobile device the menu button gets suddenly a box around itself.

### Steps to Reproduce

1. Visit i.e. https://thejester.at
2. Open a random post
3. See the change of the Menu button:

![screenshot_2015-04-30-00-41-33](https://cloud.githubusercontent.com/assets/11455444/7409239/fcf29c56-ef24-11e4-87df-17f763e01c51.png)

This is a bug because it looks kind of odd to me and does not fit to the rest of the experience.

### Technical details

* Ghost Version: 0.6.2
* Casper Version: 1.2.2
* Client OS: Android 5.1 
* Server OS: Ubuntu 14.04
* Node Version: 
* Browser: Chrome
* Database:

**Comment by novaugust** [comment]
false alarm; not an issue with casper, but with customizations of casper. Closing

**Comment by hkalant** [comment]
I reported this on Slack last week I think. @PaulAdamDavis fixed this in #203.

**Comment by jschaich** [comment]
awesome, thanks a lot!

**Comment by jschaich** [comment]
great, that fixed it!
