### ISSUE TITLE
Question: Where do I find post.hbs?

### ISSUE THREAD

**Issue by catherineberaud** [TryGhost/Casper#209]
Hi 
Sorry for the basic question. I'm trying to add the facebook comments to my blog but I don't know how to find my post.hbs file. I'm using Ghost Pro and simply drag and drop images directly on the webpage and also write directly on the webpage. I don't directly see the files and directories. 

Can anyone help? Thanks!
PS: I'm using the Casper theme

**Comment by nuclearpengy** [comment]
hi @catherineberaud.
On Ghost(Pro) users don't have direct access to the source. If you'd like to upload a custom theme file the best thing is to jump onto the support Slack (https://ghost.org/slack/) or contact support@ghost.org.

**Comment by catherineberaud** [comment]
Thank you. I'll follow up with the support team.

**Comment by catherineberaud** [comment]
Thank you. I'll follow up with the support team.

**Comment by catherineberaud** [comment]
Thank you. I'll follow up with the support team.

**Comment by catherineberaud** [comment]
Thank you. I'll follow up with the support team.

**Comment by nuclearpengy** [comment]
:)
