### ISSUE TITLE
Japanese glyphs can't be correctly displayed on iPhone

### ISSUE THREAD

**Issue by TonnyXu** [TryGhost/Casper#212]
When the post is written in Japanese, and viewing the contents in iPhone Safari, the font can't be shown correctly.

![](https://scontent.xx.fbcdn.net/hphotos-xta1/v/t1.0-9/1623754_10207035602551488_4088174945468614208_n.jpg?oh=13d352522f2c8742195bcb4513f4a623&oe=55F1EFC2)

I've personally added some font specification in my personal site, but don't know if it's the best solution to do.

Here is the changes I've made:

```diff
$ diff screen.css screen.origin.css
121c121
<     font-family: "casper-icons", "Open Sans", "Hiragino Kaku Gothic Pro", sans-serif;
---
>     font-family: "casper-icons", "Open Sans", sans-serif;
188c188
<     font-family: "Merriweather", "Hiragino Mincho Pro", serif;
---
>     font-family: "Merriweather", serif;
215c215
<     font-family: "Open Sans", "Hiragino Kaku Gothic Pro", sans-serif;
---
>     font-family: "Open Sans", sans-serif;
506c506
<     font-family: 'Open Sans', "Hiragino Kaku Gothic Pro", sans-serif;
---
>     font-family: 'Open Sans', sans-serif;
701c701
<     font-family: "Open Sans", "Hiragino Kaku Gothic Pro", sans-serif;
---
>     font-family: "Open Sans", sans-serif;
873c873
<     font-family: "Open Sans", "Hiragino Kaku Gothic Pro", sans-serif;
---
>     font-family: "Open Sans", sans-serif;
882c882
<     font-family: "Merriweather", "Hiragino Mincho Pro", serif;
---
>     font-family: "Merriweather", serif;
964c964
<     font-family: "Open Sans", "Hiragino Kaku Gothic Pro", sans-serif;
---
>     font-family: "Open Sans", sans-serif;
1313c1313
<     font-family: "Merriweather", "Hiragino Mincho Pro", serif;
---
>     font-family: "Merriweather", serif;
1399c1399
<     font-family: "Open Sans", "Hiragino Kaku Gothic Pro", sans-serif;
---
>     font-family: "Open Sans", sans-serif;
1487c1487
<     font-family: "Open Sans", "Hiragino Kaku Gothic Pro", sans-serif;
---
>     font-family: "Open Sans", sans-serif;
1571c1571
<     font-family: "Open Sans", "Hiragino Kaku Gothic Pro", sans-serif;
---
>     font-family: "Open Sans", sans-serif;
```

**Comment by TonnyXu** [comment]
I haven't tested the case for Chinese/Korean characters yet, so it's just a quick fix for my personal site. I will take some time to test those 2 languages.

**Comment by TonnyXu** [comment]
I just tested on Chinese/Japanese/Korean, here is the result page: http://tonny.mobi/2015/06/17/ghost-font-issue-in-cjk/

You can see Chinese font are still not good enough.

**Comment by hiroqli** [comment]
My iPhone, Japanese environment, can display Japanese glyphs correctly without "Hiragino Mincho Pro" in screen.css. 
And, we need discuss about using "Hiragino Mincho Pro".

**Comment by TonnyXu** [comment]
@hiroqli I think I understand the reason, because you set your region and default language to Japanese. If you set your OS language to English and you will see the broken glyphs. That's because `san-serif` and `serif` will mapping to the default font to the system language's font.

**Comment by JohnONolan** [comment]
Fork of the theme is the correct solution for now, in future we'd definitely like to have comprehensive support for i18n

**Comment by mecab** [comment]
@TonnyXu FYI I have just forked the theme for Japanese environment: https://github.com/mecab/Casper-ja . It also includes the issues related to ligature (#227) and some minor adjustment for Ja. I hope it helps you.
