### ISSUE TITLE
iPhone 5* Safari portrait breakpoint with cover image styling looks broken

### ISSUE THREAD

**Issue by jeromecovington** [TryGhost/Casper#215]
The cover image is very tall (requiring quite a bit of scrolling to get past it) and the post summaries overlap with the bottom of the cover image.

I noticed this on http://www.ethicaldeveloper.com but I have noticed it on other blogs running Casper, as well. Is there another issue or PR against this?

![iphone5-1](https://cloud.githubusercontent.com/assets/486493/8651427/bed43040-2946-11e5-911a-d20e16f8a813.png)
![iphone5-2](https://cloud.githubusercontent.com/assets/486493/8651426/bed39694-2946-11e5-91f0-a02e5a9e361c.png)
![iphone5-3](https://cloud.githubusercontent.com/assets/486493/8651428/bed7b0a8-2946-11e5-9df8-e1f1c63e4568.png)

**Comment by ArekSredzki** [comment]
I have noticed this as well

**Comment by ripper2hl** [comment]
:+1: fix this please, same problem on iphone 4

**Comment by JohnONolan** [comment]
PRs welcome

**Comment by sturobson** [comment]
I had a spare five minutes so thought I'd take a look at this. @jeromecovington you've changed themes I see - which other sites using Casper have this issue?

**Comment by BrianDGLS** [comment]
I can't replicate this. I notice the issue is from mid 2015, so perhaps this issue can be closed.

**Comment by JohnONolan** [comment]
Agreed - will re-open if anyone can reproduce
