### ISSUE TITLE
Building system

### ISSUE THREAD

**Issue by homaily** [TryGhost/Casper#219]
Hello folks,

Do you use a build tool to build Casper template javascript & css like Grunt or Gulp?

**Comment by nuclearpengy** [comment]
Ghost themes use handlebars, not sure if that helps.

**Comment by homaily** [comment]
Hello Nathan, Thanks for the super fast respond!

Do you use any building tool for CSS? or do you write the css directly to assets/css/screen.css?

**Comment by ErisDS** [comment]
We native CSS & JS - there are no build tools, if there were they'd be here in the repo :wink:

**Comment by nuclearpengy** [comment]
@homaily check out this link: http://themes.ghost.org

**Comment by homaily** [comment]
Thanks Hannah. I thought you might have a separate repo to build the template it's kinda unusual not having a build tool for CSS & JS these days :)

I plan to translate Casper to Arabic and it will be much easier if there is a building tool to automate the CSS flipping task.


Thanks folks. Really appreciate your fast responses.

**Comment by nuclearpengy** [comment]
check out https://github.com/TryGhost/Ghost/issues/3801 for internationalisation, also consider joining our Slack community: https://ghost.org/slack/

There is a channel dedicated to theme development. :)

**Comment by homaily** [comment]
I just did. Thanks Nathan.

**Comment by nuclearpengy** [comment]
:grinning: :+1:
