### ISSUE TITLE
Add additional social icons

### ISSUE THREAD

**Issue by cwonrails** [TryGhost/Casper#220]
Right now the icons section includes Ghost, the RSS feed, Twitter, Google Plus, and Facebook.

Additional icons for LinkedIn, AngelList, Dribble, and GitHub would be very welcome.

**Comment by JohnONolan** [comment]
If you need other icons, by all means fork and customised. The default theme is intended as just that: a default. It should solve 90% of use cases without introducing bloat for the last 10%. The beauty of open source is that you aren't locked in to what is provided.
