### ISSUE TITLE
How to add "Home" button to return to the main page of the blog?

### ISSUE THREAD

**Issue by online** [TryGhost/Casper#225]
Hello!

Tell me, please, how to add a Home button like in this theme ([Attila](http://attila.zutrinken.com/headlines-blockquotes/))?

I mean this button:

![2015-12-18 23 00 15](https://cloud.githubusercontent.com/assets/722881/11907275/3d82cd78-a5db-11e5-9ab4-320e0e3d5f31.png)

I would very much like to see this button in the standard theme Casper.

**Comment by roll** [comment]
Going to fork the theme to add the button. It's not a big deal but just curious why you don't have it by default?)

**Comment by JohnONolan** [comment]
Because the logo links to the homepage and there is a home link in the navigation menu - http://demo.ghost.io/the-businessman-the-fisherman/

**Comment by roll** [comment]
Thanks! The reason of confusion was because default blog setup for Ghost(Pro) doesn't have a logo uploaded so it looked like there is no home button at all.

**Comment by JohnONolan** [comment]
Fair point - Casper is definitely due for a few updates :)
