### ISSUE TITLE
Merriweather "fi" ligature renders as "i"

### ISSUE THREAD

**Issue by nybblr** [TryGhost/Casper#235]
Looks like Google fonts updated Merriweather in January, and now all Casper-based themes look like this in Chrome, Safari, and Firefox:

<img width="741" alt="screen shot 2016-01-23 at 4 49 05 pm" src="https://cloud.githubusercontent.com/assets/794113/12533034/3c68cf8c-c1f1-11e5-97f9-81adcf83a878.png">

Ligatures like "fi" => "i"

https://www.google.com/fonts/specimen/Merriweather

Turning off the `liga` feature fixes it, but not sure if this is a Merriweather issue, or outstanding tech debt in Casper styles.

**Comment by TomChantler** [comment]
I'm impressed nybblr. I just noticed this (about hour ago) on my blog but had not yet worked out a fix. It renders fine on my Windows Phone and in Microsoft Edge on my desktop. Presumably the working browsers don't support ligatures.

Also it highlights the risks of using external fonts. Imagine if somebody changed the letters around for fun and it made your text all sweary and gibberish!

**Comment by juice49** [comment]
I also noticed this just an hour or so ago! @nybblr you mention turning off `liga`is a workaround, but I could not work out how to do this. I tried disabling the `font-feature-settings: 'liga' 1, 'onum' 1, 'kern' 1;` CSS rules, but this doesn't appear to have any effect. I temporarily switched themes in the end.

FYI I have used the Ghost demo page as a test of this. There are a couple of examples ("specific" and "defined") under the [code section](https://demo.ghost.io/style-test/#code) the show the problem.

**Comment by nybblr** [comment]
I just dropped some styles into my Code Injections => Blog Header:

```html
<style>p,ul,ol,dl{
-webkit-font-feature-settings: 'liga' 0, 'onum' 1, 'kern' 1;
-moz-font-feature-settings: 'liga' 0, 'onum' 1, 'kern' 1;
-o-font-feature-settings: 'liga' 0, 'onum' 1, 'kern' 1;
}</style>
```

**Comment by juice49** [comment]
Odd, that doesn't work at all for me. Not sure why that is, but thanks very much for the help!

**Comment by jameslex** [comment]
Great catch!

**Comment by JohnONolan** [comment]
Yep - hoping that Google resolve this pronto, but if not then we'll ship an update

**Comment by JohnONolan** [comment]
According to Google a fix for this will be pushed tomorrow: https://github.com/google/fonts/issues/8

**Comment by davelab6** [comment]
The update to merriweather was made in advance of the Firefox 44 launch on Tuesday that will mean the old files will just stop working. 

However, there is 1 bug with fi/fl ligatures (which will be fixed monday morning PST) and an issue with the new design being a little darker than before especially on Macs. 

You can turn ligatures off with CSS to work around this until then:

    -webkit-font-feature-settings: 'liga' 0, 'onum' 1, 'kern' 1;
    -moz-font-feature-settings: 'liga' 0, 'onum' 1, 'kern' 1;
    -o-font-feature-settings: 'liga' 0, 'onum' 1, 'kern' 1;
    font-feature-settings: 'liga' 0, 'onum' 1, 'kern' 1;

**Comment by novaugust** [comment]
Google's published the fix

**Comment by davelab6** [comment]
The fix is now pushed all the way through the Fonts API :)
