### ISSUE TITLE
.author-thumb lacks object-fit or similar

### ISSUE THREAD

**Issue by justinboden** [TryGhost/Casper#237]
The author thumbs which display on the index page gets squashed or stretched if the author profile image isn't perfectly square. Fixed it for myself by setting object-fit: cover to the css doc, on line 974.

**Comment by JohnONolan** [comment]
Hi @justinboden - I'm afraid I can't reproduce this. If you could add all the proper info needed to diagnose (screenshot, URL, browser name, browser version, Ghost version, Casper version, etc) then I'd be happy to take a look.

**Comment by justinboden** [comment]
Sure thing! 

Casper: 1.2.7
Ghost: 0.7.5
Chrome Browser: 47.0.2526.111
URL: greatscott.media (fixed version)

Screencap taken from index page:
![screenshot 2016-02-03 16 05 01](https://cloud.githubusercontent.com/assets/5818930/12773914/27fec932-ca90-11e5-9a80-4dfa3f1b9fc3.png)

Zoomed-in to make stretching more apparent:
![screenshot 2016-02-03 16 05 18](https://cloud.githubusercontent.com/assets/5818930/12773937/59f83b80-ca90-11e5-8131-1d04e5d17926.png)

Original image for context:
![image](https://cloud.githubusercontent.com/assets/5818930/12773977/ac902fb0-ca90-11e5-9a2a-42af776820c2.png)

And with my 'fix':

![screenshot 2016-02-03 16 11 49](https://cloud.githubusercontent.com/assets/5818930/12773997/da3aa31e-ca90-11e5-9d0e-ee4e3c5e96b3.png)

Apologies if this error is only produced by settings on my end, but I was able to reproduce it with Ghost running locally on my machine and on the live page.

**Comment by JohnONolan** [comment]
Ah yes, I see it now - https://github.com/TryGhost/Casper/blob/master/partials/loop.hbs#L16 needs to be an a tag with a background image

**Comment by allistercsmith** [comment]
Noticed this in my blog too, and found this open issue. Whipped up a quick PR with a fix :)
