### ISSUE TITLE
Bug: Adding Google Custom Search for Casper theme displays input box incorrectly due to padding in css table def

### ISSUE THREAD

**Issue by packled** [TryGhost/Casper#242]
Issue Summary
Bug: Adding Google Custom Search for Casper theme displays input box incorrectly due to padding in css table definition (low priority)

Steps to Reproduce
- Add Google Custom Search box and you will see the input field is displayed lower than it should be.

This is a bug because...
It looks wrong

Technical details
The issue is in screen.css for the Casper theme.
table th,
table td {
padding: 8px;
line-height: 20px;
text-align: left;
vertical-align: top;
border-top: #EFEFEF 1px solid;
}
If the "padding: 8px" is removed, it displays correctly. Removing it is probably not the best course of action however since it would affect other areas so perhaps just a mention in the docs for now.

My workaround was to define a static page for the Search and then put put in a "style" with padding: 0px to override.

This works totally fine for me so this is a very low priority issue but wanted to make you aware since people may run into this very easily.

Ghost Version: master - latest commit: INSERT COMMIT REF - Ghost-0.7.7
Client OS: MacOS El Capitan and Ubuntu 14
Server OS: MacOS El Capitan and Ubuntu 14
Node Version: v0.12.4
Browser: All latest versions

**Comment by novaugust** [comment]
Hey @packled, Casper's display having problems after you modify isn't really a bug with the theme; it's a result of your modification. This isn't something that we're going to modify Casper for.
That said, there's an easy way to add custom CSS to whatever theme you're using, and thereby fix for your modification without having to modify the theme itself: add the necessary styling in your `ghost-head` code-injection field (<your-blog.com>/ghost/settings/code-injection)
ie
```
<style>
/* fix issue with google search box */
input {padding: 0;}
</style>
```

**Comment by packled** [comment]
Hi, the display was having problems by default. I modified the theme as part of troubleshooting the display issue. Out of the box, if you add Google Custom Search, the display is broken. Your suggested workaround is not really acceptable since it will affect the entire theme, which is why I localizes the style to just a custom static page.
