### ISSUE TITLE
Bio post preview markdown

### ISSUE THREAD

**Issue by madroneropaulo** [TryGhost/Casper#244]
The post preview on the Authors bio pages doesn't show correctly markdown.

**Comment by acburdine** [comment]
@madroneropaulo could you please give a bit more description for this issue? 

The author bio page uses the same theme code to render markdown that the main page does, and likely this is an issue with Ghost itself, and there are already several issues open there about it.

**Comment by bluezhan** [comment]
Why and demo is not the same ~~~ the theme

**Comment by JohnONolan** [comment]
Author bios don't support markdown.
