### ISSUE TITLE
"Incorrect password" notification for private blogs

### ISSUE THREAD

**Issue by surdaft** [TryGhost/Casper#253]
I have just noticed that if one were to type in a password incorrectly on a private blog then the notification shows in the bottom left, totally away from the main content. This isn't really a bug but I feel it would be more user friendly to potentially show it above the field or something, just so that it isn't confusing for any one who doesn't spot it way in the bottom left there.

![screen shot 2016-06-21 at 10 44 06](https://cloud.githubusercontent.com/assets/8268249/16225134/1aa1f71c-379d-11e6-8b72-7c00daa5f25c.png)

**Comment by acburdine** [comment]
@surdaft Thanks! Actually though, this is a bug with Ghost itself, using the default private.hbs template.

If you like, could you re-open another issue on that repo?

**Comment by surdaft** [comment]
Ohh, sorry I didn't notice that, alright will do. Thanks for that @acburdine :)
