### ISSUE TITLE
Embedded Gists Styling

### ISSUE THREAD

**Issue by jgable** [TryGhost/Casper#26]
Someone on twitter has reported that the styles of embedded gists look a little wonky.

You can include this tag in a post to test it out for yourself.

``` html
<script src="https://gist.github.com/jgable/6598091.js"></script>
```

**Comment by intrd** [comment]
I'm trying to style embedded gists here, it seems to work, but when site finishes loading completely, it goes back to the standard of the gist .. any solution?
