### ISSUE TITLE
Author picture is over lapping, mobile view portrait

### ISSUE THREAD

**Issue by pascalandy** [TryGhost/Casper#261]

**Comment by pascalandy** [comment]
<img width="434" alt="author-2016-07-27_22h54" src="https://cloud.githubusercontent.com/assets/6694151/17199732/11462c0c-544d-11e6-929d-8493504e643e.png">

**Comment by kevinansfield** [comment]
Hi @pascalandy, which version of Ghost/Casper are you using? This issue was fixed in https://github.com/TryGhost/Casper/commit/09b48303987fdc8f5185cca3c81e215da638d8cf that was released as part of Ghost 0.8.0 and 0.9.0.

**Comment by pascalandy** [comment]
I see now it was fixed in 1.31. I was using 1.28.

Thanks!
