### ISSUE TITLE
Subscribe box glitch - iPhone 6+* Safari portrait

### ISSUE THREAD

**Issue by pascalandy** [TryGhost/Casper#263]
Here the text within the button is weird. 
It should probably have the same size as the subtitle.

I bigger view mode, it's solid!  

![2016-07-29_15h45 issue](https://cloud.githubusercontent.com/assets/6694151/17261435/ad8f4e70-55a3-11e6-9c29-3bf7ed9e1507.jpg)

**Comment by sarandford** [comment]
I tested this on Chrome, Safari, and Firefox and it no longer appears to be an issue. I think this should be closed. 
<img width="473" alt="screen shot 2017-03-30 at 9 26 05 am" src="https://cloud.githubusercontent.com/assets/9602895/24506296/0063fa8c-152b-11e7-8518-bf37a7fd0af9.png">

**Comment by pascalandy** [comment]
Agreed :)
