### ISSUE TITLE
.nav-opened .menu-button flickers in Safari for OS X when background is changed.

### ISSUE THREAD

**Issue by jamespayne** [TryGhost/Casper#265]
Hi, I have an issue where I am attempting to change the default colour of the menu in Casper and in Safari 9.1.2 on El Capitan 10.11.6 (15G31), the colour of the .menu-button class flickers. Have tried it in Chrome and it does not happen. I am on Ghost 0.9.0. See gif below. Any idea what might be causing this?

![flicker](https://cloud.githubusercontent.com/assets/72580/17690622/2e26a672-63d3-11e6-8705-64bdd1e141f0.gif)

I'm basically trying to change the background to a dark purple colour. Considering it doesn't happen in Chrome, it appears that it might be a webkit issue.

I have had a look around and some people have suggested changing various parts of the CSS based on other people's suggestions on the web but nothing seems to fix the problem. If anybody has any suggestions, that would be great. Thanks!

Edit: Just to add to this, the flicker sometimes goes to the correct colour but sometimes turns to the brown colour and stays after load.

I have also checked (just to make sure) by reverting back to the original screen.css. Maybe my problem is that I should be overriding with a custom css that loads after screen.css instead of cloning Casper? To make that clear, I have created a copy of the casper theme and modified my package.json to suit my own theme name.

**Comment by JohnONolan** [comment]
Sorry but this isn't a bug :) if you need help modifying a theme then please head over to our slack team - slack.ghost.org
