### ISSUE TITLE
Ellipsis fill in navigation looks weird in Firefox

### ISSUE THREAD

**Issue by Fahrradflucht** [TryGhost/Casper#270]
I noticed (while using Firefox) that in the navigation every item has those three ellipsis dots and wanted to remove them because I thought they looked ugly. While investigating I realized that in Safari and Chrome the ellipsis dots are used to fill the whole line and that the selected one becomes a real line.

Here is a screenshot taken on Firefox 50.0a2 (2016-09-11):
<img width="276" alt="screenshot 2016-09-17 15 38 20" src="https://cloud.githubusercontent.com/assets/13237661/18608554/d2f24756-7cec-11e6-89d1-60cfe7934bc2.png">

And here is a screenshot taken on Safari Release 13 (Safari 10.0, WebKit 11603.1.5):
<img width="282" alt="screenshot 2016-09-17 15 39 23" src="https://cloud.githubusercontent.com/assets/13237661/18608559/ff059e2e-7cec-11e6-9935-5ea628ff6c52.png">

Is this intentional?

**Comment by JohnONolan** [comment]
The safari behaviour is intentional, the firefox behaviour is a firefox bug :)
