### ISSUE TITLE
Add reddit share to casper fonts

### ISSUE THREAD

**Issue by wikimatze** [TryGhost/Casper#278]
Hi Daniel,

is it possible to add an icon for it?

Cheers from Berlin!

**Comment by wdherndon** [comment]
Hi!

I already added reddit share and a few others,

but the changes were rejected.

Casper should be kept super-simple IIRC.

In any case, you can find my modified Casper at:

https://github.com/wdherndon/Casper


Greetings from Marburg!

Bill

**Comment by wikimatze** [comment]
I'll watch your fork in order to stay informed. Best regards to wonderful Marburg.
