### ISSUE TITLE
Add Reddit as a share option

### ISSUE THREAD

**Issue by jimmyjump** [TryGhost/Casper#280]
It will be nice to also add Reddit by default as an option to share post.

**Comment by wdherndon** [comment]
If you look through the old issues, this has been suggested (multiple times) before, and rejected. This is why I made my own version - it has reddit and a few others:
https://github.com/wdherndon/Casper

**Comment by acburdine** [comment]
@jimmyjump as @wdherndon said, this has been raised and rejected several times in the interests of keeping Casper as simple as possible :)
