### ISSUE TITLE
Misuse of section elements in footer

### ISSUE THREAD

**Issue by Heydon** [TryGhost/Casper#287]
The footer contains two `<section>`s. There is no need to produce these semantics / navigational cues (in screen reader software) for such small runs of content.

In **default.hbs**:

```html
<footer class="site-footer clearfix">
  <section class="copyright"><a href="{{@blog.url}}">{{@blog.title}}</a> &copy; {{date format="YYYY"}}</section>
  <section class="poweredby">Proudly published with <a href="https://ghost.org">Ghost</a></section>
</footer>
```

I recommend changing them to paragraphs.

**Comment by JohnONolan** [comment]
This is a total bikeshed.

**Comment by Heydon** [comment]
@JohnONolan No it isn't, and two likes says you're outnumbered. Sections are exposed as regions in AT. Where they are misused they are obstructive to screen reader users. This is simply poor HTML.

**Comment by WaqasIbrahim** [comment]
I agree with @Heydon.
https://www.w3.org/TR/html5/sections.html#the-section-element

> The section element represents a generic section of a document or application. A section, in this context, is a thematic grouping of content. The theme of each section should be identified, typically by including a heading (h1-h6 element) as a child of the section element.

> Examples of sections would be chapters, the various tabbed pages in a tabbed dialog box, or the numbered sections of a thesis. A Web site's home page could be split into sections for an introduction, news items, and contact information.

This actually is not semantically correct, they should be replaced with a paragraph tag.

**Comment by jpw** [comment]
Hi folks, 

Even if one is in doubt over the semantics, those `section`s would appear to present an annoyance to screen reader users, as described here;
http://www.weba11y.com/blog/2016/04/22/screen-reader-support-for-new-html5-section-elements/

They don't appear to me to be paragraphs either.  Fortunately, HTML5 has breathed new life into the `small` element, and the example given in [the specs](https://www.w3.org/TR/html5/text-level-semantics.html#the-small-element) seems ideal for this case;

> The small element represents side comments such as small print.
> Small print typically features disclaimers, caveats, legal restrictions, or copyrights.

To quote [HTML5 Doctor on `small` & `hr` elements](http://html5doctor.com/small-hr-element/#element-small);

> small is now for side comments, which are the inline equivalent of aside — content which is not the main focus of the page. A common example is inline legalese, such as a copyright statement in a page footer, a disclaimer, or licensing information.

**Comment by Heydon** [comment]
@jpw Sounds reasonable to me, but I'm not sure if any AT exposes `<small>` as such?

**Comment by jpw** [comment]
@Heydon I'm not sure either! :) On the upside, as [ARIA role="contentinfo" is implicit in `footer`](http://w3c.github.io/html/sections.html#the-footer-element) I would personally consider that enough signposting for AT's -- especially because as soon as the content is perceived the meaning will be obvious. I think the emphasis here is on reducing any obstructions to that perception.
