### ISSUE TITLE
Microformats 2 supprt

### ISSUE THREAD

**Issue by jaduncan** [TryGhost/Casper#290]
There's a pull request at https://github.com/TryGhost/Casper/pull/29 regarding MF2 support in casper, but it was rejected on the basis of MF2 being something undevelped. Three years down the line, I'm wondering if you'd accept that or an updated PR to support MF2 and Indieweb bits?

**Comment by JohnONolan** [comment]
We've since adopted automatic microformats support in Ghost core via JSON+LD, which we went for because it's abstracted away from the theme and so "just works" everywhere :)

**Comment by jaduncan** [comment]
That's excellent news, but at the moment https://john.onolan.org/en-route-to-mauritius/ isn't validating for the basics of microformats2 h-entry classnames (e-content, p-name, dt-published, u-url - see http://microformats.org/wiki/h-entry for the extended bits) or author (p-author h-card and/or rel=author - see http://microformats.org/wiki/h-card). In addition, the https://john.onolan.org/ doesn't support h-card.

I can submit issues to core for this, if that's preferred and/or attempt to generate a PR for you. I just thought I'd check on this issue before I start.

**Comment by JohnONolan** [comment]
Sorry, I should have been more clear: We're using the schema.org specification via JSON+LD. The output of which is valid, and can be verified here: https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fjohn.onolan.org%2Fen-route-to-mauritius%2F

At the moment we still don't think that the microformats2 approach is the right way to go or will offer significant benefits beyond our existing structured data -- particularly at the cost of a significant amount of additional clutter in the HTML

**Comment by kevinmarks** [comment]
Schema isn't microformats. There is no public parser for it, just some opaque stuff at Google. The supposed clutter is much terser than schema. See http://www.kevinmarks.com/microformatschema.html

**Comment by jaduncan** [comment]
I also wonder if you'd rethink the view that there's a lot of clutter if you have a moment to look at PR #29 again? There's a total of 46 added characters to index.hbs and 91 characters to post.hbs, so it isn't what I'd call particularly heavy (although I appreciate you might want a new PR focussed on the core rather than the theme).

**Comment by JohnONolan** [comment]
You're (both) very welcome to add microformats 1/2/any-other to your themes, but this isn't something we're going to include in the default theme at the moment. I have no opinion on any politics RE schema-vs-microformats other than that schema has a concrete use-case and benefit which justifies its inclusion :)
