### ISSUE TITLE
How to have Ghost select another theme than Casper on first start.

### ISSUE THREAD

**Issue by pascalandy** [TryGhost/Casper#292]
Hi,
As I customize my themes locally, it would be very practical for me to have Ghost using another theme than Casper when it's initializing. 

Is there any doc about this ?
Thank you!

**Comment by JohnONolan** [comment]
This isn't related to the casper theme, please have a look over our contributing guidelines for info on the best places to get help w/ questions and feature requests https://github.com/TryGhost/Ghost/blob/master/.github/CONTRIBUTING.md

**Comment by pascalandy** [comment]
You're right John, this is maybe a CLI related question. It's a real challenge for most folks to know where to ask a question. I'll do better next time :)

**Comment by JohnONolan** [comment]
> It's a real challenge for most folks to know where to ask a question.

That is why we have https://github.com/TryGhost/Ghost/blob/master/.github/CONTRIBUTING.md which outlines exactly how to solve that challenge
