### ISSUE TITLE
Import WP-stuff with cyrillic slugs

### ISSUE THREAD

**Issue by suncheez** [TryGhost/Casper#293]
I've met an issue when was trying to import WP-content to the Ghost, where were a lot of cyrillic slugs in URLs — a lot of them exceeded the 150 symbols limit because of UTF encoding that looks like 

> "slug":"%d1%81%d0%bc%d0%b5%d1%80%d1%82%d1%8c-%d0%b6%d0%b8%d0%b7%d0%bd%d0%b8"

I suggest increasing the limit or autoconvert such slugs to transliteration.

Thanks.

**Comment by suncheez** [comment]
While it is not fixed, the dirty workaround is:
# vi ghost.json
:%s/%d//g
:wq

That will screw all URLs for posts, but at least will cut them under 150 chars limit.

**Comment by JohnONolan** [comment]
This isn't related to the Casper theme
