### ISSUE TITLE
Subscribe button may cover menu item

### ISSUE THREAD

**Issue by PaszaVonPomiot** [TryGhost/Casper#300]
### Issue Summary

For mobile users if menu has many entries the subscribe button will cover one menu item.

### Steps to Reproduce

1. Create about 16 menu entries
2. In Chrome development mode switch to tablet mode
3. Pick iPhone 5 dimensions
4. Open side menu on homepage

### Technical details:

Ghost Version: alpha.18 installed via ghost-cli
ghost-cli Version: 1.0.0-alpha.16
Node Version: v6.10.0
OS: Debian 3.16.39-1+deb8u1
Database: MariaDB 10.0.29
Browser: Comodo Dragon

### Screenshot

![image](https://cloud.githubusercontent.com/assets/5560454/24723773/0eaf10c2-1a49-11e7-9735-8abcafebec0b.png)

**Comment by JohnONolan** [comment]
This is intentional - the menu can still be scrolled to reveal the content below the button. Having this many menu items is an edge-case, so doesn't need a perfect solution
