### ISSUE TITLE
Merriweather font don't pass Firefox Nightly stricter validation

### ISSUE THREAD

**Issue by fczuardi** [TryGhost/Casper#303]
Steps to reproduce:

- Using a [Firefox Developer Edition](https://www.mozilla.org/en-US/firefox/developer/) browser, open a blog with the default theme
- Open the console and check the error messages.

Expected behavior:

The text displays in a nice font.

Actual behavior:

The browser fallbacks to the default serif, which is tiny and uglier.

Error output:

```
downloadable font: Layout: DFLT script doesn't satisfy the spec. DefaultLangSys is NULL (font-family: "Merriweather" style:normal weight:300 stretch:normal src index:2) source: https://fonts.gstatic.com/s/merriweather/v15/ZvcMqxEwPfh2qDWBPxn6nkZRWJQ0UjzR2Uv6RollX_g.woff2  css:26:12
downloadable font: Layout: Failed to parse script table 0 (font-family: "Merriweather" style:normal weight:300 stretch:normal src index:2) source: https://fonts.gstatic.com/s/merriweather/v15/ZvcMqxEwPfh2qDWBPxn6nkZRWJQ0UjzR2Uv6RollX_g.woff2  css:26:12
downloadable font: GSUB: Failed to parse script list table (font-family: "Merriweather" style:normal weight:300 stretch:normal src index:2) source: https://fonts.gstatic.com/s/merriweather/v15/ZvcMqxEwPfh2qDWBPxn6nkZRWJQ0UjzR2Uv6RollX_g.woff2  css:26:12
downloadable font: rejected by sanitizer (font-family: "Merriweather" style:normal weight:300 stretch:normal src index:2) source: https://fonts.gstatic.com/s/merriweather/v15/ZvcMqxEwPfh2qDWBPxn6nkZRWJQ0UjzR2Uv6RollX_g.woff2
```

Side-by-side Chrome(left) vs Firefox Dev (right) on Mac OS:
![screen shot 2017-04-12 at 5 15 45 pm](https://cloud.githubusercontent.com/assets/7760/24977553/dcf2f66a-1fa3-11e7-8c16-7068f2b737a9.png)

Possible fix: Maybe add one extra fallback font before serif, since fixing Merriweather might be way out of the scope of this theme :)

**Comment by JohnONolan** [comment]
We absolutely don't support or optimise for browser beta or nightly builds, which by their definition have bugs and are prone to change. This seems like a bug in firefox which should be reported to firefox.
