### ISSUE TITLE
Feedback on Casper 2.0

### ISSUE THREAD

**Issue by PaszaVonPomiot** [TryGhost/Casper#318]
I really like the old Casper theme so at first I was sceptic about new design but then I think it's best if I just give you my thoughts on how to make 2.0 better. So here it goes in random order

### Subtitle is fine but title is missing
Title should be placed where ghost logo is now:
![image](https://user-images.githubusercontent.com/5560454/27504096-a2a72d5e-5884-11e7-88bd-6f1488967cb6.png)

### Add some left margin to navbar items
![image](https://user-images.githubusercontent.com/5560454/27504130-2649c0e0-5885-11e7-9e0f-c4c5cb0dd5b8.png)

### Move RSS icon to footer
![image](https://user-images.githubusercontent.com/5560454/27504138-49942db0-5885-11e7-956a-76179f8ca4d1.png)

### Add publication date to cards
Date could fit eg. below author.
![image](https://user-images.githubusercontent.com/5560454/27504151-7e85d8de-5885-11e7-8a84-15e5b0cb940a.png)
btw. Cards are really beautiful - well done

### Get rid of top bar appearing in the middle of post
Seriously this bar is a disaster as it completely ruins the style of Casper theme. My suggestion not to use any sliding bars and put social icons in static way somewhere where they won't look intrusive.
![image](https://user-images.githubusercontent.com/5560454/27504213-0a082a9c-5886-11e7-8781-4d4e2f42defa.png)
The old solution was perfect:
![image](https://user-images.githubusercontent.com/5560454/27507469-4836d8d2-58d0-11e7-8478-bf229ff6e372.png)

### Clicking on the tag like "getting started" should link to that tag related post list
![image](https://user-images.githubusercontent.com/5560454/27507505-fb186b64-58d0-11e7-8001-12ef902bfc47.png)

### Contrast of header and footer in posts
It appears that header and footer are black in posts and it strikes me as too contrasting. I wonder if there is a better solution

**Comment by JohnONolan** [comment]
Thanks for the feedback.
