### ISSUE TITLE
Image width follows content width

### ISSUE THREAD

**Issue by kennethlimcp** [TryGhost/Casper#320]
On `0.11.10`:

<img width="724" alt="screen shot 2017-06-26 at 20 20 20" src="https://user-images.githubusercontent.com/6760914/27538949-022b7990-5aad-11e7-9188-2b958c62ef57.png">

On `1.0.0-beta.2`:

<img width="1083" alt="screen shot 2017-06-26 at 20 20 02" src="https://user-images.githubusercontent.com/6760914/27538939-f6ab5edc-5aac-11e7-87cf-215b9397bbf0.png">

It will be nice to have the image displayed with correct dimensions that makes more sense for a blog.

**Comment by JohnONolan** [comment]
Good catch! Fixing
