### ISSUE TITLE
Infinite scroll gets confused by URL changes

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Casper#321]
Go to https://john.ghst.pro/ => scroll down, everything works as expected

Go to https://john.ghst.pro/# => scroll down, at a certain point the posts just start looping and repeating over and over again

Casper @ Ghost 1.0-beta2

**Comment by JohnONolan** [comment]
cc @AileenCGN

**Comment by kevinansfield** [comment]
The issue is that the `$.get` request here (https://github.com/TryGhost/Casper/blob/master/assets/js/infinitescroll.js#L23) results in a relative URL, so when you have a `/#` it tries to load `site.com/#/page/x` from the server which will always resolve to the homepage.
