### ISSUE TITLE
The table is beyond the maximum width

### ISSUE THREAD

**Issue by zhaoyibo** [TryGhost/Casper#328]
I use Ghost 1.0 RC, and casper version is 2.0.0

When I use the Markdown syntax in the post to write a table, if the contents of the table is too long, it will not wrap. Causing the table to overflow the page, like the following
![qq20170718-115110 2x](https://user-images.githubusercontent.com/11988080/28300235-ab884572-6bb0-11e7-9902-d14ffc7e3f8d.jpg)

I noticed that the table's `white-space` is `nowrap`. When I disable it, the table style is back to normal
![qq20170718-115229 2x](https://user-images.githubusercontent.com/11988080/28300239-b2e1c352-6bb0-11e7-88b4-69d29b248455.jpg)

**Comment by JohnONolan** [comment]
After looking at #322 I'm pretty sure you're running on Ghost 0.11/LTS -- Casper 2.0 is not compatible with LTS. If you want to use new Casper you'll need to be running on Ghost 1.0 -- compatibility is specified in package.json

Feel free to re-open if I'm wrong

**Comment by zhaoyibo** [comment]
I'm sure I'm running on Ghost 1.0
I am using the ghost-cli tool to install and refer to this document https://docs.ghost.org/docs/installing-ghost-via-the-cli

```
[root@instance-1 blog]# ghost version
Ghost-CLI version: 1.0.0-rc.3
Ghost Version (at ~/blog): 1.0.0-rc.1
```

![qq20170720-223159 2x](https://user-images.githubusercontent.com/11988080/28422653-47c42ff0-6d9b-11e7-8fb7-c1002127a4b8.jpg)

**Comment by JDevlieghere** [comment]
I'm running into the same issue with Ghost 1.1.0/Casper 2.0.1. The problem seems to be related to `white-space: nowrap;` in `.post-full-content table`.
