### ISSUE TITLE
Subscribe button missing on mobile

### ISSUE THREAD

**Issue by JBaczuk** [TryGhost/Casper#329]
In Labs, Subscribe feature adds a subscribe button on desktop, but is missing on mobile.

**Comment by AileenCGN** [comment]
@JBaczuk could you please provide some more information? I am not able to reproduce this. With subscriber mode switched on, I get the subscribe button in every blog post.

**Comment by JBaczuk** [comment]
I'm sorry I just realized I was not on the latest version of Ghost.  I will update and verify.

**Comment by JohnONolan** [comment]
It's definitely there :) http://demo.ghost.io/welcome/ 

On mobile it appears at the bottom of posts but not in the header navigation where there's limited space
