### ISSUE TITLE
Having no posts makes footer links in Author profiles not clickable.

### ISSUE THREAD

**Issue by Zelaf** [TryGhost/Casper#333]
Hello! I'm slowly setting up my Ghost blog and I noticed on the Casper theme that the links aren't clickable on the author page when the author has no posts.
![screen shot 2017-07-28 at 19 04 29-fullpage](https://user-images.githubusercontent.com/10819462/28728099-9e5a7734-73c7-11e7-9476-285f63bd2962.png)
The page when the links aren't hovered over.
![screen shot 2017-07-28 at 19 05 46-fullpage](https://user-images.githubusercontent.com/10819462/28728148-ce1cdee4-73c7-11e7-8fb1-4068a3c5b171.png)
Here I'm holding the mouse over the link which does highlight the text when the links are working on the homepage.

The screenshots where taken with the --fullpage option in Firefox's console, so the whole page is in the screenshot.

**Comment by acburdine** [comment]
I can verify this - a quick inspection in the Developer Tools shows that the main author page content block (the part with the author name and bio) extends a bit into the footer, and it also happens to have a higher z-index than the footer does, leading to the footer links being un-clickable.

I was able to fix it temporarily by applying a higher z-index to the footer, but there might be a better solution.

**Comment by Zelaf** [comment]
I deleted the Ghost user and now when there is no posts on the home page the footer links are not working there either.
