### ISSUE TITLE
Activated successful with warnings/errors!

### ISSUE THREAD

**Issue by arfianadam** [TryGhost/Casper#336]
My environment:
- mac
- `node@6.10.2`
- `ghost-cli@1.0.1`
- `ghost@1.1.0`

I created a new directory and ran `ghost install local` and it was up and running. I cloned this repo and zipped it so I can upload it on the local ghost server (I want to develop a custom theme). The upload was successful but then the problem occurs when I tried to activate it.

Here is the message:
```
Activated successful with warnings/errors!
archive activated successfully but some warnings/errors were detected. You are still able to use and
activate the theme. Here is your report...

Warnings

The output of {{id}} changed between Ghot LTS and 1.0.0, you may need to use {{comment_id}}
instead.

The output of {{id}} has changed between Ghost LTS and 1.0.0. {{id}} used to output an
incrementing integer ID, and will now output an ObjectID. We've added a new {{comment_id}} helper
that will output the old ID for posts that have been imported from LTS, and the new ID for new
posts. If you need the old ID to be output on imported posts, then you will need to use
{{comment_id}} rather than {{id}}.

Affected files:
post.hbs
```

The weird thing is, I tried to revert the change by activating the default theme and the warning popped up again with the exact same message. And the other weird thing, this doesn't happen in production (I have the exact same installation, `ghost` version, etc).

Anybody know the issue on why this only happen to development?

**Comment by ErisDS** [comment]
@arfianadam This is a warning only. It is telling you that the meaning of `{{id}}`, which is used in post.hbs changed and that you may wish to change it. In this case the usage is correct.

Development mode shows warnings, production mode will only show errors.

**Comment by arfianadam** [comment]
Ah I see, thank you for the heads up! @ErisDS
