### ISSUE TITLE
Site title/logo vertical alignment problem

### ISSUE THREAD

**Issue by arfianadam** [TryGhost/Casper#338]
My testing environment:
- Ghost 1.1.0 / Casper 2.0.1
- Mac
    - Chrome 59.0.3071.115 (desktop+mobile screen size)
- Android
    - Chrome 59.0.3071.125 (mobile screen size)

There is a vertical alignment problem for site title/logo when there are no nav items. Here's the screenshot:
![image](https://user-images.githubusercontent.com/10904377/28812931-4285d6d6-76c1-11e7-8b24-d8c451557f30.png)
I think it occurs because when the nav items are gone, the container doesn't have fixed height and the title/logo is smaller than the container, hence the title not aligning to the center because it doesn't have a point of reference. I'm making a PR for this.

**Comment by JohnONolan** [comment]
Hey! Thanks for reporting this. If you're going to file a bug report for a front end issue please include version numbers for Ghost/Casper, what browser, what OS, etc. No way to reproduce it otherwise :)

**Comment by arfianadam** [comment]
@JohnONolan you're welcome. Ah, sorry, I already updated the post. Thanks!

**Comment by arfianadam** [comment]
@JohnONolan have you checked it out?
