### ISSUE TITLE
Whole page blurry in Chrome 59 on Windows 10

### ISSUE THREAD

**Issue by mrkurt** [TryGhost/Casper#340]
I don't have an easy way to reproduce this since I don't own a Windows machine, but we've had a few users report blurry pages with Casper 2 on Chrome. This happens on both our blog (https://fly.io/articles/), and the Ghost blog.

Here's a screenshot one of them sent us:
![image](https://user-images.githubusercontent.com/7724/28853844-dda4df22-76f8-11e7-9df3-2161e8e90b09.png)

The discussion on Reddit doesn't have many more details, but they do confirm that it happens on the Ghost blog as well:

https://www.reddit.com/r/webdev/comments/6qypjn/how_to_version_a_web_api/dl1gfmp/

OS: Microsoft Windows 10 Home, Version: 10.0.14393 Build 14393
Browser: Google Chrome, Version: 59.0.3071.115

**Comment by ErisDS** [comment]
Hi @mrkurt, this issue is happening for users who have the "Experimental Web Platform Features" enabled in chrome://flags, and only happens on Windows 10. Essentially, it's a bug in an experimental chrome feature.

**Comment by Androbin** [comment]
@ErisDS I'm using Ubuntu 16, not Windows 10, and still have the issue.
