### ISSUE TITLE
Blockquote render change intended?

### ISSUE THREAD

**Issue by johnnyb2good** [TryGhost/Casper#343]
Hello,

The blockquote from Ghost 0.11.x seems to have had it's left vertical bar and styling dropped in Ghost 1.1.0 and Casper 2.0.  Is this intentional?  See following screenshots of the old vs. new rendering.  In the new rendering, the Markdown preview still shows a bar on the left, but the actual webpage render is missing the left vertical bar and has other font difference.

Ghost 0.11.x, Casper 1.3.6:

![image](https://user-images.githubusercontent.com/20143009/28901643-b743b7c0-77c7-11e7-9e8a-62ea70b8ff54.png)

![image](https://user-images.githubusercontent.com/20143009/28901526-bb193542-77c6-11e7-8d24-f735fa979b42.png)

Ghost 1.1.0 -- Casper 2.0.1:

![image](https://user-images.githubusercontent.com/20143009/28901679-f468ccb2-77c7-11e7-9d13-dc80c371ebd4.png)

![image](https://user-images.githubusercontent.com/20143009/28901700-0d5202fc-77c8-11e7-91a4-7143b2e59f00.png)

System Details:

Ghost Version: 1.1.0
Theme: Casper 2.0.1
Node Version: 6.11.1
Browser/OS: Chrome 59.0.3071.115, viewed on Windows 10, served from Ubuntu Linux 16.04
Database: MySQL 14.14

Thanks,

Johnny

**Comment by kevinansfield** [comment]
Hey @johnnyb2good 👋 Yes, this is the intended styling. If you have any further questions please swing by our [Slack channel](https://slack.ghost.org), we use GitHub solely for bug and feature development tracking whereas Slack is the right place for questions and support. Thanks!

**Comment by johnnyb2good** [comment]
Ok, will do -- thanks Kevin!
