### ISSUE TITLE
Card issue after upgrading to Casper 2.0.3

### ISSUE THREAD

**Issue by JDevlieghere** [TryGhost/Casper#349]
After upgrading to Ghost 1.5.2 and Casper 2.0.3 I noticed that the cards on my blog looked a little off. It looks like there is some kind of overlay, which makes the blog title greyed-out and  also prevents me from clicking on the post title. I tried to figure out what element was causing this with the Chrome's DevTools but without success. 

Returning to the previous version with `ghost update --rollback` resolved the issue. I am not injecting any custom CSS other than the snippet below. 

```
<style type="text/css">
	.post-full-content pre {
		background: #002b36;
		border: 1px solid #002b36;
	}
</style>
```

**After the upgrade:**
![after](http://i.imgur.com/qkPpkG7.png)

**Before (after the rollback):**
![before](http://i.imgur.com/NSorj8p.png)

Please let me know if there is any more info I can provide!

**Comment by ifvictr** [comment]
Can confirm. This is my Ghost running with Casper 2.0.3: ![2017-08-10_15-41-50](https://user-images.githubusercontent.com/10110245/29195282-8285a89c-7de2-11e7-8420-78c09bcb4b55.png)

**Comment by pascalandy** [comment]
Same here.

**Comment by corazza** [comment]
Same!
