### ISSUE TITLE
Site Header ::before ::after position

### ISSUE THREAD

**Issue by R4ver** [TryGhost/Casper#351]
I noticed after upgrading the theme together with ghost 1.5.2 that the black overlay on the front page cover, covers the top portion of the top post, like 10% or so.

The z-index of the content in site-header inner is also behind the black overlay.

Thought I'd let you guys know ;)

**Comment by vikaspotluri123** [comment]
Looks like a duplicate of #349

**Comment by R4ver** [comment]
Oh sorry about that! I'll close this one ;)
