### ISSUE TITLE
The footer section should snap at the bottom at any resolution

### ISSUE THREAD

**Issue by pascalandy** [TryGhost/Casper#354]
1) This screen shot was made on my imac 27''. IMHO the footer section should snap at the bottom of the window when there is not enough content to fill the page.

2) The content in the footer is not vertically centered.

<img width="1854" alt="screen shot 2017-08-11 at 10 46 20 pm" src="https://user-images.githubusercontent.com/6694151/29237184-f4566394-7ee6-11e7-96d4-cfb6eb9585b8.png">

### Technical details:

Ghost Version: 1.5.2 (via the official Docker hub image)
Environment production
Node Version: v6.11.2
Database: sqlite3
Mail SMTP
Browser/OS: Version 60.0.3112.90 (Official Build) (64-bit)
OSX 10.11.6

Many thanks!

P.S. I'll be glad to bring PR. I prefer the discuss first!

Cheers!
Pascal

**Comment by corazza** [comment]
I agree with you, but the title is confusing. Please edit 'shall' to 'should'

**Comment by JohnONolan** [comment]
Sticky footers are unreliable and generally cause more problems than they solve for the sake of an edge case. Not interested in tracking this - but if anyone has a particularly ingenious solution then feel free to suggest via PR.

**Comment by pascalandy** [comment]
Make sense. Thank you!

**Comment by lightningboss** [comment]
I believe that sticky footers are solved with flexbox. Take a look here: https://philipwalton.github.io/solved-by-flexbox/demos/sticky-footer/

**Comment by JohnONolan** [comment]
@lightningboss that's actually a really nice technique :) thanks!
