### ISSUE TITLE
Quote are too wide

### ISSUE THREAD

**Issue by pascalandy** [TryGhost/Casper#355]
<img width="1203" alt="screen shot 2017-08-12 at 11 44 32 am" src="https://user-images.githubusercontent.com/6694151/29242048-bd9fd930-7f53-11e7-8812-48709fe405ee.png">

### Technical details:

Ghost Version: 1.5.2 (via the official Docker hub image)
Environment production
Node Version: v6.11.2
Database: sqlite3
Mail SMTP
Browser/OS: Version 60.0.3112.90 (Official Build) (64-bit)
OSX 10.11.6

**Comment by ErisDS** [comment]
@pascalandy Can you please provide enough information for a reproduction? That is the markdown you used to generate the HTML, your Browser + OS name and version.

**Comment by pascalandy** [comment]
Sure and sorry for this! It's done :)

**Comment by kevinansfield** [comment]
@pascalandy this still seems to be missing a reproduction case. Can you please provide the markdown used or the specific post setup which others can use to see the issue you're trying to demonstrate?

**Comment by pascalandy** [comment]
You mean this ?

```
> Happy clients are everything to us. Without you guys we would be living on the street (or in our Mom's basement). Thank you so much for trusting us over all those years.
```

 I can reproduce on casper 2.0.2 and 2.0.3. Thank you!
