### ISSUE TITLE
Mouseover latest blog post

### ISSUE THREAD

**Issue by foorb** [TryGhost/Casper#359]
Hi, 
i hope I am right here. Is the following behaviour correct? The publication cover seems to be overlaying the blog post.

### Screenshot

![kapture 2017-08-14 at 23 38 14](https://user-images.githubusercontent.com/14993807/29293065-d81745c6-8149-11e7-9b69-854379469401.gif)

### Steps to Reproduce
 
Fresh installation of ghost with casper without any modifications.
`docker run -d --name some-ghost -p 2368:2368 ghost:latest`

### Technical details

* Casper Version: 2.0.3
* Ghost Version: 1.5.2
* Browser Version: 60.0.3112.90
* OS Version: macOS 10.12.6

**Comment by vikaspotluri123** [comment]
Duplicate of #349 - will be fixed in the next release

**Comment by foorb** [comment]
Amazing fast reaction. Thank you!!
