### ISSUE TITLE
[Navbar] No logo but blog title does not position correctly

### ISSUE THREAD

**Issue by lightningboss** [TryGhost/Casper#361]
### Screenshot

<img width="311" alt="screen shot 2017-08-15 at 22 55 17" src="https://user-images.githubusercontent.com/11751444/29336045-e658c0ec-820c-11e7-9160-e64c8428d66a.png">

### Steps to Reproduce
 
 1. Create a new page and remove the publication logo and nav links
2. Go to a blog post

### Technical details

* Casper Version: 2.0.2
* Ghost Version: 1.5.1
* Browser Version: Chrome Version 60.0.3112.90
* OS Version: macOS 10.12.6

**Comment by JohnONolan** [comment]
Please update to the latest version of Casper https://github.com/TryGhost/Casper/releases

This was fixed in 2.0.3
