### ISSUE TITLE
Issue with title font color

### ISSUE THREAD

**Issue by hsand** [TryGhost/Casper#363]
Somewhere between 2.0.2 and 2.0.3 there was a change to the site's title font color. I don't see a corresponding commit, and the color does not match the CSS .site-title "color: #fff" parameter, which makes me think it could be a bug.

Here you can see before and after on my site.

Before change:
![old](https://user-images.githubusercontent.com/14326961/29382199-2a0c9434-82cc-11e7-965b-0d64bb197310.PNG)

After change:
![new](https://user-images.githubusercontent.com/14326961/29382227-36fce662-82cc-11e7-9b54-2be961e0a2ae.PNG)

**Comment by hsand** [comment]
It was the removal of:

.site-header-content {
    position: relative;		
    z-index: 300;
....

You can see the diff here: https://github.com/TryGhost/Casper/compare/2.0.2...master#diff-ce5e030f2e2e2a50f18199464f07ea70L137

**Comment by kevinansfield** [comment]
Hi @hsand, can you please upgrade to the latest 2.0.4 release and report back if you are still seeing the same issue? Thank you.

**Comment by hsand** [comment]
I can confirm the issue is present in the 2.0.4 release as well. 

You can also see the issue on the ghost demo site, demo.ghost.io. The ghost logo (http://demo.ghost.io/content/images/2014/09/Ghost-Transparent-for-DARK-BG.png) is completely white, though is covered by a transparent grey element. Adding back the CSS I mentioned above fixes the issue.
