### ISSUE TITLE
Rendering of longish blockquotes

### ISSUE THREAD

**Issue by metawops** [TryGhost/Casper#364]
Do you need help or have a question? Please come chat in Slack: https://ghost.org/slack 👫.

If you're filing a bug 🐛, please include the following information:

### Screenshot

![ghost-casper-blockquote](https://user-images.githubusercontent.com/376090/29384005-ce5ce380-82d2-11e7-9b94-8f39ae4a42e4.png)

### Steps to Reproduce
 
1. In the Ghost 1.x editor, in an article, enter a blockquote (`> Quote Text`).
2. See the nice rendering in the left part of the above screenshot – that's the live preview during editing.
3. See the no-so-nice rendering of a longish blockquote by the Casper 2.0.4 theme in the right part of the screenshot.

### Technical details

* Casper Version: 2.0.4
* Ghost Version: 1.6.0
* Browser Version: Safari 10.1.2
* OS Version: macOS 10.12.6

**Comment by crepererum** [comment]
IMHO the quote looks like an oversized link.
