### ISSUE TITLE
Change Title (site name) but pages still display "ghost" as title

### ISSUE THREAD

**Issue by eendii** [TryGhost/Casper#366]
Do you need help or have a question? Please come chat in Slack: https://ghost.org/slack 👫.

If you're filing a bug 🐛, please include the following information:

### Screenshot

![ss](https://user-images.githubusercontent.com/18214839/29422135-72533222-83a1-11e7-98fd-235789ad6c43.jpg)

### Steps to Reproduce

 1. From the admin page, go to "Settings: General"
 2. Leave everything default, edit Title & Description and Save
 3. Then when I go to "home" page and do refresh, the title still display "ghost", not the new title. Same thing as the top black bar at the top, still display "ghost". But initially while the page was loading, it displayed the new title ... but then after the page completely (or halfway) loaded, the new title was replaced (switched back) to "ghost".

### Technical details

* Casper Version: 2.0.4
* Ghost Version: 1.6.1
* Browser Version: Firefox 54.0.1
* OS Version: Windows 10

**Comment by kevinansfield** [comment]
@eendii this isn't a bug, if you want to use the site title instead of the logo you need to first remove the logo (or you can replace it with your own logo)

![screen shot 2017-08-17 at 17 36 54](https://user-images.githubusercontent.com/415/29423228-ddb4bd1c-8372-11e7-97ed-f0f1e953445c.png)
