### ISSUE TITLE
Social sharing icons don't appear in Safari on macOS

### ISSUE THREAD

**Issue by kostyakoz** [TryGhost/Casper#367]
### Screenshot

In Safari:
![safari](https://user-images.githubusercontent.com/1935229/29473170-67165934-845f-11e7-9f57-ffac361e7d54.png)

Same blog view in Chrome looks fine.
![chrome](https://user-images.githubusercontent.com/1935229/29473171-671a2b0e-845f-11e7-9e5e-82d5cdd1077b.png)

### Steps to Reproduce
 
 1. This is in default Casper theme.

### Technical details

* Casper Version: 2.0.5
* Ghost Version: 1.6.2
* Browser Version: Safari 10.1.2
* OS Version: macOS 10.12.6

**Comment by JohnONolan** [comment]
Can't reproduce this - pls try updating to the latest versions of Ghost/Casper and feel free to re-open if you still have problems
