### ISSUE TITLE
<ul> lists don't shows properly on iPhone 7 (Safari)

### ISSUE THREAD

**Issue by kostyakoz** [TryGhost/Casper#368]
### Screenshot

On iPhone 7.
![img_0059](https://user-images.githubusercontent.com/1935229/29473517-c1722092-8460-11e7-85b2-045f54019d75.PNG)

On macOS everything looks fine.
![screen shot 2017-08-18 at 9 56 46 pm](https://user-images.githubusercontent.com/1935229/29473576-fe1e612c-8460-11e7-93b0-a09a0ab043da.png)

### Steps to Reproduce
 
 1. Just default theme on iPhone 7 Safari. `<ul>` tag in post (or `*` in Markdown). Looks fine on macOS.

### Technical details

* Casper Version: 2.0.5
* Ghost Version: 1.6.2
* Browser Version: Safari on iPhone 7
* OS Version: iOS 10.3.3

**Comment by a1p4ca** [comment]
I have the save problem on Chrome and Safari.
![Different between firefox and chrome](https://user-images.githubusercontent.com/13712304/29490825-318e5fda-8583-11e7-814b-597fc2b31851.png)
But Firefox works very well. I'm working on this issue too. So if I fix this, I'll pull request.
