### ISSUE TITLE
Place to go back for footnotes is covered by header

### ISSUE THREAD

**Issue by lightningboss** [TryGhost/Casper#369]
### Screenshot

<img width="361" alt="screen shot 2017-08-19 at 00 42 27" src="https://user-images.githubusercontent.com/11751444/29480261-5125a810-8477-11e7-86b0-69b5168633ad.png">

### Steps to Reproduce
 
 1. Create a footnote and a long article
 2. Click on the return-symbol
3. The text you want to go back to is not really visible through the header

### Technical details

* Casper Version: 2.0.5
* Ghost Version: 1.5.1
* Browser Version: Chrome Version 60.0.3112.90
* OS Version: macOS 10.12.6

**Comment by JohnONolan** [comment]
This is an edge case without a clear solution that doesn't involve a lot of heavy handed JS - so it's probably not something we're going to optimise for by default - but if this is critical to you, then you could definitely inject an additional script via code injection to handle this for you if you wanted :)
