### ISSUE TITLE
Compatibility issues in IE 11 and bellow

### ISSUE THREAD

**Issue by fedefu** [TryGhost/Casper#371]
The homepage works perfect, but not the articles. 

### Screenshot

[![]()
](url
![image001](https://user-images.githubusercontent.com/31281197/29618766-77cfe5f2-8819-11e7-942c-01ab6abd24f2.png)
)
### Steps to Reproduce
 
 1. This is the first step
Open any article like this http://demo.ghost.io/welcome/ in internet explorer

 2. This may be the post content used to cause an issue...

### Technical details

* Casper Version: 1.0
* Ghost Version: 1.0
* Browser Version: Internet explorer
* OS Version:

**Comment by JohnONolan** [comment]
Please update to the latest versions of Ghost and Casper and feel free to report again if you still have issues
