### ISSUE TITLE
Syntaxic coloration

### ISSUE THREAD

**Issue by rgarrigue** [TryGhost/Casper#372]
Hello

I'm using ghost 1.6.1 from docker. I used zutriken/bleak template before. Since 1.0 release I'm pretty fine with Casper since you added the post mosaïc. But I'm still missing syntaxic coloration.

Writing this I'ld expect some colors

```
```python
# -*- coding: ISO-8859-1 -*-

"""
Requirements
    pip install wmi win32core
"""

import wmi
c = wmi.WMI()

# Process list

for process in c.Win32_Process ():
  print(process.ProcessId, process.Name)
``` 

But there's none : https://blog.garrigue.re/python-on-windows/

Since I use ghost as a notebook for my ops stuff, that's a serious cosmetic issue for me.

Best regards,

**Comment by kevinansfield** [comment]
@rgarrigue syntax highlighting is not something that will be built in to the default theme, not all users will need it and themes etc and the required features of different syntax highlighters will differ between use cases.

It's easy enough to add syntax highlighting independent of a theme in a way that will work no matter which theme you're using. For a quick tutorial of using prism.js I have a [blog post here](https://lookingsideways.co.uk/super-simple-code-highlighting-for-ghost/) but a similar approach can be used for other highlighters, a quick google search should return a number of results showing how it can be done.

**Comment by corazza** [comment]
The [article](https://lookingsideways.co.uk/super-simple-code-highlighting-for-ghost/) by @kevinansfield is helpful, but for those looking to add support for languages not included by the default script or different themes, use these lines:

- CSS in header for a different theme (replacing the one from the article): `<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/prism/1.6.0/themes/prism-okaidia.css">`
- scripts for other languages (in addition to the main `prism.min.js` script): `<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.6.0/components/prism-java.min.js"></script>`

**Comment by rgarrigue** [comment]
Thanks guys, that's ok for me. Just for the records, default prism include "javascript python ruby powershell bash batch c latex".
