### ISSUE TITLE
Anchors copy shortcut

### ISSUE THREAD

**Issue by rgarrigue** [TryGhost/Casper#373]
Hello

I just discovered that I can add anchors to my URL to directly point someone to a chapter, like https://blog.garrigue.re/python-on-windows/#wmi

I wish there was a shortcut icon displaying on title mouse over to open & copy the anchor.

Edit : ansible doc is a perfect example : http://docs.ansible.com/ansible/latest/docker_container_module.html#docker-container

![image](https://user-images.githubusercontent.com/1872031/29656627-480f79a8-88b5-11e7-8074-0486ab80230c.png)

Regards,

**Comment by corazza** [comment]
I thought about this as well. It would be great if, on mouse-over, one of those little inverse "P"s or whatever appeared to the left of the subtitle, which was a link to `#subtitle`, and on mouse-out it disappears.

**Comment by JohnONolan** [comment]
This is great for technical documentation but largely a non-existent use case for other forms of creative writing and publishing -- so it's not something we would add by default, but it's definitely something you could implement easily for your particular site, either with a theme mod or by using the code injection feature :)

**Comment by corazza** [comment]
Anyone mind creating a code injection snippet for this feature and publish it as a gist or smth?
