### ISSUE TITLE
Progress bar styling breaks on OS-X Chrome

### ISSUE THREAD

**Issue by Leoooob** [TryGhost/Casper#378]
### Screenshot

![Screenshot of dodgy styling](https://i.gyazo.com/a2431723b083304013edf2b6b3153ba8.png)

### Steps to Reproduce
 
All of the posts on my [install](https://blog.leonhassan.co.uk) have this issue on Mac, using Chrome. It's also got similar broken styling when viewing in Safari.

I couldn't reproduce the issue using the live casper site, because progress bars are not in-use there. I'm therefore not entirely sure if this is a localised issue, or an issue with the actual theme.

### Technical details

* Casper Version: 2.1.0 (my own branch)
* Ghost Version: Ghost 1.8.1
* Browser Version: 60.0.3112.90 (Official Build) (64-bit)
* OS Version: Sierra 10.12.2

**Comment by kevinansfield** [comment]
@Leoooob this sounds like a localised issue, I can't reproduce it locally at all here. https://blog.ghost.org uses slightly modified Casper too and there's no issue there.

It's odd that you see the issue in both Safari and Chrome

**Comment by compulsions** [comment]
I also got the same issue while editing the theme even if I didn't edit the progress bar itself, can't properly say how it happened though

**Comment by JohnONolan** [comment]
Can't reproduce here either. Feel free to re-open if anyone comes up with a reproducible test case
