### ISSUE TITLE
Post without tags creates GQL error

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Casper#382]
Steps to reproduce:
1. Create a new post without any tags
2. Publish the post
3. Navigate to the post in the frontend
4. See the error in the server logs

I guess this line need's a check whether the primary tag exists: https://github.com/TryGhost/Casper/blob/master/post.hbs#L105

```
Error: Query Error: unexpected character in filter at char 1
tags:+id:-59ae9780c14d732
-----^
Expecting 'NOT', 'LBRACKET', 'NULL', 'TRUE', 'FALSE', 'NUMBER', 'LITERAL', 'STRING', 'GT', 'LT', 'GTE', 'LTE', got 'AND'
    at Object.parser.parseError (/Users/kirrg001/Downloads/Ghost-1.8.2/node_modules/ghost-gql/dist/parser.js:324:12)
    at Object.parse (/Users/kirrg001/Downloads/Ghost-1.8.2/node_modules/ghost-gql/dist/parser.js:240:22)
```

The error is no critical error in my opinion, because it simply doesn't show prev/next posts.

* Casper Version: master
* Ghost Version: master (+1.8.1)
* Browser Version:
* OS Version:

**Comment by ErisDS** [comment]
Yar, it needs to be wrapped in an `{{#if primary_tag}}{{/if}}`  This is not a new error pretty sure this will have been around for a while.
