### ISSUE TITLE
The floating header hides anchor-linked content

### ISSUE THREAD

**Issue by PunKeel** [TryGhost/Casper#385]
### Video

[YouTube video](https://www.youtube.com/watch?v=IElpwOA6JNU)
_Be warned, everything happens so quickly!_

### Steps to Reproduce
 
 1. Write a (long) blog post with footnotes `[^1]`, or add titles & link to them using anchors `[Title](#idwithoutspecialchars)`
 2. Click on the footnote o/

[Sample page to reproduce](https://ungeek.fr/p/98050ac9-0be0-46bd-9d14-41c08aabec32/#fnref2)

### Technical details

* Casper Version: 2.1.2
* Ghost Version: 1.8.6
* Browser Version: Chrome 59, Safari
* OS Version: macOS Sierra 10.12.6 (16G29)

**Comment by kevinansfield** [comment]
@PunKeel the only way to work around that is to use JS. If you have a site that relies on anchor links you may want to install something like the [smooth-scroll](https://github.com/cferdinandi/smooth-scroll) plugin where it's possible to set an `offset` height for the scroll position.
