### ISSUE TITLE
How is the number of cards on a row determined?

### ISSUE THREAD

**Issue by YOnoda** [TryGhost/Casper#387]
It seems that the number of cards on a row in a main blog page is not consistent. In some rows there are three cards, but in other rows one big card conquers the total space.

This phenomenon is also seen on the official ghost blog, which uses a theme specifically built for the blog but the is based on top of the Casper, I believe.

<img width="480" alt="2017-09-20 07 33 08" src="https://user-images.githubusercontent.com/4002991/30632136-8f7b3792-9dd6-11e7-8de0-da91eec329fb.png">

In `screen.css` there is the following description at *6. Post Feed*, but I found that sometimes one card takes all the space on a row even in the middle of the page (i.e. it is not the most recent post):

> The first (most recent) post in the list is styled to be bigger than the others and take over the full width of the grid to give it more emphasis. Wrapped in a media query to make sure this only happens on large viewports / desktop-ish devices.

Am I missing something?

**Comment by kevinansfield** [comment]
The most recent post sizing will only work when the most recent post has a feature image. If the use of feature images is inconsistent then the sizing of posts will also be inconsistent.
