### ISSUE TITLE
Images and other elements cannot be floated any more

### ISSUE THREAD

**Issue by Bilge** [TryGhost/Casper#388]
Floating elements such as images and tables right was possible in pre-1.0 Ghost releases of Casper, but for some reason it no longer has any effect: images remain center-aligned no matter what. I cannot figure out how to right-align images any more.

### Steps to Reproduce
 
 1. Add image
 2. Apply style: `float: right`

### Technical details

* Casper Version: 2.1.2-3-gf5b7b45
* Ghost Version: 1.8.6
* Browser Version: Firefox 55.0.3
* OS Version: Windows 7

**Comment by kevinansfield** [comment]
Hi @Bilge, unfortunately there's not much we can do with this issue as you haven't explained where or how you are trying to apply the `float: right` style, it's also unlikely that a simple style like that will work.

This isn't a bug in Casper, if you need help styling your theme please swing by the #themes channel in our [Slack community](https://slack.ghost.org)

**Comment by Bilge** [comment]
If you wanted me to explain where and how I am applying the style, why not ask me instead of closing the issue like you just don't care? Moreover, your Slack "community" appears to be closed off to open source contributors, reserved only for paying customers.

**Comment by kevinansfield** [comment]
The issue was closed because your issue was not a bug but a help request. We use GitHub solely for bug tracking and on-going feature work.

The [Slack community](https://slack.ghost.org) is free and open to everyone, I'm not sure where you are getting the idea that it's reserved for paying customers.

**Comment by Bilge** [comment]
Whether or not it's a bug is a matter of perspective. If you do not support floating I suppose it is not a bug. But from my perspective, this is something that used to work in Casper but now suddenly does not. For me, this is a BC-breaking change that breaks the layout of all my articles.

**Comment by kevinansfield** [comment]
It may have worked in Casper 1.x, it sounds like you've switched themes to Casper 2.x (the major version number signifies breaking changes under [semver](http://semver.org)) which is a completely new theme, you can't expect custom CSS styles you've applied in one theme to always work in another.

You can install [Casper 1.4](https://github.com/TryGhost/Casper/releases/tag/1.4.0) if you want to keep full backwards compatibility with your custom styles - it's the old 1.x Casper that's compatible with Ghost 1.x.

Please don't re-open the issue, this is _not_ a bug and won't be dealt with here on GitHub. I've given you links to our Slack community where you can get community help with themes and styling.

**Comment by juhi24** [comment]
I'd also like to know how to add floating images on posts. I tried to ask around on slack about this, but no-one seemed to care. If anyone knows a solution, please comment.

**Comment by mary-dean** [comment]
I have had no trouble floating images right or left within a post. I just tested it, and this works for me: 
```&lt;img src=&quot;/content/images/2018/03/apple.png&quot; alt=&quot;&quot; style=&quot;float:right&quot;&gt;```

**Comment by slava-vishnyakov** [comment]
Add an empty `<div>` wrapper in html:

    <div>
        <img src="/content/images/2019/05/image-4.png" style="float: left; margin-right: 20px;"> 
        text text
    </div>

The outside div (`class="post-content"`) has a `display: flex`, so floats don't work inside.

**Comment by mschmid** [comment]
@slava-vishnyakov you just saved me from starting creating a table layout, thank you for the explanation.
