### ISSUE TITLE
Only one tag is displayed in articles and on post cards

### ISSUE THREAD

**Issue by Bilge** [TryGhost/Casper#389]
Nowhere within Casper is it possible to see more than one tag for an article. Perhaps this is intentional for post cards, but somewhere in the article itself it should be possible to see the complete list of tags. Currently posts are limited to exactly one tag per article, of which only the first is shown.

### Steps to Reproduce
 
 1. Create article with multiple tags.
 2. View article.

### Technical details

* Casper Version: 2.1.2
* Ghost Version: 1.8.6
* Browser Version: Firefox 55.0.3
* OS Version: Windows 7

**Comment by kevinansfield** [comment]
Hi @Bilge. That's intentional, Casper is designed for a single tag per post.

You're free to modify Casper to your liking in order to better fit your site structure.

**Comment by Bilge** [comment]
That doesn't make sense because Ghost has always supported multiple tags
and Casper is the default first-party theme for Ghost. It should be invalid
to only support the first tag in the UI because that's fundamentally
incompatible with Ghost itself.
