### ISSUE TITLE
Feature: sub-content linking for headings

### ISSUE THREAD

**Issue by Bilge** [TryGhost/Casper#390]
Headings have always had unique IDs, but one has to source-dive to find it, thus making sub-content linking difficult. Many sites show a paragraph marker (¶) next to headings on mouse-over, which when clicked, creates a link to that heading. The specific implementation is left to your discretion, but linking to specific parts of a document is an important feature.

**Comment by vikaspotluri123** [comment]
Looks like a duplicate of #373

**Comment by kevinansfield** [comment]
Closing as a duplicate of #373
