### ISSUE TITLE
Missing multiple tag support

### ISSUE THREAD

**Issue by Bilge** [TryGhost/Casper#391]
Ghost supports, and always has supported, multiple tags. Casper used to support multiple tags, too, but since circa v2 only supports a single tag. The mismatch of feature support between Ghost and Casper creates a number of **usability issues** through behavioural inconsistencies.

Since Casper only displays the first tag this creates a faux notion of a *"primary"* tag, to which all other tags can be considered *secondary*. All secondary tags are invisible to Casper. This causes confusion for users whom expect their tags to be visible on the front-end.

Since Casper ascribes the first tag as the primary, it is autonomously creating semantic meaning for tag order despite the fact that tag order is irrelevant to Ghost itself and in most other popular tagging systems found on the Web today.

* If a tag exists as a primary on some articles but a secondary on others, viewing the tag's page (e.g. `/tag/foo/`) will appear to list articles that don't have the `foo` tag (of course, they do, you just can't see it because `foo` is not the primary tag for those articles).

* If a tag is exclusively used as a secondary tag, it is completely undiscoverable by simply following links within the UI. Such tags can only be reached by typing the tag name directly into the URL.

These behavioural inconsistencies betray user expectations and make Ghost appear to have bugs it does not. Whether this is a bug in Casper or Ghost depends on what the intended behaviour should be. I recommend either:

1. Casper is updated to support mutiple tags per post.
2. Ghost is downgraded and syncronised with Casper to support only one tag per post.

My personal preference is strongly for the first option.

To be clear, it would be fine for any other theme to redefine, neglect or otherwise break Ghost features, but since Casper is the flagship default theme for Ghost, I believe **Casper absolutely must have feature parity with Ghost**.

cc @JohnONolan @ErisDS 

---

:warning: #389 was closed prematurely. Please do not close this issue until resolved!

### Steps to Reproduce
 
 1. Create article with multiple tags.
 2. View article.

### Technical details

* Casper Version: 2.1.2
* Ghost Version: 1.8.6
* Browser Version: Firefox 55.0.3
* OS Version: Windows 7

**Comment by corazza** [comment]
I think you're approaching the issue wrong. First, I think the primary tag feature was introduced to *Ghost itself*, and Casper merely utilizes it in the way it does. So, no, your proposed solutions aren't the only ones: neither does Casper have to behave like it did, nor does Ghost have to remove multiple tags.

# The practical issue of secondary tags being completely lost from the UI

This is simply not  true. You are still able to link to secondary tags wherever you want. For example, I utilize this by having my primary tags be the most concrete and relevant to the post (the name of the series that the post belongs to, for example), and then adding the more general, "category-like" secondary tags to the navigation menu.

So when the user for example clicks "Projects" in my navigation bar, the `/tag/project` page is loaded, but the primary tags that are displayed on the card are always something more specific--this makes perfect sense! The user doesn't even know that `project`  is a tag, unless they examine the URL, they merely see a collection of many posts, tagged with semantically-rich names of the individual projects that the posts relate to!

# The general issue of secondary tags losing prominence in Casper

However, I do agree with the sentiment that something should change: namely, secondary tags should appear *at least somewhere on the post's page.* Showing a single tag in the post's card in Casper makes sense, that's what gives meaning to primary tags in the first place, and it's less confusing. However, there is no reason not to have an *"also tagged as: ..."* snippet at the bottom of the actual page. As you claim, and I agree, it really would improve navigating the blog.

**Comment by Bilge** [comment]
> I think the primary tag feature was introduced to Ghost itself

Do you have a single source to back that up? It seems to me the concept of a *primary tag* is *purely virtual* and manifest itself only in the Casper front-end by the way it behaves. Furthermore, there is no mention of having to re-order your tags to place an emphasis on the new primary/secondary dichotomy in the [migration guide](https://docs.ghost.org/docs/migrating-to-ghost-1-0-0), which there definitely should be if that change was intentional.

**Comment by kevinansfield** [comment]
@Bilge primary tags are most definitely a first-class citizen in Ghost https://dev.ghost.org/primary-tags/

**Comment by Bilge** [comment]
@kevinansfield Thanks, I certainly cannot refute that fact, although that information might be easier to find in the documentation than in a blog. Nevertheless, my points still stands that:

1. Exclusively secondary tags (that never appear in the primary position) are undiscoverable by readers and search engines.
2. There is nowhere to see secondary tags from within Casper.
3. The Ghost admin view disagrees with the Casper client view of the tag list for posts and articles.
4. The concept of a primary tag is known only to developers and is an unexpected behaviour for typical users.

**Comment by JohnONolan** [comment]
> that information might be easier to find in the documentation than in a blog

http://themes.ghost.org/docs/primary_tag

You mean like right here? In the documentation that you didn't bother to read before opening an aggressive entitled issue claiming that no concept of primary tag exists, because you didn't research it at all?

> ⚠️ #389 was closed prematurely. Please do not close this issue until resolved!

This issue is now closed. Further to your multiple other warnings - most recently in https://github.com/TryGhost/knex-migrator/issues/73 - If you open more nuisance issues, you will be permanently banned. Your attitude and your tone are not acceptable and will not be tolerated.

Ghost is open source, if you have strong views about it working a particular way - then fork it and make it work that way.
