### ISSUE TITLE
How to change the fucking favicon ?

### ISSUE THREAD

**Issue by ky0ncheng** [TryGhost/Casper#392]
Do you need help or have a question? Please come chat in Slack: https://ghost.org/slack 👫.

If you're filing a bug 🐛, please include the following information:

### Screenshot

![]()

### Steps to Reproduce
 
 1. This is the first step
 2. This may be the post content used to cause an issue...

### Technical details

* Casper Version:
* Ghost Version:
* Browser Version:
* OS Version:

NOTHING METHOD IN DOCS.
https://help.ghost.org/hc/en-us/articles/223207167-Blog-Settings-Overview

**Comment by ky0ncheng** [comment]
FUCK

**Comment by ky0ncheng** [comment]
I found this setting in ghost source code, why not writed in theme code?

**Comment by corazza** [comment]
this is hilarious don't delete it lmao
