### ISSUE TITLE
Feature: Lazy loading the images/assets

### ISSUE THREAD

**Issue by pankajpatel** [TryGhost/Casper#396]
# Feature: Lazy Load

The featured image and other images are the key part of the blog and it post. I tried to check the Page Insights score for my blog, and I found out that most of the recommended optimizations were for for images. 

One of Other optimizations was for `ghost-sdk.min.js`

## Suggestions:
- [ ] Lazy load for images
- [ ] Increase Cache duration for Images from Unsplash, as they will rarely change
- [ ] delivery of `ghost-sdk.min.js` from CDN. As for a Ghost setup, Casper will be same (if not customized) and if it is customized, developers will be aware of the CDN delivery and can disable it if they want. Normal users are anyway editing some file to include `disqus`
![developers google com-speed-pagespeed-insights-time2hack com](https://user-images.githubusercontent.com/251937/31098789-258344ae-a7c4-11e7-9cc7-a60bbbb56c34.png)

**Comment by kevinansfield** [comment]
Hey @pankajpatel 👋 It looks like you've opened this issue in the wrong repo? These reports are things specific to your blog and hosting, they can't be solved by changes in Casper.

> delivery of ghost-sdk.min.js from CDN. As for a Ghost setup, Casper will be same (if not customized) and if it is customized, developers will be aware of the CDN delivery and can disable it if they want.

This is a generated file that's unique for each blog, serving a single instance from one CDN isn't a viable option for Ghost as it's a distributed platform. We're aware it's not optimal, there's an issue tracking it in Ghost itself https://github.com/TryGhost/Ghost/issues/7299

**Comment by pankajpatel** [comment]
Thanks @kevinansfield
