### ISSUE TITLE
Images inside of parent elements increase parent element width

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Casper#402]
### Screenshot

<img width="1115" alt="screen shot 2017-10-16 at 16 09 33" src="https://user-images.githubusercontent.com/415/31619449-72c76e0c-b28c-11e7-8e64-d177d14e2b69.png">

### Steps to Reproduce
 
1. Add an image to markdown without a blank line above it so that it's part of the container element, eg:
    ```markdown
    * Ghost is designed for ambitious, professional publishers who want to actively build a business around their content. That's who it works best for. If you're using Ghost for some other purpose, that's fine too - but it might not be the best choice for you.
    ![](https://images.unsplash.com/photo-1508108712903-49b7ef9b1df8?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&s=ef5b702734890c24b01d605d5b41eceb)
    ```

2. View the blog post at large screen widths - the element containing the image will be forced to fill the same width as the image. This is not an issue at smaller screen widths where images are constrained to their container width.

### Technical details

* Casper Version: 2.1.4
* Ghost Version: 1.14.0
* Browser Version: Chrome 61
* OS Version: macOS

**Comment by JohnONolan** [comment]
> The easiest workaround is to ensure your images or videos are separated by newlines 

Yep - that's the only way for now
