### ISSUE TITLE
Performance: Don't animate box-shadow directly

### ISSUE THREAD

**Issue by lightningboss** [TryGhost/Casper#405]
Casper is animating the box-shadow on hover at the front page with all the post-cards.
Animating box-shadow causes repaints (open chrome devtools and open tab "rendering").

This can easily be avoided by animating its pseudo element. Check this blogpost for a description: http://tobiasahlin.com/blog/how-to-animate-box-shadow/

I don't think that this is absolutely necessary, but it would be a good enhancement.

**Comment by thomasvaeth** [comment]
So I had code already for animating box-shadow, so I did it quick. https://github.com/samesies/Casper/tree/box-shadow

The downside is have to put z-index: -1 on the pseudo element, which causes the image to perform strangely on hover on Chrome (white lines go across it). 

A solution would be rebuilding the card to make the whole thing a link inside the article, put the box shadow on the link, and then add JS for clicking on the author. Doing all of that kind of negates the little painting improvement.
