### ISSUE TITLE
Links in code blocks are in dark grey on a black background

### ISSUE THREAD

**Issue by olivierlambert** [TryGhost/Casper#407]
This make those links almost invisible. I'm missing something?

---

### Screenshot

![ghost1](https://user-images.githubusercontent.com/1241401/32556573-1a7594ba-c4a0-11e7-8882-407a5f0d106c.png)

URL live here: https://xen-orchestra.com/blog/docker-support-in-xenserver-the-ultimate-guide/

### Steps to Reproduce
 
 1. latest ghost release
 2. using code blocks AND urls (colored in dark grey)

But visible while hovering:

![ghost2](https://user-images.githubusercontent.com/1241401/32556623-379a82da-c4a0-11e7-9fa6-217c9cdfc5b7.png)

### Technical details

* Casper Version: latest
* Ghost Version: latest
* Browser Version: latest FF and Chrome
* OS Version: Fedora latest

**Comment by kevinansfield** [comment]
@olivierlambert you're not missing anything, looks like you've found a genuine bug, thanks for reporting!

**Comment by frazjp65** [comment]
It is not limited to anchor tags. The same issue can be replicated using "em", "strong", and "h1" tags. I assume there are others too. 

I created a PR (#408) to fix the issue for all descendant elements.
