### ISSUE TITLE
Replace Fitvids/jQuery with Reframe/Noframe

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Casper#409]
Anyone welcome to take this, if not I'll look at it later. 

https://github.com/dollarshaveclub/reframe.js

**Comment by pankajpatel** [comment]
Good idea! FitVids picks up all the videos in the container with
```
var selectors = [
        'iframe[src*="player.vimeo.com"]',
        'iframe[src*="youtube.com"]',
        'iframe[src*="youtube-nocookie.com"]',
        'iframe[src*="kickstarter.com"][src*="video.html"]',
        'object',
        'embed'
];
```
where as reframe/noframe will need individual selectors.

So the new method will need to pass these above jquery selectors to reframe or just enable for `iframe`, `object` and `embed`.
