### ISSUE TITLE
Where's the search and menu bar?

### ISSUE THREAD

**Issue by leonardoferreiradg** [TryGhost/Casper#410]
Do you need help or have a question? Please come chat in Slack: https://ghost.org/slack 👫.

If you're filing a bug 🐛, please include the following information:

### Screenshot

![]()

### Steps to Reproduce
 
 1. Why this theme doesn't has search bar and menu icon on top? ;/

### Technical details

* Casper Version: last
* Ghost Version: last
* Browser Version: all browsers
* OS Version: macOS

**Comment by kevinansfield** [comment]
@leonardoferreiradg this is neither a bug nor an actionable feature request. As it says in the default issue text you skipped over 😉:

> Do you need help or have a question? Please come chat in Slack: https://ghost.org/slack 👫.
