### ISSUE TITLE
PR #408 Breaks Highlight.js

### ISSUE THREAD

**Issue by kamioftea** [TryGhost/Casper#412]
The change to the css added in #408 is more specific than the css used by highlight.js to syntax highlight code. Pages that were previously syntax highlighing fine don't once casper is upgraded to the latest version. 

Highlight.js just uses spans for coloring, e.g. `<span class="hljs-keyword">def</span>`. If the selector is limited to elements that were displaying invisibly it should fix the issue. I'll try to submit a PR once I get chance, but it'll probably be later in the week. In the mean time if anyone has a better suggestion on how to fix it, or if you'd rather not fix the problem here since it's due to third-party css, let me know.

### Steps to Reproduce
 
 1. add `<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/obsidian.min.css">` to the page header
 2. add the following to page footer:
```
    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/scala.min.js"></script>
    <script>hljs.initHighlightingOnLoad();</script> 
```
3. add a code snippet to the page
```
    ```scala
    def aScalaFunction(): Unit
    ```
```
You should see syntax highlighted text, instead it is just white on black.
### Technical details

* Casper Version: 2.1.7
* Ghost Version: 1.18.4

**Comment by JohnONolan** [comment]
> if you'd rather not fix the problem here since it's due to third-party css

Yeah, pretty much? Not sure what else to say about this one. If you load a 3rd party script/style which breaks things, then that's generally a problem to report to the 3rd party script/style

**Comment by Costo** [comment]
The problem is not due to third party CSS. The third party CSS is fine and does not break things. The change introduced in PR #408 just "hides" all colors that are added by the syntax highlighter (highlight.js).

**Comment by JohnONolan** [comment]
Highlight.js is not part of casper and has nothing to do with casper. If you introduce a 3rd party library, then it's up to you to deal with compatibility. It is not up to Casper to anticipate every 3rd party library in the world which may or may not be added at some point. If you introduce a new displaynone.css which sets `body { display: none; }` then equally - that is not a bug in Casper. 

If Casper doesn't work for *your* particular use-case, then download it and modify it for your needs. That's how open source works.
