### ISSUE TITLE
IE11 logo size and feed icon alignment issues

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Casper#413]
### Screenshot

<img width="1194" alt="screen shot 2017-12-12 at 10 39 03" src="https://user-images.githubusercontent.com/415/33884743-d4baa6aa-df38-11e7-89d8-8bf145f7b927.png">

### Steps to Reproduce
 
1. Ensure you have a logo added in the General Settings admin screen
2. Load your blog's home screen in IE11

### Technical details

* Casper Version: 2.1.7
* Browser Version: IE11
* OS Version: Win 8.1

**Comment by ChaoticLaw** [comment]
I'm wondering has anyone else has had this happen to them? I've personally not been able to see it happen on my own site. Using a SVG for my logo.

## Screenshot
![ie11-mnguyenio-site-fs8](https://user-images.githubusercontent.com/31334284/34411124-d5ede38c-ec28-11e7-845a-3acca71e1cde.png)

## Technical details
  - Ghost 1.19.0 Production
  - Casper Version: 2.1.7
  - Browser Version: Internet Explorer 11.1000.17035.0 (Update Versions: 11.0.47)
  - OS Version: Windows 10 Pro Insider Preview (Build 17035)
