### ISSUE TITLE
Markdown Render Bug with code block in List on hosted Ghost

### ISSUE THREAD

**Issue by PaulSolt** [TryGhost/Casper#415]
The markdown doesn't format correctly when there is a code block inside a list.

It takes up more space than expected, and doesn't match the design of the post/page on both Safari and Chrome.

### Screenshot

![buggy render with code block in list](https://user-images.githubusercontent.com/371902/34118207-215e288a-e3ec-11e7-9ba6-046697bb7791.png)

Sample post:

Preview: http://blog.supereasyapps.com/p/1f814a96-82a7-4ab1-8ad2-c71ec97e0bf4/
Private: https://super-easy-apps.ghost.io/ghost/#/editor/5a37bebafd52ba0022dbf414

**Expected**

Formatting should stay the same for the width, the code block should render inside the list

**Actual**

1. The entire list is enlarged by 1-2 inches
2. Makes it feel out of place with the normal width the of the article

### Steps to Reproduce
 
 1.  Create a code block in a list view
2. Use content sample at bottom of post.

### Technical details

* Casper Version: Forked: https://github.com/SuperEasyApps/Casper (2.1.6)
* Ghost Version: Hosted? No idea ...
* Browser Version: Safari 11.0.2 /Chrome Version 63.0.3239.84 (Official Build) (64-bit)

* OS Version: High Sierra 10.13.2

# Sample Content (Buggy at top, expected format at bottom)

## 10. Create an `@IBInspectable` `UIColor` Property

You can create `UIColor` properties that are @IBInspectable and let the user pick a color using Xcode's built-in color picker.

1. Create a function to update the color of the UIButton's background image:

    ```swift
    func refreshColor(color: UIColor) {
        let image = createImage(color: color)
        setBackgroundImage(image, for: UIControlState.normal)
        clipsToBounds = true
    }
    ```

    Creating the image and setting the backround image are fairly self-explanitory, but clipToBounds needs to be enabled, otherwise the corners will not rounded (which is kind of the point of this tutorial).

2. Create a `@IBInspectable` variable for the background color named `backgroundImageColor` and call the `refreshColor(color:)` method:

    ```swift
    @IBInspectable var backgroundImageColor: UIColor = UIColor.init(red: 0, green: 122/255.0, blue: 255/255.0, alpha: 1) {
        didSet {
            refreshColor(color: customBGColor)
        }
    }
    ```

    The logic is similar to how the corner radius worked, except the default value is a light blue color, similar to the default `Tint` Color on iOS 11.

3. Make sure to add the call to `refreshColor()` to your `sharedInit()` to ensure the default color is set when you create the `RoundedButton` and run the app:

## 10. Create an `@IBInspectable` `UIColor` Property

You can create `UIColor` properties that are @IBInspectable and let the user pick a color using Xcode's built-in color picker.

1. Create a function to update the color of the UIButton's background image:

    Creating the image and setting the backround image are fairly self-explanitory, but clipToBounds needs to be enabled, otherwise the corners will not rounded (which is kind of the point of this tutorial).

2. Create a `@IBInspectable` variable for the background color named `backgroundImageColor` and call the `refreshColor(color:)` method:

    The logic is similar to how the corner radius worked, except the default value is a light blue color, similar to the default `Tint` Color on iOS 11.

3. Make sure to add the call to `refreshColor()` to your `sharedInit()` to ensure the default color is set when you create the `RoundedButton` and run the app:

**Comment by AileenCGN** [comment]
This seems to be a CSS issue. PR is welcome!
