### ISSUE TITLE
Inlined images are not inlined in the article

### ISSUE THREAD

**Issue by andreygrehov** [TryGhost/Casper#416]
I inline formulas as images. It works great in the editor's preview screen, but when I open post in the Preview mode (via the Preview link in the Post Settings), Ghost places all the inline images as separate elements.

This is how it looks in the Side-by-Side preview screen:

<img width="628" alt="screen shot 2017-12-29 at 5 48 52 pm" src="https://user-images.githubusercontent.com/409722/34457587-4dae5810-ed83-11e7-8d5d-bfec93e1be60.png">

And here is the same piece of content in the Preview mode:

<img width="824" alt="screen shot 2017-12-29 at 5 49 39 pm" src="https://user-images.githubusercontent.com/409722/34457588-53f549e0-ed83-11e7-8af0-ba4bd61970c4.png">

### Technical details

* Casper Version: 2.1.7
* Ghost Version: 1.19.0
* Browser Version: Chrome 63.0.3239.84
* OS Version: macOS Sierra 10.12.6

**Comment by AileenCGN** [comment]
Hey @andreygrehov 

Casper treats images the same as there's no way to take every possible use case into count. If you want to have a special image class to use for your inline formulas, you would need to add some CSS to your version of Casper.

You can use your image

`![example](https://yourwebsite/inline-formula.jpg#inline)`

and then in your CSS use this class:

`img[src$="#inline"] {}`

You can always use our [slack](https://slack.ghost.org/) community - https://slack.ghost.org, if you're not able to find the answer.
