### ISSUE TITLE
[FR] "Read More" links within cards

### ISSUE THREAD

**Issue by RowanKaag** [TryGhost/Casper#426]
Hi there!

Let me start off by stating that I'm loving the new Casper lay-out! Just went back to Ghost again from using WordPress a while intermittently. 

Now, for my ~~"issue"~~|Feature Request, is it possible (within Casper) to add a "Read More" `<span>` or `<button>` at the end of a `section.post-card-excerpt`? I am aware that, within `current/content/themes/casper/partials/post-card.hbs` the `{{excerpt}}` variable is stated which gathers the (custom) excerpt data. 

It might be a nice add-on to have this feature added in addition to the `words ="33"` section to visually indicate that there is more content behind the link.

Would love to hear your thoughts.

### Technical details
* Casper Version: 2.1.9
* Ghost Version: 1.20.3
* Browser Version: Safari 11.0.2 (13604.4.7.1.6)
* OS Version: macOS 10.13.2 (17C205)

**Comment by AileenCGN** [comment]
Hi @RowanKaag 

Thanks for the idea! 

We only keep Github issues open for bugs and in-progress feature work, but always happy to chat about future ideas over on our  [slack](https://slack.ghost.org/) community - https://slack.ghost.org.
