### ISSUE TITLE
Still localhost:2368 even if env url set

### ISSUE THREAD

**Issue by hedefalk** [TryGhost/Casper#428]
1. Start a new ghost blog self-hosted
2. Use a proxy with a domain
3. Use casper

Expected - all links should work when env url is set.

Real: One of the links is going to localhost:xxxx, the main thingie here:

![image](https://user-images.githubusercontent.com/116520/35628782-3f82ce28-069d-11e8-91b9-93270f8566b3.png)

![image](https://user-images.githubusercontent.com/116520/35628784-4192a29c-069d-11e8-8a08-4218262879be.png)

It's the `blog.url` variable that isn't correct, everything else seems to work:

https://github.com/TryGhost/Casper/blob/bfaae0f7ba5c4b9d70d9f37b65ea765257aa5486/partials/site-nav.hbs#L5

### Technical details
* Casper Version: latest
* Ghost Version: latest

**Comment by hedefalk** [comment]
I realize this probably isn't Casper's fault since other themes use the same var.

**Comment by ErisDS** [comment]
@hedefalk please check out https://docs.ghost.org & https://slack.ghost.org. This is a configuration issue - not a bug in Ghost or Casper.
