### ISSUE TITLE
WARN Theme's file locales/en.json not found.

### ISSUE THREAD

**Issue by yaccin** [TryGhost/Casper#432]
After updating my ghost installation to the latest version (1.21.1) it is no longer starting. Instead I get this error message:

`WARN Theme's file locales/en.json not found.`

Since I am using the default theme without any modifications it is rather annoying. The file is indeed not in the themes directory, and also not available in this repository.

**Comment by kevinansfield** [comment]
@yaccin that's just a warning, it won't be the reason Ghost isn't starting. Please swing by our [Slack channel](https://slack.ghost.org) to get support, we use GitHub solely for bug tracking and on-going feature work and do not offer any support here.
