### ISSUE TITLE
[Feature Requests] Enhancing theme with Disqus integration & Prism-powered syntax highlight.

### ISSUE THREAD

**Issue by asharamseervi** [TryGhost/Casper#433]
Hello Awesome Guys,

Hope you're doing well. I just installed Ghost & loving it. This theme impressed me a lot.
After researching, I got to know, @hungys is supercharging this theme with lots of needful enhancements at: https://github.com/hungys/CasperS.
I appreciating his efforts and requesting to community to update theme with following changes:
- [ ] Update: noopener like: target="_blank" rel="noopener" at /partials/site-nav.hbs
- [ ] Feature Request: Google Analytics integration
- [ ] Feature Request: Prism-powered syntax highlightDisqus integration
- [ ] Feature Request: Disqus integration
- [ ] Feature Request: Social links with Simple Icons integration

& much more (SEO point of view). **Open for discussion & raising pull requests.**

**Comment by kevinansfield** [comment]
@asharamseervi all of these are easily possible by editing your theme to your requirements or adding snippets in the Code Injection area of Ghost's admin and Disqus integration is [already present](https://github.com/TryGhost/Casper/blob/master/post.hbs#L72-L93).

None of the items in your list are applicable to everyone and so are not in Casper's scope - it's meant as a basic starter theme ready for customisation so I'm going to close this issue.

**Comment by asharamseervi** [comment]
I believe, Developers usually prefer Ghost instead of other CMS. Like me, there are a lot of Developers who looking forward to sharing their snippets, why not to collaborate on Prism-powered syntax highlight??

**Comment by kevinansfield** [comment]
@asharamseervi that's fine if you want to do that but this repo is not the place, we use GitHub solely for bug tracking and on-going feature work. If you want to create a developer-focused fork of Casper you're free to do so 😄

**Comment by asharamseervi** [comment]
But, I wish to contribute & giving back to the community. If so, this will stop me to do further contributions, because this is first ever I'm willing to contribute to Ghost Community. Sorry to say, stepping back from Awesome Project. Thanks & Good Luck.

**Comment by kevinansfield** [comment]
Forking and creating a developer-focused version of Casper with your specific comment service and highlighting preferences _is_ contributing and giving back to the community. What I'm saying is that those don't belong in the base Casper theme because developers are not the intended audience and the default theme should not be forcing site-specific preferences.

If you want to find people to help contribute to your Casper "developer edition" theme there's always our [Slack team](https://slack.ghost.org) where you can reach out on the `#themes` channel.
