### ISSUE TITLE
Author.hbs rss url contains one slash too much

### ISSUE THREAD

**Issue by cotko** [TryGhost/Casper#434]
here https://github.com/TryGhost/Casper/blob/master/author.hbs#L33

should probably end with `{{url absolute="true"}}rss/` instead of `{{url absolute="true"}}/rss/`

Example is [on ghots's blog site](https://blog.ghost.org/author/john/) where the linked rss is 

http://cloud.feedly.com/#subscription/feed/https://blog.ghost.org/author/john//rss/

**Comment by kirrg001** [comment]
Thanks for the report. PR is welcome 👍
