### ISSUE TITLE
Improve way to enable Disquss

### ISSUE THREAD

**Issue by prashanthmadi** [TryGhost/Casper#440]
It would be great if we can set disqus-id from environment variable :)
```
s.src = 'https://test-apkdzgmqhj.disqus.com/embed.js';
```
https://github.com/TryGhost/Casper/blob/master/post.hbs#L87

and also if we could enable discuss from environment variable too rather than manually editing the code :).

**Comment by vikaspotluri123** [comment]
You wouldn't be able to set it via an environmental variable since that line is frontend javascript; themes don't have access to any of the backend js 😉

**Comment by prashanthmadi** [comment]
Thnks @vikaspotluri123 

may be we could try something as ghostium. changing in partials/custom/config.hbs file  
https://github.com/oswaldoacauan/ghostium#configuring

Ex:
https://github.com/oswaldoacauan/ghostium/blob/master/partials/custom/config.hbs#L5

**Comment by AileenCGN** [comment]
Hi @prashanthmadi 

Thanks for the idea!

We only keep Github issues open for bugs and in-progress feature work. I'll add the idea to our internal ideas board. As soon as the feature gets requested often enough, we discuss and schedule the feature for an upcoming sprint.
