### ISSUE TITLE
Display publish date in the overview cards

### ISSUE THREAD

**Issue by pgrm** [TryGhost/Casper#442]
A friend of mine pointed out, that it would be nicer if the date would be visible on the cards when looking at an overview. Now looking at https://blog.ghost.org/ I totally agree with him. It would be great to see at one glance, when each post was published so that I can get a feeling, if I missed reading something, or how up to date some information might be.

He provided the following screenshot of an example on how it could look like: 

![image](https://user-images.githubusercontent.com/713456/38220555-104e4d62-36db-11e8-89f2-4e6e6e9af348.png)

Although, I see now, that his date format is too long for some of the publishers on https://blog.ghost.org/ it could be reduced to just dd.MM.yy or MM/dd/yy or what ever you prefer.

### Steps to Reproduce
 
 1. Having some posts, open the man page of your blog, with a list of latest posts, you won't see any information about the date, when those post were published.

### Technical details

* Casper Version: 2.1.10
* Ghost Version: 1.22.0
* Browser Version: Chrome 65

**Comment by AileenCGN** [comment]
Hi @pgrm 

Thanks for the idea!

We only keep Github issues open for bugs and in-progress feature work. Please check out [our forum](https://forum.ghost.org) to see if your suggested idea already exists, so you can upvote it, or post this idea in the features section for other users to see and upvote.

**Comment by pgrm** [comment]
For anyone who will find the issue in the future - here's the suggestion in the forum: https://forum.ghost.org/t/casper-display-publish-date-in-the-overview-cards/665
