### ISSUE TITLE
Floating header conflicts with footnote

### ISSUE THREAD

**Issue by yizhigou** [TryGhost/Casper#444]
The float header will cover the footnote target.

![2018-04-04 17_16_12](https://user-images.githubusercontent.com/2212749/38299601-119654dc-382d-11e8-9439-272962083a27.gif)

* Casper Version: 2.1.10
* Ghost Version: 1.22.0
* Browser Version: Chrome 65.0.3325.181
* OS Version: macOS 10.13.3 (17D102)

**Comment by JohnONolan** [comment]
Duplicate of #369
