### ISSUE TITLE
Casper bug on hover over post author icon

### ISSUE THREAD

**Issue by blagoeres** [TryGhost/Casper#456]
Hello, I noticed a small but in Casper when I hover over post author icon. This happens only on full width cards. The below is animated gif that shows the behavior when you hover over icon. I am using Google Chrome browser.

![bug](https://user-images.githubusercontent.com/15614178/40369924-5f31c820-5ddf-11e8-8fdb-d82e5988f6c1.gif)

**Comment by JohnONolan** [comment]
This looks like a browser rendering bug to me, not specific to anything in Casper or Ghost (I can't reproduce). I imagine it'll go away by itself, but if not feel free to let us know again in future :)
