### ISSUE TITLE
Search feature and option to turn off infinite scroll?

### ISSUE THREAD

**Issue by resting** [TryGhost/Casper#461]
As above.
Would be great to have a search feature on the site and the option to turn off infinite scroll and use pagination instead.
Right now, its just hard to find old posts when you have 50 or more of them for example.

**Comment by kevinansfield** [comment]
@resting Ghost doesn't support search natively so it's not included in the default theme and the purpose of Casper is to be a well-designed simple starting point so there's no configuration. You're free to add both of those features to your own theme 😉
