### ISSUE TITLE
Mobile width content overflow

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Casper#464]
### Screenshot

![img_3197](https://user-images.githubusercontent.com/415/43386685-5758f992-93dc-11e8-8f39-5241966c9ba4.png)

### Steps to Reproduce
 
 1. Open https://demo.ghost.io/using-tags/ on a mobile device or using Chrome DevTools's device toolbar set to a mobile width

### Technical details

* Casper Version: 2.4.0
* Ghost Version: 1.25.2

**Comment by jessehouwing** [comment]
Not entirely fixed it seems: 
![image](https://user-images.githubusercontent.com/4173387/43458425-89cdfdc0-94ca-11e8-9524-fed92944aab8.png)

When there is a long `code-element-code-element-code-element-code-element-code-element-code-element-code-element-code-element-code-element-code-element-code-element-code-element-code-element-code-element-` the line doesn't wrap.

**Comment by kevinansfield** [comment]
Hey @jessehouwing 👋 Good catch! 😄 This appears to be a different issue, one that was around before the issue this PR addressed. I've opened a new issue for it here https://github.com/TryGhost/Casper/issues/466
