### ISSUE TITLE
Long words do not break causing content overflow

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Casper#466]
### Screenshot

![](https://user-images.githubusercontent.com/4173387/43458425-89cdfdc0-94ca-11e8-9524-fed92944aab8.png)

Sample page: https://jessehouwing.net/visual-studio-2017-merge-tool-in-tower/

### Steps to Reproduce
 
1. Add a very long word with no spaces to a paragraph

### Technical details

* Casper Version: <= 2.4.1

**Comment by kevinansfield** [comment]
Initial testing indicated that we need something like the following applied to children of `.post-content` or `.kg-card-markdown`:

```css
max-width: 100%;
word-wrap: break-word;
```

**Comment by TonnyORG** [comment]
@kevinansfield Fixing this one here: #483

**Comment by JohnONolan** [comment]
^ merged

**Comment by fadeevab** [comment]
Guys, and now it wraps always even if inline code is short:
![Annotation 2019-08-06 191915](https://user-images.githubusercontent.com/5967447/62557292-61a3e880-b87f-11e9-9b9b-5d4d94de0946.png)

**Comment by JohnONolan** [comment]
Nice.
