### ISSUE TITLE
Responsive layouts failed when I using casper v2.5.0

### ISSUE THREAD

**Issue by OIdiotLin** [TryGhost/Casper#472]
### Steps to Reproduce
 
1. I updated my casper theme from v2.2.1 (default when i installed ghost) to the latest v2.5.0.
2. The web page displayed in my cellphone is crashed (responsive error). 

This is the normal web page displayed with old version casper(v2.2.1)

![good](https://user-images.githubusercontent.com/8947243/44330379-68342700-a499-11e8-9586-6e1f212b2eaf.png)

The screenshot below shows the situation i met after i updated casper to v2.5.0. **I cannot drag the web page either**.

![mess](https://user-images.githubusercontent.com/8947243/44330380-68342700-a499-11e8-94d1-55ca304d3527.png)

### Technical details

* Casper Version: v2.5.0
* Ghost Version: v1.22.7
* Browser Version: Google Chrome 66.0.3359.181
* OS Version: Ubuntu 16.04.4 LTS

**Comment by kevinansfield** [comment]
@OIdiotLin Casper 2.5.0 is only compatible with Ghost 2.0.0 or later. From the [release notes](https://github.com/TryGhost/Casper/releases/tag/2.5.0):

> **Ships with Ghost 2.0.0. Compatible with Ghost >= 2.0.0.**
