### ISSUE TITLE
Make CC0 (and others?) available apart from copyright symbol (©)

### ISSUE THREAD

**Issue by sgort** [TryGhost/Casper#477]
My website hosts at https://datafluisteraar.org/ where I prefer CC0 instead of ©. I couldn't find no other way than editing the default.hbs file on the server. I'm not a coder and I don't know how to properly fix this without editing such a template file.
Herewith the issue though. Please make CCO (and others?) available apart from copyright symbol (©)

**Comment by gargol** [comment]
Hey @sgort :wave: Editing `default.hbs` is a completely fine approach in this situation :smiley: Themes can't account for every possible customization and are open for editing for this exact purpose.
