### ISSUE TITLE
PR #408 Breaks Highlight.js #2

### ISSUE THREAD

**Issue by flip111** [TryGhost/Casper#486]
I'm also effected by the things discussed in https://github.com/TryGhost/Casper/issues/412

I open a new issue because the other issue was locked. It's fine that it's closed, but why prevent discussion? I like to discuss with other people a solution for this.

Many bloggers blog about software, they like syntax highlighting, they use highlightjs.
Many bloggers like ghost, they use casper.
There will be a group of people who use casper + highlightjs. These two things are related by the people who use it in this way. It's now 3 people @kamioftea @Costo and me, so not particular for one person. And also the people who couldn't post in the topic since last year or just didn't bother to post.

Can open source also have open discussion?

I'm not sure how common it is to use highlightjs + ghost (missing metrics). However if the css theme of casper can be rewritten to have the same look and not get messy css code it can be a win to have highlightjs support.

**Comment by Costo** [comment]
This PR might have fixed this issue: https://github.com/TryGhost/Casper/pull/484

**Comment by flip111** [comment]
Thanks @Costo !
