### ISSUE TITLE
Modernising Casper

### ISSUE THREAD

**Issue by MishUshakov** [TryGhost/Casper#515]
Hey, I really love using Ghost, that's an amazing product, people seem to love. But I don't like, that the **default** Casper theme, which I'm using (and millions of others) depends on jQuery. I doesn't think it has to be that way. We are now in 2019 and have every jQuery feature available as a native implementation. Im suggesting you to rewrite the jQuery-dependent parts in the modern JavaScript (document.querySelector, fetch API, Intersection Observer API). I will hack around on that for myself in the upcoming weeks.

According to https://web.dev (Google's guides) it does also make sense to lazy-load images using lazysizes.js (easy to implement).
I'm also wondering, why Ghost does support AMP, but has no support for PWA (Progressive Web Apps). It's not critical, but it's just SAD, because users can't read our articles offline.

Additionally there is a need for a proper accessibility audit and patches to be made, because some colours used in the theme seemed to have insufficient contrast ratio (which means, it would be impossible to read, for some users)

Thank you a lot, you have done an awesome job 👍

**Comment by gargol** [comment]
Hey @MishUshakov  👋 We ask that you please do not use GitHub for feature requests, the default issue templates pointed you to our [forum](https://forum.ghost.org) for this type of question - the [Ideas](https://forum.ghost.org/c/Ideas/l/votes) topic will let you propose features and let others vote on them 😄. We use GitHub solely for bug-tracking and on-going feature development so we try to keep it noise free.

FYI: Many projects have their own support guidelines and GitHub will highlight them for you, or the project owners will use issue templates to point you in the right direction, please read them before opening issues.
