### ISSUE TITLE
Images with long annotations are left-aligned

### ISSUE THREAD

**Issue by brandonskerritt** [TryGhost/Casper#517]
Do you need help or have a question? Please come chat in our forum: https://forum.ghost.org 👫.

If you're filing a bug 🐛, please include the following information:

### Screenshot
![image](https://i.imgur.com/UMMOzwv.png)
In the editor

![image](https://i.imgur.com/A23pcmy.png)
In the published post (it's hard to see, but it is left aligned here instead of center aligned)

### Steps to Reproduce
 
 1. Upload an image to Ghost, Casper theme (I copied and pasted it)
2. Write a long annotation under the image
3. Image is now left-aligned when published
### Technical details

* Casper Version: Most recent (blog was created on 05/01/2019)
* Ghost Version: Most recent (blog was created on 05/01/2019)
* Browser Version: Firefox - latest build (Firefox was downloaded on 05/01/2019)
* OS Version: Windows 10, latest build (Windows was installed & updated on 05/01/2019)

**Comment by JohnONolan** [comment]
@peterzimon Think max-width is needed here both in Casper and in Admin

**Comment by mchlbowyer** [comment]
Is there a fix for this? Having the same issue where any image with more than 1 line on the caption is left aligned.

Thanks

**Comment by peterzimon** [comment]
fixed with https://github.com/TryGhost/Casper/commit/74ae3d5140498196a76e5cc4f54f8b6974f60cc0
