### ISSUE TITLE
Twitter embeds are too wide

### ISSUE THREAD

**Issue by bershatsky** [TryGhost/Casper#524]
When copying a link to a tweet, and letting Ghost do the auto-embed, the sides are cut off when viewed on a mobile device.

However, if you use Twitter's actual embed code and put it in an HTML element, then it looks just fine on a mobile device.

**Comment by gargol** [comment]
Related report with a visual example - https://forum.ghost.org/t/twitter-card-cut-off-on-mobile-device/6167

**Comment by aclysma** [comment]
I had something similar happen when I had a code snippet emedded on a page (https://i.imgur.com/I2zfOE5.jpg). I am using casper with an extra CSS file mostly to tweak the colors, and adding this to the end seems to have fixed it. (By default it was set to "center"). I don't think this reproduced unless I had a caption with long-ish text attached to the snippet, so I'm not sure if it's the same problem or not.

`div.post-content { align-items: unset; }`
