### ISSUE TITLE
[Feature Request] Support SASS

### ISSUE THREAD

**Issue by alex285** [TryGhost/Casper#529]
hello! this is kinda related to https://github.com/TryGhost/Casper/issues/169 but since that was 4 years ago i want to re-open it

im using Ghost for first time (and btw you have done great job there!) so i thought to build my theme based on Casper. i do not mind if Casper uses CSS, but it would be nice if build scrips could also handle SASS when there is under `assets/sass` for example

to add; that would be very handy for someone that is just starting with Ghost, since the template system is so awesome that eventually everyone will develop their own themes from scratch, therefore they can add SASS

**Comment by ErisDS** [comment]
Hi @alex285 if you're adding SASS to a theme, then it's up to you to also add the necessary build tools. This is nothing to do with Ghost, or Casper - your choice of tooling, whether that's css processors or build tools is entirely up to you. We just happen to use postcss & gulp.

**Comment by alex285** [comment]
no worries, already wrote a SASS Gulp; it was more like a friendly suggestion, so new Ghost people will have a smoother starting up :)
