### ISSUE TITLE
Next and previous posts don't work correctly

### ISSUE THREAD

**Issue by nguyentk90** [TryGhost/Casper#534]
Hi,

I've just upgrade from Ghost 1.x to Ghost 2.0, the upgrade was successful. I tried the latest version of Casper theme but it didn't work. I didn't make any modification in the theme.

### Screenshot

![](https://i.imgur.com/POouDLu.png)

### Steps to Reproduce
 
 1. Open a post
 2. Scroll to the bottom, there are two related post (next/previous), but the summary doesn't work, it show undefined and the url doesn't as well, when click on it, it return to home page (/).

### Technical details

* Casper Version:2.9.3
* Ghost Version:2.16.2
* Browser Version:Chrome 72.0.3626.119
* OS Version:macOS

**Comment by Kimbanjang** [comment]
i have same issue in post

**Comment by kirrg001** [comment]
Can you please update to 2.16.3? Thanks!

**Comment by kirrg001** [comment]
Closing. This was fixed in [2.16.3](https://github.com/TryGhost/Ghost/releases). I recommend updating to the latest Ghost version [2.16.4](https://github.com/TryGhost/Ghost/releases).
