### ISSUE TITLE
Adding a GTM code into the theme file

### ISSUE THREAD

**Issue by nmoumen** [TryGhost/Casper#551]
Hi,

For tracking purpose (e.g. scroll on my content), I need to add a GTM code into the theme file.

Bellow the steps I've followed so far: 
- Download the theme from Ghost to be able to modify it
- Updated the file "default.hbs" using a text editor, including my gtm code before (and another try after) the <body>
- Change the name of my "default. rtfd" after modification back to "default.hbs"
- Download the modified template using the same name to avoid complication, but I am requested to change the name ("Sorry, the default Casper theme cannot be overwritten.
Please rename your zip file and try again.")
- Change the name for casper–1- and upload it into Ghost for activation
- activation of the new template casper-1- confirmed
=> but at this stage, when I go on my blog homepage, I have an 505 error message saying : 
“ENOENT: no such file or directory, open ‘/home/ghost/content/themes/casper–1-/default.hbs’”

Any idea what I am doing wrong ? 

Ps: I am using the casper 2.9.5
Note: I am a marketer not a developer, please keep it simple :-) 

<img width="897" alt="Capture d’écran 2019-03-16 à 09 18 40" src="https://user-images.githubusercontent.com/45001310/54472696-0d637380-47cd-11e9-99f5-ad90d36cd070.png">
<img width="1270" alt="Capture d’écran 2019-03-16 à 09 23 20" src="https://user-images.githubusercontent.com/45001310/54472705-2b30d880-47cd-11e9-91a9-96b7708430fe.png">

**Comment by kevinansfield** [comment]
Hey @nmoumen  👋 Friendly reminder: help or support is not available on Github. Our default issue templates pointed you to our [forum](https://forum.ghost.org) for this type of question 😄 We use GitHub solely for bug-tracking and on-going feature development so we try to keep it noise free.

Many questions can be answered by reviewing our docs for [self-hosters](https://docs.ghost.org), our [theme API](https://themes.ghost.org), or our [public API](https://api.ghost.org). If you can't find an answer then our [forum](https://forum.ghost.org) is a great place to get community support, plus it helps create a central location for searching problems/solutions.

FYI: Many projects have their own support guidelines and GitHub will highlight them for you, or the project owners will use issue templates to point you in the right direction. Reading the guidelines or issue templates before opening issues can save you and other project maintainers some valuable time.
