### ISSUE TITLE
`<blockquote>` styling is inconsistent with a child `<p>`

### ISSUE THREAD

**Issue by fadeevab** [TryGhost/Casper#562]
### Issue Summary

![quote-inconsistency](https://user-images.githubusercontent.com/5967447/55682811-f550c100-5940-11e9-9d25-9b63829db5a2.png)

### To Reproduce

1. Add markdown block and type "> Test".
Resulting HTML:
```html
<blockquote><p>Markdown</p></blockquote>
```
2. Type "> Test" right into Ghost editor.
Resulting HTML:
```html
<blockquote>Not markdown</blockquote>
```

### Technical details:
Ghost Version: Version 2.19.3
Node Version: 8.15.1
Browser/OS: Firefox 66.0.2 (Windows)
Database: MySQL

**Comment by fadeevab** [comment]
Transferred from TryGhost, see https://github.com/TryGhost/Ghost/issues/10666#issuecomment-481319470

**Comment by fadeevab** [comment]
@kevinansfield wrote: "The difference in HTML output with an inner <p> vs no inner <p> is a known difference between the markdown renderer output and the rich-text renderer output and is not a bug in the editor.

Themes should be prepared to handle the variation as both are valid HTML, if you are using Casper could you open an issue on that repo or report the issue on the respective theme repo or to the theme developer. Thanks 🙂"

**Comment by ofadieiev** [comment]
@JohnONolan 

The issue is closed, but not fixed. 

![image](https://user-images.githubusercontent.com/49716172/68593904-1d883b80-049f-11ea-83b4-b0fb1517da23.png)
