### ISSUE TITLE
Gulp globbing not optimised

### ISSUE THREAD

**Issue by ptalmeida** [TryGhost/Casper#578]
gulpfile.js in 

- function `hbs` and watcher `hbsWatcher`
  - ` 'node_modules/**/*.hbs'` is never matched by `'*.hbs'` so there is no need for the negative. 
  - There is no need to match `'partials/**/*.hbs'` instead of the less intensive `'partials/**'`

- function `css` in `src('assets/css/*.css', {sourcemaps: true}),`
  -  doesn't match nested files while `cssWatcher` does. 
  -  matches file extension while `cssWatcher` doesn't. 

- function `js` in `src('assets/js/*.js', {sourcemaps: true}),`
  -  unnecessarily matches file extension.

Should I open a PR with the small fixes necessary?

**Comment by JohnONolan** [comment]
Sure @ptalmeida - PR welcome :)
