### ISSUE TITLE
    "posts_per_page": 6 doesn't work

### ISSUE THREAD

**Issue by StreetFlaneur** [TryGhost/Casper#582]
i set  "posts_per_page": 6 , but  doesn't work
home page return all posts 
==
Can you help me？

**Comment by allouis** [comment]
Casper has an infinite scroll plugin, if you look carefully only the first 6 posts will be loads, but as you scroll the rest would come in. You can remove this line from default.hbs to stop that https://github.com/TryGhost/Casper/blob/master/default.hbs#L79
