### ISSUE TITLE
New lines are not spaced out in card preview

### ISSUE THREAD

**Issue by davisonio** [TryGhost/Casper#594]
### Screenshot

![Screenshot 2019-07-09 at 18 20 04](https://user-images.githubusercontent.com/5341072/60909519-5789cc80-a276-11e9-8b0b-79aba9621c38.png)

### Steps to Reproduce
 
 1. Create a post that has a line break within first couple of lines
 2. See blog post listing

### Technical details

* Casper Version: Latest (I think)
* Ghost Version: 2.23.0
* Browser Version: Chrome Latest
* OS Version: macOS Latest

**Comment by vikaspotluri123** [comment]
Sounds like a duplicate of https://github.com/TryGhost/Ghost/issues/10531

**Comment by davisonio** [comment]
> Sounds like a duplicate of [TryGhost/Ghost#10531](https://github.com/TryGhost/Ghost/issues/10531)

Didn't see that one thanks!
