### ISSUE TITLE
Security vulnerability in lodash

### ISSUE THREAD

**Issue by ja573** [TryGhost/Casper#597]
It's just come to our attention that one of the dependencies of this template, lodash, has a high security issue:
https://github.com/lodash/lodash/pull/4336

The issue have been patched in  version "4.17.13", while Casper currently depends on version 4.17.11.

**Comment by gargol** [comment]
There's no direct depenency on lodash which would affect production code. Casper only has [devDependencies](https://github.com/TryGhost/Casper/blob/master/package.json#L47) which are not critical :smiley:
