### ISSUE TITLE
text descenders get cut off when floating logo image is hidden

### ISSUE THREAD

**Issue by 06b** [TryGhost/Casper#600]
### Screenshot

![image](https://user-images.githubusercontent.com/1302542/62216927-ac050100-b377-11e9-8791-76cc66d48d54.png)

Screenshot is of from https://demo.ghost.io/themes/ where "Ghost" is changed to "ghost" and I've hidden the Ghost Icon. I've underlined the issue in red in the screenshot to show the issue.

### Steps to Reproduce
 
 1. Have a title in the floating logo which contains descenders (such as g, y, j)
 2. Hide the logo image.

### Technical details

* Casper Version:
* Ghost Version:
* Browser Version: Google Chrome 75
* OS Version: Windows 10, Version: 1903

Fixed by PR #595

**Comment by JohnONolan** [comment]
Can't reproduce

![image](https://user-images.githubusercontent.com/120485/63406050-44445200-c41b-11e9-8a86-66edc58ea660.png)

**Comment by 06b** [comment]
@JohnONolan It appears you did not complete step 2.

See Below:
![Casper-Title](https://user-images.githubusercontent.com/1302542/63442492-31bd1f00-c401-11e9-8956-ea86cf56f7fb.gif)
