### ISSUE TITLE
Default AMP theme's file paths

### ISSUE THREAD

**Issue by arlopezg** [TryGhost/Casper#603]
Hey guys :)

As seen in https://ghost.org/blog/amp-support/, Ghost supports Google's AMP since 2016. We're currently working with Casper and would like to make some modifications to the default AMP theme, but can't seem to find the `amp.hbs` or `partials/amp-*.hbs` files to work on.

My question is, after looking seemingly everywhere: where is Ghost pulling the default AMP template from? Where can I find those files?

(If it's useful, here is a [link to a live AMP post](https://blog.autoplaza.cl/como-trabajar-en-uber-conoce-los-requisitos-y-caracteristicas/amp))

Thanks in advance!

Edit: also I checked the [default documentation](https://ghost.org/docs/api/v2/handlebars-themes/google-amp/) on AMP and its link to the default `amp.hbs` seems to be down 🤔 

### Technical details

* Casper Version: 2.10.5
* Ghost Version: 2.0.0
* Browser Version: Chrome (latest)

**Comment by jessehouwing** [comment]
https://github.com/TryGhost/Ghost/blob/df7e64fafa122ec5d461c4772eca86d21938046b/core/frontend/apps/amp/lib/views/amp.hbs

**Comment by jessehouwing** [comment]
The default amp template ships with Ghost itself instead of the theme.

**Comment by mvasilkov** [comment]
In the docs it says you can put the amp.hbs in the theme's folder, and Ghost will load it from there. Haven't tried it yet.

**Comment by jessehouwing** [comment]
That works. I did that for my own customization...

https://github.com/jessehouwing/jessehouwingnl-Casper/blob/customized/amp.hbs

**Comment by arlopezg** [comment]
> The default amp template ships with Ghost itself instead of the theme.

**Comment by arlopezg** [comment]
> https://github.com/TryGhost/Ghost/blob/df7e64fafa122ec5d461c4772eca86d21938046b/core/frontend/apps/amp/lib/views/amp.hbs

Thanks @jessehouwing! That's it. I'll send a heads up so that docs' link is updated.

**Comment by arlopezg** [comment]
> In the docs it says you can put the amp.hbs in the theme's folder, and Ghost will load it from there. Haven't tried it yet.

You are right. As someone replied before, the default `amp.hbs` was in Ghost's itself folder.

**Comment by jessehouwing** [comment]
@arlopezg It would be nice if the template was also part of the Ghost repo. It makes it much easier for us to stay up to date with the base version in custom themes.
