### ISSUE TITLE
Cannot close email subscription signup form in Chrome or Firefox

### ISSUE THREAD

**Issue by mchlbowyer** [TryGhost/Casper#630]
Do you need help or have a question? Please come chat in our forum: https://forum.ghost.org 👫.

If you're filing a bug 🐛, please include the following information:

### Screenshot

![]()

### Steps to Reproduce
 
 1. Open email subscription signup form on any page from navbar
 2. Try to click X at top right (same with escape key)

### Technical details

* Casper Version: Latest
* Ghost Version: 3.0.0
* Browser Version: Chrome Version 77.0.3865.120 (Official Build) (64-bit)
* OS Version: macOS 10.15

**Comment by gargol** [comment]
Hey @mchlbowyer! Could you please add the outputs in the dev console (if there are any). Did you try running it on other browsers, does it still happen there?

**Comment by sebastiansledz** [comment]
I can notice the same on Chrome and Firefox latest builds.
Closing of the subscribe form is possible only outside the class: **subscribe-overlay-content**
There is not any output in dev console.

Please see the screen - close is working on both sides just after the padding ends for above mentioned class.

[screen](https://sleepy-babbage-f86266.netlify.com/casper-sub-form.png)

**Comment by Michael-Brooks** [comment]
I'm a FireFox user and have experienced the same issue.

**Comment by mchlbowyer** [comment]
@gargol no dev output. Works fine on Safari but not on Chrome, and as @sebastiansledz and @Michael-Brooks said its the same on Firefox too.

**Comment by gargol** [comment]
Was able to reproduce this behavior. More detailed way to reproduce this bug:
1. Open the home page in a small vertical orientation (e.g. simulate viewport of Pixel 2 in vertical mode)
2. Click subscribe button
3. No way to close the modal

![Screenshot from 2019-10-30 11-10-32 - 1](https://user-images.githubusercontent.com/675397/67848944-eeb8af80-fb05-11e9-8ea6-dd968cfd8e87.png)

**Comment by casperbh96** [comment]
#662 fixes this issue - using z-index to place the close button over text

**Comment by maurobanze** [comment]
I'm experiencing the very same problem on desktop Safari and Chrome. Clicking the 'subscribe' button takes you to a full screen popup in which the 'close' button or escape keys do not work. I'm using Casper 3.0.7

**Comment by peterzimon** [comment]
Fixed with https://github.com/TryGhost/Casper/commit/9e29e145fccb0dbd859d0fb1a6a1e1be9f7977ac
