### ISSUE TITLE
Ghost v3 errorpages don't show site branding

### ISSUE THREAD

**Issue by jessehouwing** [TryGhost/Casper#632]
### Screenshot

v3
![image](https://user-images.githubusercontent.com/4173387/67384107-cf170980-f590-11e9-9e5a-68816067172c.png)

v2
![image](https://user-images.githubusercontent.com/4173387/67384139-e655f700-f590-11e9-8968-13ae3c8a52fe.png)

### Steps to Reproduce
 
Merged the casper v3 theme with my small customization and the error page now shows blanco. The HTML does include a reference to a banner, but none is shown.

In addition, no posts are added to the bottom.

### Technical details

* Casper Version: v3.0.0
* Ghost Version: 2.37.0 (Ghhost Pro)
* Browser Version: Edge Chromium or Chrome
* OS Version: Windows 10

**Comment by jessehouwing** [comment]
Casper with minimal cursomization  v3 can be found here: 

https://github.com/jessehouwing/jessehouwingnl-Casper/tree/customized-v3

**Comment by peterzimon** [comment]
Fixed with https://github.com/TryGhost/Casper/pull/639

**Comment by jessehouwing** [comment]
Verified!
