### ISSUE TITLE
Show a different message for the error state in form submission.

### ISSUE THREAD

**Issue by ahmadajmi** [TryGhost/Casper#633]
Currently, the form shows the same _**Please enter a valid email address!**_ message for both `invalid` and `error` states.

### Invaid:

<img width="1090" alt="invalid" src="https://user-images.githubusercontent.com/626005/67419654-6437f380-f5cd-11e9-93ba-150aa6cd4d74.png">

### Error:

<img width="1148" alt="error" src="https://user-images.githubusercontent.com/626005/67419653-6437f380-f5cd-11e9-9d85-81ce9650706c.png">

The mail server is set up with a few whitelisted emails, that's why I recieve `error`. So, I think there needs to be a different message to the `error` state, for example, "An error occurred, ..."

### Technical details

* Casper Version: 3.0.0
* Ghost Version: 3.0.0

**Comment by JohnONolan** [comment]
Thanks for this feedback! We use this repository for tracking bugs in Casper, but we have a dedicated forum category for feedback about the members beta and any features relating to it :) 

https://forum.ghost.org/c/members
