### ISSUE TITLE
Dark Theme table borders show white glow

### ISSUE THREAD

**Issue by jessehouwing** [TryGhost/Casper#637]
### Screenshot

![image](https://user-images.githubusercontent.com/4173387/67679931-885b5200-f98a-11e9-84a7-5da7c1573682.png)

### Steps to Reproduce
 
https://jessehouwing.net/training-scaled-professional-scrum/

### Technical details

* Casper Version:v3
* Ghost Version:v3
* Browser Version: edge chromium
* OS Version: win 10

**Comment by peterzimon** [comment]
Fixed with https://github.com/TryGhost/Casper/pull/641
