### ISSUE TITLE
Low resolution images loaded by infinite scroll in Safari

### ISSUE THREAD

**Issue by davidmaitland** [TryGhost/Casper#638]
I can only reproduce this in Safari on macOS and iOS. Firefox and Chrome on macOS are unaffected. See screenshots for example.

**Safari:**

_Bottom image is first to be loaded by infinite scroll_

<img width="593" alt="Screenshot 2019-10-28 at 13 35 13" src="https://user-images.githubusercontent.com/1108606/67682930-534e0000-f988-11e9-93be-7955ed90fe8e.png">

**Firefox:**

<img width="584" alt="Screenshot 2019-10-28 at 13 35 19" src="https://user-images.githubusercontent.com/1108606/67682973-66f96680-f988-11e9-8afc-90320f29a597.png">

I thought this might be related to #636, but I have applied the patch and it doesn't fix the resolution issue.

### Technical details

* Casper Version: 3.0.0 (tested with #636 as well)
* Ghost Version: 3.0.0
* Browser Version: macOS Safari Version 13.0.2 (15608.2.30.1.1) & iOS 13.1.3 Safari
* OS Version: macOS 10.15

**Comment by kevinansfield** [comment]
@davidmaitland did you rebuild the JS after applying #636? Unfortunately that PR was missing the updated `casper.js` file which was added in a later commit here https://github.com/TryGhost/Casper/pull/639/files#diff-b6adc270a29cdce48398f40a386f885d

**Comment by davidmaitland** [comment]
@kevinansfield I don't have a dev environment for this so I just updated the files in production (`current/content/themes/casper`) and restarted ghost. I will try building from the current master and uploading the zip from `gulp zip`. But is there a way I can rebuild directly in production without having to upload through the admin UI, I assumed `ghost restart` would do it? Thanks.

**Comment by davidmaitland** [comment]
@kevinansfield pulling master and uploading the zip build from `yarn zip` seems to have worked! Thanks for pointing me in the right direction 😊
