### ISSUE TITLE
Dark theme broken on pages

### ISSUE THREAD

**Issue by DecimusJunius** [TryGhost/Casper#643]
### Screenshot

![Screenshot_20191030-190955](https://user-images.githubusercontent.com/48381010/67857419-517f6a80-fb49-11e9-9cad-8d7d92865550.png)

### Steps to Reproduce
 https://demo.ghost.io/about

### Technical details

* Casper Version: 3.0.2
* Ghost Version: 3.0.2
* Browser Version: Chromium, Safari
* OS Version: macOS, iOS, Android

**Comment by drinkredwine** [comment]
thank you for resolving. how to apply the fix to the site? i've tried to clone, zip the repo and upload but the version is still 3.0.2 and fix isn't working.  thanks for your support.
