### ISSUE TITLE
Post Excerpt is displayed on page, but not RSS feed

### ISSUE THREAD

**Issue by spaceninja** [TryGhost/Casper#645]
In Casper 2.0, I used the excerpt feature to control the bit of text that was displayed on the post cards. It wasn't displayed anywhere on the post itself, so it could be used as a teaser. However, the excerpt was often a mildly edited version of the first paragraph.

Now that I upgraded to Casper 3.0, I find that any post with an excerpt displays the excerpt text at the top of the page by the title. That means that on many of my older posts, the first paragraph displays twice.

So for the post I put up today, I thought I'd be clever, and I took the first paragraph and put it in the excerpt, so it would benefit from the nice typographical treatment. That worked fine, as the text is shown on the post card and on the page page itself.

However, I was dismayed when the post popped up in my RSS feed to find the first paragraph missing entirely, because the RSS feed doesn't include the excerpt.

My objection here is the difference between the two. Either the excerpt is now considered part of the post content (in which case it should be included in the RSS feed to match the post page), or it's not (in which case it should not be included on the post page).

The current situation means if I ever want to provide a custom excerpt it will display at the top of the page, but not be included in the RSS feed.

Since any text on the post detail page will be included in SEO, and is semantically part of the article, it's confusing to have it not included everywhere.

### Screenshot

![Screen Shot 2019-10-30 at 4 53 36 PM](https://user-images.githubusercontent.com/257309/67907646-dd879700-fb35-11e9-8b2e-2b2764f4acba.png)

^ An older article showing an excerpt that is a near duplicate of the first paragraph

![Screen Shot 2019-10-30 at 4 55 17 PM](https://user-images.githubusercontent.com/257309/67907836-8df59b00-fb36-11e9-89a7-921be780ddab.png)

^ A new post where I moved the first paragraph into the excerpt field for styling

![Screen Shot 2019-10-30 at 4 57 30 PM](https://user-images.githubusercontent.com/257309/67907857-9e0d7a80-fb36-11e9-8448-4ad78d08e97c.png)

^ That same post in the RSS feed missing the first paragraph/excerpt

### Steps to Reproduce
 
 1. Add an excerpt to a post
 2. See the excerpt displayed at the top of the post page
 3. See the excerpt is missing in the RSS feed

### Technical details

* Casper Version: 3.0.2
* Ghost Version: 3.0.2
* Browser Version: Chrome 78.0.3904.70
* OS Version: Mac OS 10.15

**Comment by JohnONolan** [comment]
Thanks for the feedback! 

This functionality you described is intended at present, but totally understand that it may not be compatible with older content archives which worked differently. You can always hide the excerpt in the post.hbs template using CSS (via code injection) or by removing it entirely, if it doesn't fit your usecase :)
