### ISSUE TITLE
[Feedback] No hover links for article titles

### ISSUE THREAD

**Issue by nkvname** [TryGhost/Casper#651]
Hi, 

Hope it's okay to leave here feedback, because I am not sure there else to do it. Kudos for new update and dark theme.

There is just one problem and we received quite a lot of feedback regarding no active hover over links in articles on home page. Basically, if you hover blog posts nothing will happen and it looks broken. 

People are expecting something to happen then they hover over links, but now nothing happens.

**Comment by JohnONolan** [comment]
Thanks for the feedback! We appreciate the info
