### ISSUE TITLE
v3.0.2: Embedded flickr Links are moving from center alignment to left alignment while site loading/refreshing

### ISSUE THREAD

**Issue by khassel** [TryGhost/Casper#652]
### Issue Summary

see title

### To Reproduce

browse https://karsten13.de/p/28474577-294d-4949-aedc-e739905e1b3b/ and press F5-Button for several times and you see the flickr-Photo moving from left to right.

This is new in v3, no problems with ghost v2.

### Technical details:
* Official docker image ghost:3.0.2
* Browser/OS: Chrome and Firefox and Edge
* Database: internal

**Comment by JohnONolan** [comment]
It seems like you're using a fixed width flickr embed - don't think there's much we can do about this

**Comment by khassel** [comment]
Hi John,

thank you for replying to this. I followed your [guide here](https://ghost.org/integrations/flickr/#copy-the-url-of-the-photo) inserting a flickr photo. On this page, the flickr photo is embedded with the same code (height, with, ...) as on my site, you can check the source code:

````
</p><figure class="kg-card kg-embed-card"><a data-flickr-embed="true" href="https://www.flickr.com/photos/johnonolan/26091690611/" title="Venice Beach by JohnONolan, on Flickr"><img src="https://farm2.staticflickr.com/1493/26091690611_849cbd83b8_b.jpg" width="1024" height="683" alt="Venice Beach"></a><script async src="https://embedr.flickr.com/assets/client-code.js" charset="utf-8"></script></figure>
````
I  updated my test-post with the same photo and the result is still a to big picture. Couldn't figure out, which ghost version your flickr-ghost-guide is running on, thinks its an older one where this issue doesn't exists.

Anyway I think there is an issue with flickr-links, because they don't respect the blog width (and they did in earlier versions).

Thanks,

Karsten.

**Comment by khassel** [comment]
so this breaking change happened with [this commit](https://github.com/TryGhost/Casper/commit/c8c63d170c7b3421f301e6e367cff492fa2eeb16). Hacking the object `kg-embed-card` in file `/assets/built/screen.css` from `width:100%` back to `min-width:100%` fixes this problem.
