### ISSUE TITLE
Dark mode on pages not working correctly (Casper theme)

### ISSUE THREAD

**Issue by betzerra** [TryGhost/Casper#653]
### Issue Summary
Pages looks great on light mode but not on dark mode (see GIF below)

![ghost_casper_bug](https://user-images.githubusercontent.com/681600/68067094-ebe5d680-fd20-11e9-99fe-40c3365c6b9b.gif)

### To Reproduce

You can check live website at https://betzerra.com/about/

### Technical details:

* Ghost Version: 3.0.2
* Node Version:
* Browser/OS: Safari & Chrome / macOS
* Database: mySQL

**Comment by michaeleverson** [comment]
I see this issue too in Firefox Developer Edition 71.0b6

**Comment by ringleader3** [comment]
I just noticed this too, the white background and the fact that the title gets lost makes the dark mode when using pages somewhat unusable

**Comment by docherty** [comment]
This is fixed by this commit: https://github.com/TryGhost/Casper/commit/a66beb4e1044210f452cc0bda685631b500435f4

It's just an additional definition in screen.css at roughly line 2849 so the block becomes:

```
    .site-main,
    .post-template .site-main,
    .page-template .site-main {
        background: var(--darkmode);
    }
```

**Comment by betzerra** [comment]
Thank you @docherty !
