### ISSUE TITLE
No Spaces between the Navigation and Page content

### ISSUE THREAD

**Issue by mskian** [TryGhost/Casper#654]
No Spaces between the Navigation and Page content Author and Tag page

Example

<img src="https://user-images.githubusercontent.com/10300271/67850192-e8d6c480-fb2d-11e9-942e-ad5d8b2999d5.png" width="200" alt="lyra theme">

Same issue on tag page too

**Comment by peterzimon** [comment]
Fixed with https://github.com/TryGhost/Lyra/commit/e94daab78777a439ab310d70efd7172d9cc4a321
(The issue wasn't present on Casper, only on [Lyra](https://github.com/TryGhost/Lyra/))
