### ISSUE TITLE
Dark Mode 3.0.2

### ISSUE THREAD

**Issue by rolxhdz** [TryGhost/Casper#655]
I upgraded to 3.0.2 but in dark mode there are some borders on pages and tables continue with glow.
![Capture1](https://user-images.githubusercontent.com/8505040/68398646-aff4ac00-013a-11ea-8f05-06ccb042368c.PNG)
![Capture2](https://user-images.githubusercontent.com/8505040/68398657-b4b96000-013a-11ea-9cf2-852f58397877.PNG)

* Ghost Version: 3.0.2
* Browser/OS: Chrome, Safari

**Comment by docherty** [comment]
This is fixed by this comit: https://github.com/TryGhost/Casper/commit/a66beb4e1044210f452cc0bda685631b500435f4

It's just an additional definition in screen.css at roughly line 2849 so the block becomes:

```
    .site-main,
    .post-template .site-main,
    .page-template .site-main {
        background: var(--darkmode);
    }
```
