### ISSUE TITLE
Laggy/slow scroll (both Casper and Lyra themes effected)

### ISSUE THREAD

**Issue by casperbh96** [TryGhost/Casper#658]
There appears a laggy scroll in the themes for Ghost - tested on v3.0.

It's very hard to test on touchpad, especially Macbook touchpads since they are smooth. Test this with an external mouse, it's especially visible on Windows.

The lag appears on:

- Casper themes WITH members enabled
- Lyra themes WITH & WITHOUT members enabled. I tested both the plain Lyra theme and my own modified theme, the issue occurs on both.

**The bad workaround:** The lag seems to disappear on the Casper theme WHEN disabling members (not optimal).

**Update:** This problem is present on
- Windows 10, Chrome version 78 (but not on Firefox version 70)
- Ubuntu 18.04, Firefox version 70
- 1920x1080 monitor and 2560x1440 monitor
- External mice, tested with Razer, Logitech and BenQ Zowie

# Demonstration

Note that it's not exactly easy to see this issue, but you can kind of see it in the GIFs below. If you want a website to test, I suggest looking at [ML From Scratch](https://mlfromscratch.com/). The site is an example of laggy scroll with Lyra.

---

Casper with members disabled (smooth scroll, no issues):

![casper-no-subs](https://user-images.githubusercontent.com/27340033/68549543-57066b80-03f9-11ea-8c45-1f22bdf12387.gif)

Modified Lyra with Members enabled (laggy scroll):

![lyra-subs](https://user-images.githubusercontent.com/27340033/68549544-5a015c00-03f9-11ea-97dd-85e817db294c.gif)

Edit: 
Note: It's not just me having this issue. Many of my readers have told me that the scrolling on my site is horrible.

**Comment by samleez** [comment]
same issue with a gatsby theme` https://github.com/scttcper/gatsby-casper`

**Comment by samleez** [comment]
here's a laggy theme build around Casper:
https://gatsby-casper.netlify.com/

Same issue. Any ideas?

**Comment by samleez** [comment]
How in the world this issue didn't fix until now?

**Comment by oussama-HA** [comment]
I have the same issue

It most likely has to do with how they're doing the flow of the page and how intense it is on the GPU, there's pretty intense CSS.

When the page shrinks it changes to the alternate layout declared here:

https://github.com/TryGhost/Casper/blob/7c8cba7fabec47de9bed1b23b9dfac27fd9af008/assets/css/screen.css#L94

So I tried to play with `@media (min-width: 900px)` value but with no effect.

I noticed that when resizing the browser to a small window it starts scrolling smoothly.

Also, during my research I found out that `background-size:cover` has terrible performance and this starter uses a lot of this so I removed it and resized and compress the pictures but the lag is still there in high-resolution screens.

It's really annoying issue hope we can fix this together

**Comment by FarazPatankar** [comment]
I have experienced this issue as well. A bigger issue I am facing and have had my users report is the broken-ish fonts on Android devices. I checked the blog linked by @casperbh96 and the issue exists there as well.

![Uploading ghost-ss.jpg…](Broken Fonts)

If you look closely at the screenshot, you can see it. Especially on the subscribe button. Could someone please shed some light on why this happens and how we could go about fixing it?

Thanks!

**Comment by oussama-HA** [comment]
@FarazPatankar it's really really weird issue because, I noticed that the theme work great in firefox, brave, and chrome canary version 80, also chrome beta version 79. But when I tried it in another machines with different monitor resolutions it worked just fine with no lagging.

Hope some developers will work on this issue soon.

Thanks

**Comment by casperbh96** [comment]
@FarazPatankar @oussama-HA i added an update! It seems this is almost a universal problem.

**Update:** This problem is present on
- Windows 10, Chrome version 78 (but not on Firefox version 70)
- Ubuntu 18.04, Firefox version 70
- 1920x1080 monitor and 2560x1440 monitor
- External mice, tested with Razer, Logitech and BenQ Zowie

**Comment by oussama-HA** [comment]
@casperbh96 Same for me, the problem is present on high resolution monitors with a specific chrome version (official build 78) the same issue acquire on Opera too.

**Comment by casperbh96** [comment]
I have identified the code that is the problem for this issue.

**Casper theme with no modifications in default.hbs at line 44**. It's the if-statement. If you remove the whole thing, the laggy scroll disappears. I will investigate further and try to come up with a fix :)

```hbs
{{#if @labs.members}}
    <div class="subscribe-success-message">
        <a class="subscribe-close" href="javascript:;"></a>
        You've successfully subscribed to {{@site.title}}!
    </div>

    <div id="subscribe" class="subscribe-overlay">
        <a class="subscribe-close" href="#"></a>
        <div class="subscribe-overlay-content">
            {{#if @site.logo}}
                <img class="subscribe-overlay-logo" src="{{@site.logo}}" alt="{{@site.title}}" />
            {{/if}}
            <div class="subscribe-form">
                <h1 class="subscribe-overlay-title">Subscribe to {{@site.title}}</h1>
                <p class="subscribe-overlay-description">Stay up to date! Get all the latest & greatest posts delivered straight to your inbox</p>
                <form data-members-form="subscribe">
                    <div class="form-group">
                        <input class="subscribe-email" data-members-email placeholder="youremail@example.com"
                            autocomplete="false" />
                        <button class="button primary" type="submit">
                            <span class="button-content">Subscribe</span>
                            <span class="button-loader">{{> "icons/loader"}}</span>
                        </button>
                    </div>
                    <div class="message-success">
                        <strong>Great!</strong> Check your inbox and click the link to confirm your subscription.
                    </div>
                    <div class="message-error">
                        Please enter a valid email address!
                    </div>
                </form>
            </div>
        </div>
    </div>
    {{/if}}
```

**Comment by casperbh96** [comment]
This issue is fixed and can be closed if the PR https://github.com/TryGhost/Casper/pull/660 goes through.
