### ISSUE TITLE
Share this post optionality

### ISSUE THREAD

**Issue by SovereignNode** [TryGhost/Casper#672]
The Casper theme used to have a 'Share this post' section for Twitter and Facebook inside the floating-header.hbs file. Unfortunately, with 3.0, this feature has been removed. I've tried to find ways to re-introduce it again but it doesn't really work.

Can this be introduced again in the site-nav bar when scrolling down in a post view? The right section has "social icons" and "subscribe button" that could be replaced imo.

So far, I've found no good alternative to have some sort of share buttons in my posts.

Curious to hear your thoughts.
Regards,

**Comment by kevinansfield** [comment]
If you need help modifying the theme to your needs please use the [forum](https://forum.ghost.org)  🙂
