### ISSUE TITLE
post-card-content alignment issue

### ISSUE THREAD

**Issue by makeitcount** [TryGhost/Casper#675]
On home page `post-card-content` is not consistent in design. It was working fine in earlier versions of casper but not in 3.x

Ideally if there are two cards in one row then items such as `author list` of both card should align horizontally, similarly title and images should also align.

One solution could be 
```
post-card-content-link : {
     flex-grow: 1;
}
```
This aligns author list but then if one card has image `post-card-image-link` and other card does not. The item `post-card-image-link` is missing in the later one. 

So the solution could be to add `post-card-image-link` irrespective if image is there or not. Same thing for `tags`.

### Steps to Reproduce
 
 1. Publish two posts. One with title image and another one without image. Also have different title length for both. 
 2. Go to home page now and check the two post card items alignment

### Technical details

* Casper Version: 3.0.5
* Ghost Version: 3.x
* Browser Version: Chrome - Latest
* OS Version: Ubuntu

**Comment by minimaluminium** [comment]
Hey, sorry about the delay! Aligning things is important visually, but aligning everything wouldn't always be the best solution.

Here is how Casper works by default:
![Screen Shot 2020-10-08 at 10 56 10 AM](https://user-images.githubusercontent.com/1418797/95409968-610c5380-0955-11eb-8b95-a95608e8c588.png)

.vs the one everything is aligned
![Screen Shot 2020-10-08 at 10 59 26 AM](https://user-images.githubusercontent.com/1418797/95409975-64074400-0955-11eb-92a3-f8ce7799bdaa.png)

There are lots of wasted white space compared to the default one. If you prefer the latter one, you're always welcome to customize your theme as instructed [here](https://github.com/TryGhost/Casper#development). Or if the change is minor, you can also insert the CSS changes in `Code injection > Site Header` field.
