### ISSUE TITLE
Cannot resolve '--white' custom property

### ISSUE THREAD

**Issue by gaplo917** [TryGhost/Casper#676]
https://github.com/TryGhost/Casper/blob/aec67d8b5fea8116d9f7baaf32adc51d75118829/assets/css/screen.css#L2168

I think it is a mistake

### Technical details

* Casper Version: 3.0.5
* Ghost Version: N/A
* Browser Version: N/A
* OS Version: N/A

**Comment by peterzimon** [comment]
Fixed with https://github.com/TryGhost/Casper/commit/09d701c4bc387e6e8a44d999c57e773f08c0a571
