### ISSUE TITLE
Version 3.0.5 broke the navigation bar *and* the title header.

### ISSUE THREAD

**Issue by JaneJeon** [TryGhost/Casper#677]
As noted in here - https://github.com/SNathJr/ghost-on-heroku/pull/41#issue-364573354 - Casper v3.0.4 works completely fine, but anything beyond (v3.0.5 and v3.0.6) breaks the navigation bar (the one on the top) and the title header (the one that shows up when you scroll the article down).

So I'm guessing something got messed up when @peterzimon "added" secondary navigation in #664.

Can you please fix this? Thank you.

P.S. is there any sort of testing you can do for the themes? This is not the first time a minor theme upgrade _broke_ a theme. This happened with Casper v3.0.5 and London v1.0.1 as well (see https://github.com/TryGhost/London/issues/24)

**Comment by JohnONolan** [comment]
Works fine here. If you're going to open an issue next time please use the provided template and give actual details of what you think is broken. "it breaks" is not remotely useful or anything that can be acted on.

If you have great ideas for tests, feel free to open a PR - this is an _open source project_, not a support desk.
