### ISSUE TITLE
Use jsdelivr to improve jQuery load time

### ISSUE THREAD

**Issue by manyang901** [TryGhost/Casper#681]
### Technical details

* Casper Version: 3.0.7
* Ghost Version:
* Browser Version:
* OS Version:

### Content
I strongly suggest you use jsdelivr as js library CDN.
My website visitors are mainly from China, and only jsdelivr provides China pops. The original code.jquery.com has poor stability in China.
Please consider changing one line in default.hbs to help improve jQuery load time.

**Comment by JohnONolan** [comment]
You're very welcome to change the jQuery reference for your install!
