### ISSUE TITLE
Dev server does not tell where to connect

### ISSUE THREAD

**Issue by miohtama** [TryGhost/Casper#683]
### Screenshot

The dev server does not tell where to connect. Neither does README. The user is puzzled.

<img width="510" alt="image" src="https://user-images.githubusercontent.com/49922/74612791-ed3ce280-5108-11ea-9ec9-b8b4e8d73ad5.png">

### Steps to Reproduce
 
 1. `yarn install`
 2. `yarn dev`

### Technical details

* Casper Version: 3.0.7
* OS Version: macOS

**Comment by miohtama** [comment]
I suggest add a `console.log` or cover this in README if it is not straightforward to hook in the gulp server.

**Comment by kevinansfield** [comment]
@miohtama the gulp script does not serve anything except a livereload script, otherwise it's only a file watcher.

If you're looking for info on Ghost theme development everything should be in our docs https://ghost.org/docs/api/v3/handlebars-themes/

**Comment by miohtama** [comment]
@kevinansfield Thank you! It was little bit misleading as Casper theme was linked from a "how to develop themes" article.
