### ISSUE TITLE
'Subscribe' button not visible on mobile

### ISSUE THREAD

**Issue by maurobanze** [TryGhost/Casper#686]
1. The subscribe button on the nav bar is not visible on mobile, see screenshot for example. I can only see it on desktop. As a workaround, I tried appending '/#subscribe' to my domain name, which results in maurobanze.com/#subscribe, since I noticed that this is the link that gives access to the subscribe popup. 
2. However, opening that link on mobile results in a page that was not designed for mobile, which looks bad (see second screenshot). 

Therefore, I'm left with no good option for my mobile readers to subscribe. I should note that the 'subscribe box' at the end of an article is visible on mobile too, which is good. 

Thank you.

### Screenshots
![photo5949725905347785266](https://user-images.githubusercontent.com/6880879/75095774-468d9180-55a1-11ea-9bc4-31bd53410d3a.jpg)

![photo5949725905347785267](https://user-images.githubusercontent.com/6880879/75095921-89039e00-55a2-11ea-96dc-01a4c1b8210d.jpg)

### Steps to Reproduce
 
 1. Open site on mobile
 2. Notice that the homepage does not have a subscribe button anywhere (it's on navbar on desktop)

1. Open site.com/#subscribe on mobile
2. Notice that layout is all messed up, as if it had not been designed to be displayed on mobile

### Technical details

* Casper Version: 3.0.7
* Ghost Version: Ghost Pro, couldn't find version number
* Browser Version: Chrome mobile 80.0.3987.117
* OS Version: Android 9

**Comment by ravinayag** [comment]
I echo same..

**Comment by ErisDS** [comment]
Acknowledged that this is a bug, however the members code in Casper is about to be overhauled, so we're not gonna fix this right now 🙂
