### ISSUE TITLE
Typo on demo page

### ISSUE THREAD

**Issue by llb1026** [TryGhost/Casper#697]
Hello,

Just found a very simple typo on the demo site.

### Screenshot

<img width="1098" alt="스크린샷 2020-03-31 오후 9 46 01" src="https://user-images.githubusercontent.com/16914674/78028054-587d0400-7399-11ea-93af-e6578f0b4328.png">

### Steps to Reproduce
 
 1. Go to https://demo.ghost.io/themes/
 2. There's a typo in the 'Theme development' section.

### Technical details
_I'll leave them blank_
* Casper Version:
* Ghost Version:
* Browser Version:
* OS Version:

**Comment by daniellockyer** [comment]
Fixed - thanks!
