### ISSUE TITLE
"You've successfully subscribed" notification able to be seen by scrolling up

### ISSUE THREAD

**Issue by fjah** [TryGhost/Casper#704]
### Screenshot

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/24289784/79319740-a26cfa80-7f00-11ea-9b03-a1fd9ad30fcc.png">

### Steps to Reproduce
 
 1. Visit either the home page or a post;
 2. Scroll up to trigger the "bounce" motion (only works on Safari, I believe).

### Technical details

* Casper Version: 3.0.11
* Ghost Version: 3.12.1
* Browser Version: Safari 13.1
* OS Version: macOS 10.14 Catalina

**Comment by ErisDS** [comment]
Acknowledged that this is a bug, however the members code in Casper is about to be overhauled, so we're not gonna fix this right now 🙂
