### ISSUE TITLE
The blog logo doesn't appear in front page if the SVG doesn't integrate width and height properties (fw)

### ISSUE THREAD

**Issue by DarthJahus** [TryGhost/Casper#706]
Redirected from [TryGhost/Ghost](https://github.com/TryGhost/Ghost/issues/11734)

### Issue Summary

The SVG file set as "Publication logo" will have null-size in the front page if the SVG doesn't contain `width` and `height` properties (Adobe Illustrator default export doesn't include them).

### To Reproduce

0. Export an illustration as SVG from Adobe Illustrator (or other), make sure it doesn't have `width` and `height`
1. Set a SVG file as Publication logo
2. Check the front page

Example of SVG header:
```
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 24.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg version="1.1" id="Calque_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 604 204" style="enable-background:new 0 0 604 204;" xml:space="preserve">
```

### More details

If you manually add `width` and `height` to the SVG file, the logo appears correctly.

Example of SVG header:
```
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 24.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg version="1.1" id="Calque_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 604 204" style="enable-background:new 0 0 604 204;" xml:space="preserve">
```

### Technical details:

* Ghost Version: 3.13.1
* Casper version: 3.0.12

**Comment by daviddarnes** [comment]
Hey @DarthJahus, are you making sure to check the "responsive" option before exporting your SVG in Illustrator?

**Comment by JohnONolan** [comment]
SVGs will definitely need to be prepared properly for use on the web, this is not a bug in Casper :)
