### ISSUE TITLE
Replace feedly.com url with blog's rss feed?

### ISSUE THREAD

**Issue by KopfKrieg** [TryGhost/Casper#707]
In the file `partials/site-nav.hbs`, on line 32, the default feed url points to feedly.com (`https://feedly.com/i/subscription/feed/{{@site.url}}/rss/`) instead of just using the blog's rss feed (`{{@site.url}}/rss/`), and I'm asking myself if there's a reason for it, and if we could change that.

A few of my followers (and myself included) were surprised the feed url doesn't actually point to the blog's feed, which is also a problem privacy-wise.

If it's okay I'll open a pull request with the according change. Or maybe we could discuss why it points to feedly.com instead of just the blog's feed url.

### Technical details

* Casper Version: 3.0.12
* Ghost Version: 3.13.3

**Comment by JohnONolan** [comment]
Most people have no idea what an RSS feed is, providing a feedly link is a utility which makes it easy to understand how to subscribe to a site.

You can freely change this any time in your own theme if you would prefer to point directly to the feed itself.

**Comment by curia-damiano** [comment]
I would expect that you play nice by default.
Eventually if I will think that my readers are dumb, only at that point I will need to customize the theme to change the RSS feed.

**Comment by JohnONolan** [comment]
We do play nice by default. We place nice for the 99% of people who have no idea what RSS is - "99%" is the default. If you want something different: make your own theme.
