### ISSUE TITLE
load jquery fitvids from local

### ISSUE THREAD

**Issue by jeyca** [TryGhost/Casper#710]
Hey, Iam using casper 3.0.12 and wanted to remove the external loading from jquery and load it from the server itself. There I found in the source code: 

```
{{!-- jQuery, required for fitvids --}}
    <script
        src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
        crossorigin="anonymous">
    </script>
```

and a file called `jquery.fitvids.js` in `~/ghost/content/themes/casper/assets/js/lib`.

So I wonder, if the original complete jquery is necessary at all? Or if this js-file is enough to replace the used functions? I could not find any link to the js-file in the html code, so it looks like it is not used yet.

**Comment by JohnONolan** [comment]
This isn't a bug - if you need help with theming, please feel free to post on the Ghost forum -- https://forum.ghost.org -- where there are lots of other developers also working on themes!
