### ISSUE TITLE
How to translate?

### ISSUE THREAD

**Issue by zhihuiyuze** [TryGhost/Casper#720]
According to https://ghost.org/docs/api/v3/handlebars-themes/helpers/translate/ I add /var/www/ghost/content/themes/casper/locales/zh.json But the tutorial tip requires pagination.hbs and navigation.hbs . but it does not exist. I set the language to zh and restart the website and it is invalid

```
{
    "Back": "返回",
    "Newer Posts": "更新的文章",
    "Older Posts": "更旧的文章",
    "Page {page} of {pages}": "第{page}页，共{pages}页",
    "Subscribe": "订阅",
    "Subscribe to {blogtitle}": "订阅{blogtitle}",
    "Subscribed!": "已经订阅！",
    "with the email address": "在此邮箱",
    "Your email address": "你的email地址",
    "You’ve successfully subscribed to": "你已经成功订阅了",
    "A collection of posts": "文章集合",
    "A collection of 1 post": "共1篇文章",
    "A collection of % posts": "共%篇文章",
    "Get the latest posts delivered right to your inbox": "最新文章直达邮箱",
    "Go to the front page": "转到首页",
    "Latest Posts": "最新文章",
    "Message:": "Message:",
    "<a href='{url}'>More posts</a> by {name}": "<a href='{url}'>More posts</a> by {name}",
    "No posts": "没有文章",
    " (Page %)": " (第%页)",
    "Read More": "阅读更多",
    "Read <a href='{url}'>more posts</a> by this author": "阅读此作者的<a href='{url}'>更多文章</a>",
    "Ref:": "Ref:",
    "See all % posts": "查看所有%篇文章",
    "Share this": "分享",
    "Stay up to date! Get all the latest & greatest posts delivered straight to your inbox": "保持更新！所有最新最好的文章全部送进你的邮箱",
    "This post was a collaboration between": "这篇文章是",
    "youremail@example.com": "youremail@example.com",
    "1 post": "1 篇文章",
    "% posts": "% 篇文章",
    "1 min read": "一分钟阅读",
    "% min read": "% 分钟阅读"
```

**Comment by daviddarnes** [comment]
Hey @zhihuiyuze,
You need to create those templates in your copy of the theme. Take a look at this section where it links to the pagination and navigation template files that you can copy and add the translations https://ghost.org/docs/api/v3/handlebars-themes/helpers/translate/#4-ensure-templates-exist

**Comment by zhihuiyuze** [comment]
You mean, I need to download the theme to mytheme file?

David Darnes <notifications@github.com> 于 2020年5月30日周六 下午3:56写道：

**Comment by daviddarnes** [comment]
@zhihuiyuze You need to copy those files, pagination.hbs and navigation.hbs into your own theme to overwrite the default 😊
