### ISSUE TITLE
[Question] Removal of floating header? Where does the functionality go?

### ISSUE THREAD

**Issue by XapaJIaMnu** [TryGhost/Casper#723]
Hey,

I recently updated my ghost blog from 2.16 to 3.18. I have a custom theme that is based on casper and I updated it with casper’s latest changes. I noticed that partials/floating-header.hbs has been removed on October 21 2019, Here’s the git commit: https://github.com/TryGhost/Casper/commit/b51dd8ce22cfbf4c8b833f2bdf0d0793e31a5d26 

The floating panel used to have share links for twitter and facebook, as you scroll the blog post. The current casper version (looking here: https://demo.ghost.io/i-have-a-dream/ )no longer has that, at least in my default setup? The facebook/twitter buttons are now static. Have I messed up something in the migration, or is it the case that this functionality has been removed and if I want it, I have to restore it myself?

Cheers,

Nick

**Comment by JohnONolan** [comment]
This is not a bug :) if you need help building your theme, please post on forum.ghost.org

**Comment by doncabreraphone** [comment]
I've been searching for this answer for almost two hours, so it's not a bug but a feature that is no longer there. Then why do I see the floating header when I see the Casper example on the Select Theme?

It led me to think I had done something wrong with my installation. Please add a disclaimer on the main readme page here on GitHub stating that the current Casper theme is not the same one that we see on the Select Theme section.
