### ISSUE TITLE
Any chance we could only include jQuery + fitVids if they're used?

### ISSUE THREAD

**Issue by mhansen** [TryGhost/Casper#736]
### Screenshot

![image](https://user-images.githubusercontent.com/105529/93202178-a34ad680-f795-11ea-8b39-e6cace086939.png)

### Steps to Reproduce
 
 1. Visit https://www.markhansen.co.nz/
 2. Open in Lighthouse tab in Chrome Dev Tools
 3. Note there are no videos on the screen
 4. Observe that jQuery (a pretty big JS library) is loaded, parsed, and executed, seemingly just for `jquery.fitVids.js`: https://github.com/davatron5000/FitVids.js/blob/master/jquery.fitvids.js, for dynamic video sizing.

### Expected Behaviour

Option 1: Only pay the cost of jQuery + fitVids.js if there's actually a video shown
Option 2: Rewrite fitVids.js to drop the dependency on jQuery. fitVids is using extremely basic features of jQuery to look for descendants 

```
      var $allVideos = $(this).find(selectors.join(','));
```
this could be replaced with `element.querySelectorAll(selectors.join(','));` I think?

then a bit of attribute twiddling, which should work in vanilla JS?

### Technical details

* Casper Version: 3.1.0
* Ghost Version: latest (the managed one)
* Browser Version: Chrome
* OS Version: macOS

**Comment by daviddarnes** [comment]
Looks like this issue was already addressed in https://github.com/TryGhost/Casper/pull/438?

**Comment by minimaluminium** [comment]
jQuery is also used on other parts of the theme like author popup on hovering, subscribe notifications and sticky navigation as well. Also as discussed in the PR @daviddarnes pointed out, dropping jQuery will be a major breaking change for a lot of sites.
