### ISSUE TITLE
[RFE] Dark/Light Mode Toggle

### ISSUE THREAD

**Issue by dinosaw** [TryGhost/Casper#744]
Hello,

I'd like to request the option so that the end-user can choose whether or not which color theme they would prefer when reading a blog using the Casper theme. A good example would be the [Dawn](https://dawn.ghost.io/) theme that by default respects the color of the OS, but then also allows the user to toggle between all of the options (Dark/Light/System).

![Dawn](https://i.imgur.com/Zr7d90K.gif)

Would this be a possibility?

**Comment by minimaluminium** [comment]
Hey @dinosaw, we ask that you please do not use GitHub for support or feature requests 🙂 
We use GitHub solely for bug-tracking and on-going feature development.

**Comment by dinosaw** [comment]
Understood. Where would be the best place to communicate such a request?

**Comment by minimaluminium** [comment]
The best place would be [Ghost Forum](https://forum.ghost.org/) 🙂
