### ISSUE TITLE
HTML-card link new line bug

### ISSUE THREAD

**Issue by hamzamu** [TryGhost/Casper#748]
The links inside HTML-card link are awfully separated from the paragraph content. I tried to override the CSS style, but it didn't work. 

In the screenshot you can see an example in two paragraphs, the upper is for the HTML-card, the second is for a normal text. 

### Screenshot

![Screenshot from 2021-01-19 09-32-12](https://user-images.githubusercontent.com/340579/104996625-427c2500-5a39-11eb-82ac-5bb16da85904.png)

### Steps to Reproduce
 
 1. Create an HTML card
 2. Add a link <a> </a> to the HTML card content 
 

### Technical details
The links inside the HTML-card link are created as new separate lines with the latest Casper version. 

* Casper Version: Version 3.1.2
* Ghost Version: Version 3.40.5 
* Browser Version: Chrome Version 87.0.4280.88
* OS Version: Linux Solus 4.1

**Comment by minimaluminium** [comment]
Hey @hamzamu, you should wrap the HTML card content in a wrapper element. For example,

```html
<p>
    Some text and <a href="#">link</a> here.
</p>
```

Otherwise, the link would be considered as a direct child of `.post-content` element, and get flexbox styles.

**Comment by hamzamu** [comment]
I am sorry, but does that mean, I have to manually update all my HTML-cards (~400) because of a CSS mistake?

**Comment by minimaluminium** [comment]
This is not a CSS mistake. All direct children of the `.post-content` element are block elements, and they're stacked vertically with `display: flex`. If you add inline elements as direct children, they will also be stacked vertically.

If it's impossible on your end, you can override the CSS like below.

```css
.post-content {
    display: block;
}
```

**Comment by hamzamu** [comment]
Already did that. Thank you

> This is not a CSS mistake. All direct children of the `.post-content` element are block elements, and they're stacked vertically with `display: flex`. If you add inline elements as direct children, they will also be stacked vertically.
> 
> If it's impossible on your end, you can override the CSS like below.
> 
> ```css
> .post-content {
>     display: block;
> }
> ```
