### ISSUE TITLE
Change Subscribe button to Account button for logged in user?

### ISSUE THREAD

**Issue by dingran** [TryGhost/Casper#751]
Perhaps for this

https://github.com/TryGhost/Casper/blob/854880747d74b53d01474fd7082d464f0fe7cd1d/partials/site-nav.hbs#L37

we should do something like this, to change Subscribe button to Account button for logged in user?

```html  
          {{#if @member}}
                <a class="subscribe-button" href="#/portal/account">Account</a>
            {{else}}
                <a class="subscribe-button" href="#subscribe">Subscribe</a>
            {{/if}}
````

**Comment by minimaluminium** [comment]
Hey @dingran, you're right! Fixed in https://github.com/TryGhost/Casper/commit/52f763859a9585d02d1895a636047dfe76cb9ac5
