### ISSUE TITLE
{{!< default}} syntax

### ISSUE THREAD

**Issue by dingran** [TryGhost/Casper#754]
Hey there, this is more of a question than an issue

I'm pretty new to handle bar, I'm curious where does this `{{!< default}}` syntax come from? (I didn't find it in the official handlebar site. How was it supported?

E.g.
https://github.com/TryGhost/Casper/blob/7e3e891338b3541ca5cc10e320e9fac15838532f/page.hbs#L1-L3

Thanks!

**Comment by minimaluminium** [comment]
Hey @dingran, Ghost uses [express-hbs](https://github.com/TryGhost/Ghost/blob/58be6d23db72ff1c216513c35d88d40d4fdbe14a/package.json#L89) as the template engine, and `{{!< LAYOUT}}` is a special syntax of the library for layouts. You can read more about this [here](https://github.com/TryGhost/express-hbs#layouts).
