### ISSUE TITLE
How to integrate it with Netlify CMS

### ISSUE THREAD

**Issue by talmax1124** [TryGhost/Casper#757]
Hello, I do not want to use the ghost platform due to its high pricepoint. I am hosting it in Netlify, but want to know how to use the Netlify CMS to post content.

**Comment by minimaluminium** [comment]
Hey 👋 . We ask that you please do not use GitHub for support or feature requests 😄. We use GitHub solely for bug-tracking and on-going feature development.

Our [forum](https://forum.ghost.org/) is a great place to get community support, plus it helps create a central location for searching problems/solutions.

Thanks!
