### ISSUE TITLE
[Change Request] Stop using Google Font API.

### ISSUE THREAD

**Issue by SushiDude** [TryGhost/Casper#77]
Casper is currently using the [Google Font API](https://developers.google.com/fonts/) in order to retrieve fonts. Due to the fact that these fonts are hosted on Google's servers, this presents a privacy risk to all viewers of blogs that use this theme and could cause additional downtime.

The fonts in question, [Open Sans](https://www.google.com/fonts/specimen/Open+Sans) and [Noto Serif](https://www.google.com/fonts/specimen/Noto+Serif), are both under the [Apache License version 2.0](https://www.apache.org/licenses/LICENSE-2.0.html) meaning that it would be acceptable to include them with Casper.

**Comment by ott** [comment]
It should be noted that widely used web browsers send a `Referer` header with the URL of the site that embedded the resource. So it becomes possible to profile users. The short caching interval of fonts.googleapis.com also contributes to this.

@JohnONolan claims that only a subset of users care about their privacy. There is evidence that this is not the case when asking directly. I think most users are not aware that a site that they visit reveals the fact that they visited the site to Google. I doubt that when being presented with the choice whether they want to either wait a short moment longer on the first site load or revealing to Google that they visited the site and what article they read, the majority of users would choose Google.

I also think that contrary to how it is presented here either embedding the external resource or not is a political statement.

I would also like to ask @aigarsdz to publish the mentioned information or send it to me. If it can "be considered public anyway", I would like to see it. Information in this case means detailed information about your browser, computer and your browser history. At the wrong time and in the wrong parts of the world that would have been enough to justify your death.

**Comment by aigarsdz** [comment]
@ott I'm sorry that it took so long to reply. I get your point and a lot has changed in 2 years since i posted that comment, however, i wanted to note that people who want to keep their browsing private take extra steps to make sure none of this information gets shared. If you browse the internet the regular way it is really hard to avoid that.
