### ISSUE TITLE
Remove SUBSCRIBE from the navigation bar

### ISSUE THREAD

**Issue by goranche** [TryGhost/Casper#775]
Even though I've disabled the "Show Portal button" in the settings, the SUBSCRIBE button is still shown in the navigation bar.

I'd expect it to not be shown when the "Show Portal button" is disabled.

**Comment by goranche** [comment]
After trying to find where this happens, I've found the same issue in `post.hbs`. Only a check for `@member` is done, not for the setting.

**Comment by goranche** [comment]
For future reference, the location this is rendered is [here in default.hbs](https://github.com/TryGhost/Casper/blob/b16671d8a779f74b62494e674275015955a63723/default.hbs#L51-L55), and [in post.hbs](https://github.com/TryGhost/Casper/blob/b16671d8a779f74b62494e674275015955a63723/post.hbs#L81-L93)...

I don't (yet) know how to check if the "Show Portal button" setting is turned off... 😊  🙈

**Comment by minimaluminium** [comment]
Hi @goranche,

What "Show Portal button" toggle does is hide the floating Portal button on the bottom right of screen. To hide the button on the navigation bar, use this CSS. The easiest way would be adding the CSS in "Code injection" field.

```html
<style>
    a.gh-head-button {
        display: none;
    }
</style>
```

**Comment by goranche** [comment]
> What "Show Portal button" toggle does is hide the floating Portal button on the bottom right of screen. To hide the button on the navigation bar, use this CSS. The easiest way would be adding the CSS in "Code injection" field.

Thanks for this, although I have to say this sounds more like a crutch... Wouldn't it be better to have a setting to remove all references to "the portal" for those of us who don't use it?

**Comment by minimaluminium** [comment]
If you have a feature request/suggestion, use our forum's [Ideas category](https://forum.ghost.org/c/ideas/5)

We ask that you please do not use GitHub for support or feature requests 😄. We use GitHub solely for bug-tracking and on-going feature development.

Our [forum](https://forum.ghost.org/) is a great place to get community support, plus it helps create a central location for searching problems/solutions.

Thanks!
