### ISSUE TITLE
Headings and captions in darkmode are invisible

### ISSUE THREAD

**Issue by liveforeverx** [TryGhost/Casper#780]
As mentioned in dark mode issue: https://github.com/TryGhost/Casper/issues/774#issuecomment-801436912

After upgrading to the new ghost, the links in dark-mode are invisible. So, I added a link (you can't see, but it is there):

<img width="1375" alt="Screenshot 2021-03-18 at 17 35 17" src="https://user-images.githubusercontent.com/660306/111662655-67f69680-8810-11eb-8bcf-565b5d0de150.png">

Because it is black color link on black:

<img width="1232" alt="Screenshot 2021-03-18 at 17 35 26" src="https://user-images.githubusercontent.com/660306/111662674-6b8a1d80-8810-11eb-991e-a59d5de4206e.png">

**Comment by kesenwang** [comment]
Also just to add to this the tag CSS should be modified as well as it’s very hard to see with the current HEX.

**Comment by JohnONolan** [comment]
If you're upgrading from a 3.x site and `brand color` is unset, resulting in darkgrey as a fallback. To resolve this, you can choose and set a color under `Settings > Branding`

![image](https://user-images.githubusercontent.com/120485/111668777-792dac00-87ec-11eb-8f0d-fab613ddb8d1.png)

This is not related to the Casper theme

**Comment by liveforeverx** [comment]
@JohnONolan Thank you! 

Is it possible to set different colors for accent and links?

Any color, which isn't too contrasts from dark mode, isn't recognisable.

<img width="346" alt="Screenshot 2021-03-18 at 18 56 28" src="https://user-images.githubusercontent.com/660306/111674951-e0fbeb00-881c-11eb-9753-05bae5cdc617.png">

And any recognisable color as links, simply too contrast and too bright for dark mode... I can't find something, what is less contrast and visible with links.

**Comment by liveforeverx** [comment]
@JohnONolan 
The same problem exists for headers

**Comment by liveforeverx** [comment]
You do not see a header @JohnONolan , but it is there:

<img width="875" alt="Screenshot 2021-03-18 at 19 13 57" src="https://user-images.githubusercontent.com/660306/111676085-18b76280-881e-11eb-9714-eae8a376d1bf.png">

<img width="603" alt="Screenshot 2021-03-18 at 19 14 07" src="https://user-images.githubusercontent.com/660306/111676147-2ec52300-881e-11eb-8adf-238a96effe4d.png">

**Comment by liveforeverx** [comment]
Finding accent color is very hard.. Because if it enough bright for links, you header is too bright for dark mode (but links are recognisable).

For example this:

<img width="359" alt="Screenshot 2021-03-18 at 19 17 34" src="https://user-images.githubusercontent.com/660306/111676804-d6daec00-881e-11eb-8349-31366ece4319.png">

If the color shouldn't be too contrast for dark mode (for header, so that header isn't super contrasted and bright), than links are pretty dark and it isn't easy to see them:

<img width="320" alt="Screenshot 2021-03-18 at 19 18 04" src="https://user-images.githubusercontent.com/660306/111676815-d93d4600-881e-11eb-97ca-f38ec5f0242a.png">

So, it very hard to find sweet spot, where header is not bright and very contrast to dark mode, but still recognisable.

@JohnONolan Should I open separate issues for this?

**Comment by JohnONolan** [comment]
If the theme isn't suited to the color you want to use - you're very welcome to modify the theme to your needs - it is, after all : open source. Theme customisation is not a bug.

**Comment by liveforeverx** [comment]
@JohnONolan Okay, I understand for color accent. But are invisible headings (H in editor) in dark mode isn't a bug?

**Comment by JohnONolan** [comment]
Oh - I missed the part about headings, I apologise, that's definitely a bug and my mistake for not reading carefully enough.

@minimaluminium would you be able to help fix heading inside content in dark mode, and also card-captions, both of which are black but should be white

**Comment by minimaluminium** [comment]
Fixed the issue in https://github.com/TryGhost/Casper/commit/d9e9e097cdfaab23c7ee6fe6514c36a6f2957041. @liveforeverx Thanks for giving detailed feedback!

### Headings

![Screen Shot 2021-03-19 at 2 13 57 PM](https://user-images.githubusercontent.com/1418797/111739264-bc0b8480-88bd-11eb-8240-fed2daae1b25.png)

### Caption

![Screen Shot 2021-03-19 at 2 14 07 PM](https://user-images.githubusercontent.com/1418797/111739273-bf9f0b80-88bd-11eb-956b-6f29aeac39f1.png)

**Comment by kesenwang** [comment]
> If you're upgrading from a 3.x site and `brand color` is unset, resulting in darkgrey as a fallback. To resolve this, you can choose and set a color under `Settings > Branding`
> 
> ![image](https://user-images.githubusercontent.com/120485/111668777-792dac00-87ec-11eb-8f0d-fab613ddb8d1.png)
> 
> This is not related to the Casper theme

Huh, this literally does nothing for links or headers still using grey, lol.

**Comment by kesenwang** [comment]
> If the theme isn't suited to the color you want to use - you're very welcome to modify the theme to your needs - it is, after all : open source. Theme customisation is not a bug.

Yeah, nah. If dark/light mode was touted as a feature and then without notice revoked from users creating a whole bunch of cosmetic issues and then suggested tweaking CSS for users that are probably not fluent in CSS, then yeah, that definitely seems like a definition of a bug to me.

**Comment by JohnONolan** [comment]
This bug has already been fixed, there is a commit reference directly above your message - which you didn't bother to read before commenting on a closed issue.

You can take your "yeah, nah" elsewhere. If you're going to continue to be rude across multiple issues, you will not be welcome on any of our repositories. I suggest you read our [code of conduct](https://ghost.org/conduct/) before posting further.
