### ISSUE TITLE
How can I disable the 'Subscription' feature

### ISSUE THREAD

**Issue by paulosacramento** [TryGhost/Casper#782]
I don't intend to offer subscriptions, so I would like to make these 'SUBSCRIBE' buttons disappear everywhere.

**Comment by minimaluminium** [comment]
Hey @paulosacramento, 

The [solution](https://forum.ghost.org/t/ghost-4-0-really-terrible-for-personal-blog/20811/10) was already posted on our forum.

We ask that you please do not use GitHub for support or feature requests 😄. We use GitHub solely for bug-tracking and on-going feature development.

Our [forum](https://forum.ghost.org/) is a great place to get community support, plus it helps create a central location for searching problems/solutions.

Thanks!
