### ISSUE TITLE
Small images on posts not centered

### ISSUE THREAD

**Issue by brainandbrain** [TryGhost/Casper#786]
Already fixed on my custom version of the theme (fix below), so I can't show an example, but small images that are set in the post to "Wide" appear off-center on the page.

Fixed with auto margins to left and right:

`figure.kg-card.kg-image-card.kg-width-wide {
	margin-left: auto;
	margin-right: auto;
}`

**Comment by minimaluminium** [comment]
Thanks! This is now fixed in https://github.com/TryGhost/Casper/commit/816e1f608e07a57d521d1cf052fcc626c03fdeb5
