### ISSUE TITLE
Spacing between dot points 

### ISSUE THREAD

**Issue by MereCivilian** [TryGhost/Casper#787]
I recently updated to v4 and it seems that there is a bug related to spacing around dot points and numbered points. 

Please see image below:
<img width="821" alt="Screen Shot 2021-03-28 at 1 12 13 pm" src="https://user-images.githubusercontent.com/68980168/112740300-80f90780-8fc7-11eb-9d7b-c959fba0bf6e.png">

Source: https://merecivilian.com/morning-person/

Is this as intended?

**Comment by minimaluminium** [comment]
Thanks! This is now fixed in https://github.com/TryGhost/Casper/commit/0d49da97a25c4b521b1a9983d165bbafb7feb6a9
