### ISSUE TITLE
Large titles cause cards view to get disrupted

### ISSUE THREAD

**Issue by jessehouwing** [TryGhost/Casper#788]
One of my posts has a .NET namespace in the title. The posts box won't flow or truncate that, causing the infinite scroll to get disrupted.

![image](https://user-images.githubusercontent.com/4173387/113015575-f9a1c480-917d-11eb-9916-69431713196c.png)

https://user-images.githubusercontent.com/4173387/113015407-cfe89d80-917d-11eb-996b-511a0ad95ef2.mp4

**Comment by minimaluminium** [comment]
Thanks! Fixed in https://github.com/TryGhost/Casper/commit/6ac55407b3499786445a3d9a7c509ebfee319d68
