### ISSUE TITLE
Issues with Dark Mode and v4

### ISSUE THREAD

**Issue by jessehouwing** [TryGhost/Casper#789]
##Admin panel:
--

In the admin panel, the code highlights render some keywords black on black:

Dark-mode:
![image](https://user-images.githubusercontent.com/4173387/113016037-61f0a600-917e-11eb-8334-e2e4668c0d16.png)

Light-mode:
![image](https://user-images.githubusercontent.com/4173387/113016116-7339b280-917e-11eb-9b1a-d5685f52996f.png)

##Links with code in posts:
--

Stay light in dark mode:
Dark-mode:
![image](https://user-images.githubusercontent.com/4173387/113016487-d297c280-917e-11eb-97bc-5c61b54f609e.png)

Light-mode:
![image](https://user-images.githubusercontent.com/4173387/113016565-e6dbbf80-917e-11eb-8b00-82ad9cedae66.png)

##Border around Code snippets:
--

Way too low contrast around the box:

Dark-mode:
![image](https://user-images.githubusercontent.com/4173387/113016670-007d0700-917f-11eb-9034-bcf102d73d06.png)

Light-mode:
![image](https://user-images.githubusercontent.com/4173387/113016874-2e624b80-917f-11eb-9cda-4ca2b2de9cfb.png)

Interestingly, in light mode there are "white gaps" around the corners and edges:
![image](https://user-images.githubusercontent.com/4173387/113016970-48039300-917f-11eb-90ff-593f170a280e.png)

**Comment by minimaluminium** [comment]
Hey @jessehouwing, thanks for detailed feedbacks. Code block styles were improved in https://github.com/TryGhost/Casper/commit/b0e21fe0f7c00222fcf86017235daa1550989c31

![Screen Shot 2021-04-01 at 12 57 11 PM](https://user-images.githubusercontent.com/1418797/113247483-b8302700-92ed-11eb-9992-d66ce2501617.png)

Would you be able to open an issue on [TryGhost/Ghost](https://github.com/TryGhost/Ghost) regarding the first one?
