### ISSUE TITLE
Wrong portal window pops up.

### ISSUE THREAD

**Issue by snowcanyon** [TryGhost/Casper#791]
I'm not sure exactly if this is an issue with the theme or not, but as a non-logged in users if you click on a link to log in and then later click on the subscribe button at the top right corner, it pops up the log in portal instead of the subscribe portal.

This can be a link that was created and placed in the navigation or the log in link on the paywall card of the theme. Anytime you click a log in link, close the portal, and then click on the top right subscribe button you will get the wrong portal.

Hope this makes sense and is helpful.

**Comment by minimaluminium** [comment]
Thanks, that makes sense! Fixed in https://github.com/TryGhost/Casper/commit/4708987c395e498fa951d27f975968f6cb6e475b
