### ISSUE TITLE
Did the dark theme disappear from v4?

### ISSUE THREAD

**Issue by Coder-Iro** [TryGhost/Casper#794]
In v3, there was a dark theme that was automatically applied according to the system theme. But after updating to v4, I found out that the dark theme disappeared. Is the dark theme permanently gone? Or do you have any plans to make it?

**Comment by minimaluminium** [comment]
Duplicate of [a discussion](https://forum.ghost.org/t/casper-dark-theme-is-gone-in-ghost-4-0/21037) on the forum.
