### ISSUE TITLE
Overriding CSS variables 

### ISSUE THREAD

**Issue by sssoz** [TryGhost/Casper#800]
Hi there,

Thanks for all your work on this theme; it’s so organised and nice to work with! I’m not sure if this would qualify as a bug, so do let me know.

I’ve forked Casper to make some minor modifications to the templates & stylesheets to suit our needs, while still making sure that we can get major updates on the theme (e.g. 4.0). To keep things as clean as possible, I’ve created `custom.css` which loads after `screen.css`. 

I noticed that the CSS variables are in `screen.css`; I’ve declared my own colour & font variables in my `custom.css` file. However, after compilation, this means that selectors will still use variables from the original `screen` file, not mine, unless I re-declare every single selector that includes either a font or colour variable. To keep things separate & avoid modifying the original theme, would it be a good idea to maybe break down the theme’s stylesheets into separate files so that we can override the variables without having to modify the original code? 

Not sure if I’m explaining this correctly... or if perhaps there is a better way to do this. Should I be modifying the variables in `screen.css` directly instead? 

Thanks!

**Comment by minimaluminium** [comment]
Hey there,

As far as I understand, you're trying to change the CSS custom properties which are colors and fonts. If that's the case, you can just override them in your `custom.css` like:

```css
:root {
    --color-green: NEW_GREEN_VALUE;
    --color-yellow: NEW_YELLOW_VALUE;
}
```

Hope I didn't misunderstand your question. Showing some CSS you added to `custom.css` might also help understanding the context :)

**Comment by sssoz** [comment]
Hi @minimaluminium -- thanks for your response! 

I know we can simply override the variables in our own file but that’s not the issue for me. Here’s an example of what I meant: 

In the templates, in `<head>`, I load up our two CSS files like this: 
```
<link rel="stylesheet" type="text/css" href="{{asset "built/screen.css"}}" />
<link rel="stylesheet" type="text/css" href="{{asset "built/custom.css"}}" />
```

In Casper’s `screen.css`, we have: 
```CSS
:root {
  --color-wash: #e5eff5;
}

.gh-content pre {
  color: var(--color-wash);
}
```

In my `custom.css` file, I want to change `color-wash`’s value, so I could declare it like this for example: 
```CSS
:root {
  --color-wash: blue;
}
```

However, upon compilation, because the CSS is compiled one by one, our selector `.gh-content pre` will not inherit our new `--color-wash: blue` declaration. It will still be displayed as `#e5eff5;`, from `custom.css`’s variables. 

In order to override that, I have to re-declare `.gh-content pre { ... }` in my `custom.css` on top of changing the variable (as shown above). This becomes inconvenient and makes the stylesheets very bloated when we realise that both `---font-...` and `---color-...` variables are used in numerous CSS rules and we have to individually call them again to override these colours.

**Comment by minimaluminium** [comment]
This shouldn't be an issue. I've just tried this workflow on my end, and it works as expected.

![Screen Shot 2021-04-26 at 12 58 12 PM](https://user-images.githubusercontent.com/1418797/116030993-66ca4c00-a68f-11eb-9720-07b002bc244d.png)
![Screen Shot 2021-04-26 at 12 58 23 PM](https://user-images.githubusercontent.com/1418797/116031001-6a5dd300-a68f-11eb-8323-185495365052.png)
![Screen Shot 2021-04-26 at 1 01 38 PM](https://user-images.githubusercontent.com/1418797/116031119-9bd69e80-a68f-11eb-9d04-67f58ab5287c.png)
