### ISSUE TITLE
How to write JS in Ghost Posts ?

### ISSUE THREAD

**Issue by 007AMAN007** [TryGhost/Casper#801]
Hi I am new with ghost....

I am trying to run simple toggle example in ghost it's not working on site.

I am adding this JS code in injection

```<script>
function myFunction() {
  var x = document.getElementById("myDIV");
  if (x.style.display === "none") {
    x.style.display = "block";
  } else {
    x.style.display = "none";
  }
}
</script>```

And calling this function on button written in my post 

```<button onclick="myFunction()">Try it</button>
```

But it's giving error function not defined.

How I can include JS code in gatsby site ?

**Comment by minimaluminium** [comment]
Hey 👋 . We ask that you please do not use GitHub for support or feature requests 😄. We use GitHub solely for bug-tracking and on-going feature development.

Our [forum](https://forum.ghost.org/) is a great place to get community support, plus it helps create a central location for searching problems/solutions.

Thanks!
