### ISSUE TITLE
Subscribe button on top

### ISSUE THREAD

**Issue by videog4mes** [TryGhost/Casper#802]
Hey I have removed the subscribe button from the top of my site now its removed but when I click on one of my articles I still find one that is under
![subscribe button](https://user-images.githubusercontent.com/59100756/116010013-6c615c80-a5d1-11eb-8d6e-15a99e548b7c.png)
how can I remove it?

**Comment by minimaluminium** [comment]
Hey 👋 . We ask that you please do not use GitHub for support or feature requests 😄. We use GitHub solely for bug-tracking and on-going feature development.

Our [forum](https://forum.ghost.org/) is a great place to get community support, plus it helps create a central location for searching problems/solutions.

Thanks!
