### ISSUE TITLE
v4.0.4 - Post article paragraphs don't get the correct font...

### ISSUE THREAD

**Issue by jaguart** [TryGhost/Casper#803]
Main index page looks fine without any customisation - in a sans-serif font.

Article pages have a **serif** font. from a `.gh-content>p` selector in `screen.css`

Adding: `article.post p { font-family: inherit;; }` in code-injection fixes the issue by making the font-family consistent.

**Comment by minimaluminium** [comment]
A serif font was used on the post content intentionally as defined [here](https://github.com/TryGhost/Casper/blob/4708987c395e498fa951d27f975968f6cb6e475b/assets/css/screen.css#L941). You can always make it sans serif on your end like you did in code injection 🙂
