### ISSUE TITLE
Tag page: <header> element can't be child of <header>

### ISSUE THREAD

**Issue by l33d4n** [TryGhost/Casper#809]
The element 'header' must not appear as a descendant of the 'header' element.

W3C validator: https://validator.w3.org/nu/?doc=https%3A%2F%2Fdemo.ghost.io%2Ftag%2Fgetting-started%2F

URL: https://demo.ghost.io/tag/getting-started/

```html
<header class="post-card post-card-large">
   ...
   <header class="post-card-header">
      <div class="post-card-primary-tag">Tagged</div>
      <h2 class="post-card-title">Getting Started</h2>
   </header>
   ...
</header>
```

https://github.com/TryGhost/Casper/blob/ea33b00c0a8c302124a504ac673c056f8c555f82/tag.hbs#L10-L45

**Comment by minimaluminium** [comment]
Hey @l33d4n,

Thanks, fixed in https://github.com/TryGhost/Casper/commit/21bdffbd8ab0fb416c1c89ec944606ebc1eab745 :)

**Comment by l33d4n** [comment]
Great! Thank you.
