### ISSUE TITLE
How can I import NPM package in casper theme

### ISSUE THREAD

**Issue by m-arslan-dev** [TryGhost/Casper#816]
I just want to use fontawesome in this theme
I have configured it just importing css file in default.hbs file from cdn.  I want to include from npm package

**Comment by minimaluminium** [comment]
Hey 👋 . We ask that you please do not use GitHub for support or feature requests 😄. We use GitHub solely for bug-tracking and on-going feature development.

Our [forum](https://forum.ghost.org/) is a great place to get community support, plus it helps create a central location for searching problems/solutions.

Thanks!
