### ISSUE TITLE
Consider migrating from fitvids.js

### ISSUE THREAD

**Issue by seltzered** [TryGhost/Casper#823]
There's less of a need for fitvids.js these days as object-fit can be used on container divs of video elements. See https://youtu.be/wCGipDiDQck?t=324 (which includes the creators of fitvids.js) and https://caniuse.com/?search=object-fit .

**Comment by minimaluminium** [comment]
Hey @seltzered, I might be wrong, but shouldn't we looking for the browser compatibility of [aspect-ratio](https://caniuse.com/?search=aspect-ratio) instead of object-fit?

In this situation, Safari support for aspect-ratio is lower than expected at the moment.

**Comment by seltzered** [comment]
Fair point, will close for now.
