### ISSUE TITLE
adjust content length

### ISSUE THREAD

**Issue by foolioo** [TryGhost/Casper#825]
thank you for the theme!

there is no issue, this is only a question...
i am using casper version 4.20 and i am interested in a style snippet, which i can inject to the site header to modify the width of the post to occupy 90% of the screen width.

would be thankful for any help

**Comment by minimaluminium** [comment]
Hey 👋 . We ask that you please do not use GitHub for support or feature requests 😄. We use GitHub solely for bug-tracking and on-going feature development.

Our [forum](https://forum.ghost.org/) is a great place to get community support, plus it helps create a central location for searching problems/solutions.

Thanks!
