### ISSUE TITLE
Color scheme auto doesn't seem to work

### ISSUE THREAD

**Issue by yannickcof** [TryGhost/Casper#826]
Site-wide 
Selecting Auto under Color scheme not working!

**Comment by minimaluminium** [comment]
Hey @yannickcof,

Would you be able to provide little more information? e.g. OS and browser you're using.

"Auto" makes the site color scheme dependent on system's color preference. e.g. if your computer is using dark mode, the site would be in dark mode.

Here's how it works:

https://user-images.githubusercontent.com/1418797/141045974-69b4fbaf-61ed-4ee1-afe2-f66718cef049.mp4

**Comment by yannickcof** [comment]
hey @Sodbileg Gansukh I am running on macOS 12.0.1 and using chrome Version 95.0.4638.69 and my system is set to "dark mode". Thx!

**Comment by minimaluminium** [comment]
Hey again, the environment above video was made with is identical to yours. Would you be able to check again?

**Comment by yannickcof** [comment]
hey @minimaluminium ... still the same, not switching !!

**Comment by minimaluminium** [comment]
Would you be able to a provide a link to your site which has auto mode selected as the color scheme?

**Comment by yannickcof** [comment]
Sure. 👇
https://snubmonkey.com/

**Comment by minimaluminium** [comment]
Hey there, just inspected your site and it seems like the CSS is not up-to-date. There are some styles related with the auto mode added [here](https://github.com/TryGhost/Casper/blob/b5b1ea001e6b3f28d4f9960c0316dfb7ea48197d/assets/css/screen.css#L1833-L1970), and I couldn't find them in your site's stylesheet.
