### ISSUE TITLE
CLS issue on desktop

### ISSUE THREAD

**Issue by bennwalsh** [TryGhost/Casper#828]
Hi,

I've been running the default unedited version of casper but it's been failing core web vitals for some time on desktop which is really bad for SEO. It seems to be a CLS issue
<img width="1405" alt="Screenshot 2021-11-18 at 14 00 41" src="https://user-images.githubusercontent.com/7524135/142429731-1d3d20c2-2ccf-4212-ac47-d910706e07d0.png">
.

**Comment by minimaluminium** [comment]
Hey @bennwalsh,

Sorry about the long delay here :)

Would you be able to send us your site URL, and possibly the links that are reported if that's possible?

**Comment by bennwalsh** [comment]
thanks to @minimaluminium [minimaluminium](https://github.com/minimaluminium) Adding the following code to the Code injection header section fixed the issue

<style>
.gh-head-logo img {
width: 121px;
height: 26px;
}

.article-image img {
aspect-ratio: 3/2;
object-fit: cover;
}
</style>
