### ISSUE TITLE
The site design preview is now broken.

### ISSUE THREAD

**Issue by boycottseattle** [TryGhost/Casper#831]
Using the latest version of Ghost with Casper 4.5 breaks the page preview on the design page.

**Comment by minimaluminium** [comment]
Hey @boycottseattle, just checked with the latest version of Ghost and Casper, but couldn't reproduce the issue. Would you be able to send a screenshot, and see if there's any console error when on the design screen?

**Comment by boycottseattle** [comment]
Screenshot? No point...it just shows blank. Nothing there. Just blank.

**Comment by minimaluminium** [comment]
The issue wasn't reproducible, so I'm closing this one. If you still encounter this, make sure to reopen the issue.
