### ISSUE TITLE
Right To Left (RTL) script support

### ISSUE THREAD

**Issue by foolioo** [TryGhost/Casper#833]
Firstly, thanks you all for the fine work!

I've been using Ghost for a long time and up until now, there is no builtin support for [Right-To-Left (RTL) scripts](https://en.wikipedia.org/wiki/Right-to-left_script#Current_scripts) - neither for Ghost admin, nor for Ghost website layout.

In the community, there are post on how to achieve it by modifying the template's styles
- [Layout change from left to right and better language support](https://forum.ghost.org/t/layout-change-from-left-to-right-and-better-language-support/14339)
- [Ghost Tips & Tricks #2 / Ghost Admin Right to Left (RTL) Support](https://forum.ghost.org/t/ghost-tips-tricks-2-ghost-admin-right-to-left-rtl-support/14357)

Modifying the template's styles is done one per Ghost version. Once a version is updated, the steps needs to be repeated (if the is no breaking changes), which makes the update processes cumbersome.

Was wondering whether there is any plans to bake RTL support into the theme or Ghost itself? (just to be clear, I do not refer to the translation of Ghost interface)

**Comment by minimaluminium** [comment]
Hey @foolioo, happy new year! We're not planning to add RTL support to Casper at the moment.

The mentioned solutions on the forum could be added as code injection instead of merging them with the theme's default stylesheet, so the changes won't be overridden when you update the theme.
