### ISSUE TITLE
Why default.hbs doesn't have OG tags by default?

### ISSUE THREAD

**Issue by tiendq** [TryGhost/Casper#838]
I don't see OG tags e.g. `og:img` in `default.hbs` then post is shared with ugly preview in default Ghost installation.

While the Casper demo shows OG tags nicely (make me things they're default settings) e.g. https://demo.ghost.io/the-purpose-of-education/

**Comment by minimaluminium** [comment]
Hey @tiendq, all Open Graph tags are added by Ghost core, not by themes. If your theme doesn't output them, it's most likely there's no `{{ghost_head}}` in your theme's `default.hbs` template ([example](https://github.com/TryGhost/Casper/blob/5cdcda15ee93027aaf203b6ef1d408d40fe36b0a/default.hbs#L27))

**Comment by tiendq** [comment]
I use default settings, it uses Casper, so it should have {{ghost_head}} by default. But even after I added FB metadata manually in the post settings then still don't see `og` tags generated.

**Comment by minimaluminium** [comment]
Do you have a link to the post that doesn't output the tags?

**Comment by tiendq** [comment]
> Do you have a link to the post that doesn't output the tags?

Please have a look at this link https://blog.haypley.com/ky-thuat-doc-dao-rap-nha-lego/

FB title, description, image are provided in the post settings but none of them appears in the post (public view).

I use the latest Casper v4.7.2

**Comment by tiendq** [comment]
I just tried again with a quick `ghost install local` and got same result. There must be something wrong with `ghost_head`, reported [here](https://github.com/TryGhost/Ghost/issues/13983).
