### ISSUE TITLE
Usage of the !important CSS qualifier

### ISSUE THREAD

**Issue by madhavmehndiratta** [TryGhost/Casper#839]
The use of !important CSS qualifier is not recommend by Google AMP and hence it is showing errors in the Google Search Console.

https://amp.dev/documentation/guides-and-tutorials/develop/style_and_layout/style_pages/

![image](https://user-images.githubusercontent.com/43489174/151925412-df9c9469-a287-48be-ae45-754571c7ab57.png)

**Comment by minimaluminium** [comment]
Hey @madhavmehndiratta,

This was fixed in https://github.com/TryGhost/Ghost/commit/76cde7918687304af21b3f89c8ca51399f9d3bea and the fix was included in Ghost [v4.32.1](https://github.com/TryGhost/Ghost/releases/tag/v4.32.1).

So please update your Ghost instance :)
