### ISSUE TITLE
Changing the cover image size

### ISSUE THREAD

**Issue by KnightKrusty** [TryGhost/Casper#840]
![Screenshot_20220216_182334](https://user-images.githubusercontent.com/84474313/154859586-4e83f6b3-5dc5-402e-9535-60f42be2ef18.png)

Hello, I am trying to customise the casper theme similar to uploaded screenshot, i have changed the navigation  completely but i am not able to change the size of the cover image.. i have tried quite few things but i am not able to change its size...

This is my first experience working on Ghost theme so there are lot of variables i dont get, a bit of help would be awesome..

**Comment by KnightKrusty** [comment]
```
.site-header-content {
    max-height: 650px;
}
```

Seems like this is the answer i was looking for....

**Comment by KnightKrusty** [comment]
Seems like adding gradient isnt that easy a little help there would be awesome....

**Comment by minimaluminium** [comment]
Hey 👋 . We ask that you please do not use GitHub for support or feature requests 😄. We use GitHub solely for bug-tracking and on-going feature development.

Our [forum](https://forum.ghost.org/) is a great place to get community support, plus it helps create a central location for searching problems/solutions.

Thanks!
