### ISSUE TITLE
Toggle Cards Not Working

### ISSUE THREAD

**Issue by doncabreraphone** [TryGhost/Casper#841]
The Toggle cards are not working on Casper. It displays a large down arrow button on firefox and a tiny gray button on chrome and doesn't works in neither of them.

![image](https://user-images.githubusercontent.com/45015326/156274009-13686621-8e98-44ad-b01a-37ac2e387b5f.png)

Is there something I'm missing? This is a new installation of ghost.

**Comment by minimaluminium** [comment]
Hey @doncabreraphone,

Is there any live link where I can check? Might be something related with card assets not being served. Have you disabled the card assets by any chance in `package.json`?

More info: https://ghost.org/docs/themes/content/#editor-cards

**Comment by doncabreraphone** [comment]
Not at all, it is a clean installation, didn't touch a thing yet. I'm working locally, so it is not online yet.

**Comment by doncabreraphone** [comment]
> Hey @doncabreraphone,
> 
> Is there any live link where I can check? Might be something related with card assets not being served. Have you disabled the card assets by any chance in `package.json`?
> 
> More info: https://ghost.org/docs/themes/content/#editor-cards

Everything seems normal to me, but still doesn't works.

![image](https://user-images.githubusercontent.com/45015326/156645633-53ac14c6-a060-4cea-9488-fd3e62eb4b6e.png)

**Comment by doncabreraphone** [comment]
I just confirmed that the `cards.min.css` and `cards.min.js` are not being loaded in the `{{ghost_head}}` helper. How can I load them manually?

**Comment by minimaluminium** [comment]
Hey @doncabreraphone, would you be able to open the issue in [TryGhost/Ghost](https://github.com/TryGhost/Ghost)? This doesn't sound like a theme specific issue if the assets aren't being loaded even if `"card_assets": true` is defined in package.json.

**Comment by minimaluminium** [comment]
Found that you've already opened one there, thanks!
