### ISSUE TITLE
Section Headers Card not consistent with editor

### ISSUE THREAD

**Issue by doncabreraphone** [TryGhost/Casper#843]
The more I try to use Ghost with its default theme Casper, the more I realize half of the features advertised on the theme side are not even finished.

This is Casper's Section Header Cards.

**Editor version:**

![image](https://user-images.githubusercontent.com/45015326/156901774-111b2e63-2178-475d-9190-30a718f1ed4f.png)

**Live version:**

![image](https://user-images.githubusercontent.com/45015326/156901761-e6bc40c4-0de4-43c7-a3b0-99836656bf63.png)

Please keep in mind I'm using the latest Casper version, fresh installation, no code injected or anything. It should work, right? Maybe I am missing something here?

Casper version 4.7
Ghost Version: 4.38.0

* Colors are not working (only black works)
* Background images are working fine
* Buttons are not working (they don't show up with the right class, I only see the link, but not a button)
* Sub-text is not working properly (no alignment present)

**Comment by minimaluminium** [comment]
Closing for the same reason as https://github.com/TryGhost/Casper/issues/845.
