### ISSUE TITLE
Site Navigation not hiding on scroll (like in the Select Theme)

### ISSUE THREAD

**Issue by doncabreraphone** [TryGhost/Casper#844]
Maybe I'm missing something, but when I installed Ghost and I selected Casper for my site, I was under the impression that the nav will hide and the post title will be shown instead when the reader scrolls through the page, just like it happens in the "Select Theme" section on the editor.

![image](https://user-images.githubusercontent.com/45015326/156902622-73031877-a78a-4068-a550-a32d1b581445.png)

On scroll, it hides and shows the post title:

![image](https://user-images.githubusercontent.com/45015326/156902625-b0d39090-e559-4cc9-8653-c3b6be3baa3f.png)

But in reality that never happens. The classes to make that work are present online in error.hbs, not in default.hbs.

Default.hbs
![image](https://user-images.githubusercontent.com/45015326/156902628-959395dc-2b2e-459a-9741-51c3e33f7632.png)

Header.hbs
![image](https://user-images.githubusercontent.com/45015326/156902631-23418c10-e2d2-4a92-a7b1-cbca6e03dabe.png)

So I'm a bit confused here. Why there are two different codes for the navigation? And how do I make the default "hide navigation on scroll" work?

**Comment by doncabreraphone** [comment]
Just found out this is no longer a supported feature. I'm closing this comment and leaving it here in case someone else comes looking. The Casper demo on the Select a Theme should be updated to the latest version to avoid wasting people's time.

**Comment by minimaluminium** [comment]
Hey @doncabreraphone, thanks for the report. Now the correct version of the Casper demo is used in the admin. https://github.com/TryGhost/Admin/commit/eea5706e076effebebbafb8a3e76cd66dd982bb9
