### ISSUE TITLE
H1 headers that are also marked Bold disappear on Mobile browser

### ISSUE THREAD

**Issue by orencohendev** [TryGhost/Casper#847]
On mobile, when I include a bolded H1 headline in a post, it doesn't show up. Instead, it's just blank.
This reproduces on Chrome, Safari, Firefox, and Brave.
You can see an example in this link on my blog. Access it from both mobile and desktop and look for the header at the bottom of the post "Want to be featured too?"
https://www.itsyourshoe.com/josh-philips-reviews-the-jordan-6-unc/

# Specs For Reproduction
Here's what I've been using to reproduce the problem:
- Windows 11 / Chrome Browser - Works well on desktop.
- iPhone 13 Pro Max / Chrome, Safari, Firefox, and Brave - All of them reproduce the problem.
- Casper 4.7.2 edited to include Hyvor Talk comments on the post handlebars file.
- Latest edition of Ghost (I'm hosting on Ghost Pro so updates are automatic).

# Screenshots
Some screenshots from my desktop and mobile.

## On Desktop headline appears correctly:
![2022-03-11](https://user-images.githubusercontent.com/62210374/157857542-689acae4-6d60-4af8-a91e-be287ad380d5.png)

## On Mobile (the headline should be where the red rectangle is)
![IMG_8894](https://user-images.githubusercontent.com/62210374/157857577-e522c22d-85a0-41b3-9898-c0cb42a419c9.jpg)

**Comment by minimaluminium** [comment]
Hey @orencohendev, not sure I understand the issue well.

Would you be able to provide some screenshots that explain what's expected and what's not?

**Comment by orencohendev** [comment]
@minimaluminium Added some screenshots from my desktop and mobile phone to illustrate the problem.

**Comment by orencohendev** [comment]
Update: My H1 headline was bolded in the editor, too. When I removed the bold in the editor (since it doesn't do anything anyway), the header appeared on mobile.

**Comment by orencohendev** [comment]
I also updated the ticket name to reflect this new information

**Comment by minimaluminium** [comment]
Hi! I've just inspected the title element and it has some serious deep nesting with `<strong>` tag. That might be the reason why it's not showing up on mobile browser because of the limit for maximum nested element.

No idea why it has that many nested elements though 😬. Would you try removing it and writing again?

https://user-images.githubusercontent.com/1418797/158504389-6648a717-4706-4b47-83ce-76b5290ab043.mp4

**Comment by orencohendev** [comment]
Yes, that's what I wrote above that when I removed the bold on the header everything worked correctly. For some reason, the bold formatting remained after I transformed the bolded text to a title.

**Comment by minimaluminium** [comment]
I've just tried to reproduce the issue by toggling bold formatting on a header couple of times, and the `<strong>` tag was toggled correctly without being nested.

> I removed the bold on the header

Could you try removing the header text altogether, not just the formatting?

**Comment by orencohendev** [comment]
> Could you try removing the header text altogether, not just the formatting?

Removed.

**Comment by orencohendev** [comment]
Added back. It does appear now as expected without the bolding. Do you see anything different in regards to the strong tags?

**Comment by minimaluminium** [comment]
Now it doesn't have any nested multiple `<strong>` tags :)

<img width="485" alt="CleanShot 2022-03-16 at 5 35 47@2x" src="https://user-images.githubusercontent.com/1418797/158560496-eef355e4-4625-4dba-9ad8-22ee89759a95.png">
