### ISSUE TITLE
inconsistent nodejs version support for development

### ISSUE THREAD

**Issue by orklepee** [TryGhost/Casper#849]
### Issue:
The supported versions of Nodejs for Ghost and Yarn never align. 

**Ghost: `ghost start` after installing supported nodejs version for yarn**
```ps
Message: The version of Node.js you are using is not supported.
Supported: ^12.22.1 || ^14.17.0 || ^16.13.0
Installed: 14.13.0
```

**Yarn: `yarn install` after installing supported nodejs version for ghost**
```ps
error gscan@4.0.0: The engine "node" is incompatible with this module. Expected version "^10.13.0 || ^12.10.0 || ^14.13.0". Got "14.17.0"
error Found incompatible module
```

The only workaround here seems to be downloading Node.js for yarn's supported versions, then forcing a reinstall to meet Ghost's supported version. From this point, you can launch `ghost start`, then `yarn dev` to compile CSS. Seems a little counter-intuitive, no?

**Comment by minimaluminium** [comment]
Hey @orklepee, looks like the version of gscan you're using is bit old. The current version is 4.22.0 and the supported Node.js versions are same as Ghost. https://github.com/TryGhost/gscan/blob/069e6977633fb8e5de18e725d79bcdcefe7bcfc7/package.json#L17
