### ISSUE TITLE
Double scrollbars @ Signup Popup

### ISSUE THREAD

**Issue by doncabreraphone** [TryGhost/Casper#850]
The popup shows double scrollbars, in every major browser, as shown in this Firefox screenshot.

![image](https://user-images.githubusercontent.com/45015326/158469249-5ff23aec-2cf7-4c9f-be03-b203695e90d4.png)

The issue comes from the CSS rule "overflow: hidden" being ignored when the popup with the iframe appears, since ".gh-portal-popup-wrapper" has an "overflow: scroll" rule.

I recommend removing the overflow scroll or setting it to auto, or sacrificing a goat since that is how we solve most things in my home village. Either way, this is an easy fix, bu just in case, I will go get a goat.

**Comment by orencohendev** [comment]
I can't find `gh-portal-popup-wrapper` in Casper's CSS files. Maybe it's a change that should be introduced on CSS that exists in the main Ghost theme where the admin is stylized too?
