### ISSUE TITLE
how to remove connect.facebook.net/en_US/fbevents.js script from head? 

### ISSUE THREAD

**Issue by Rabinzon** [TryGhost/Casper#852]
![Kanban powered visual management system @ Kaiten 2022-03-23 19-23-58](https://user-images.githubusercontent.com/8072488/159747764-5d33505f-2b07-4e3f-b53f-849ed1ac19c3.png)

I can't find where this script is injected :(

**Comment by minimaluminium** [comment]
Hey @Rabinzon, this script isn't added by Casper.

We ask that you please do not use GitHub for support or feature requests 😄. We use GitHub solely for bug-tracking and on-going feature development.

Our [forum](https://forum.ghost.org/) is a great place to get community support, plus it helps create a central location for searching problems/solutions.

Thanks!
