### ISSUE TITLE
Subscribe elements stay visible despite having disabled memberships

### ISSUE THREAD

**Issue by keraf** [TryGhost/Casper#854]
When disabling all membership features in the Ghost admin panel, the subscription elements (header and post) stay visible but provide no functionality (nothing happens when clicking on them). Even after signing out of the admin panel, they stay visible.

Reproduction steps:
- Go to Admin -> Settings -> Memberships
- Under "Subscription access", select "Nobody"
- Return to the website and visit a post

Actual result: The "Subscribe" button in the header is visible. On posts, the "Sign up for more like this" section is visible. Nothing happens when clicking on both.

Desired result: Hide subscription functionality when memberships are disabled.

Info:
- Ghost version: 4.41.3
- Ghost admin version: 4.41.3
- Casper version: 4.7.3
- Hosting: Self-hosted (Ubuntu 20.04 LTS)
- Browser: Firefox 98.0.2 (64-bit)
- Operating System: Windows 11

**Comment by minimaluminium** [comment]
Hey @keraf! Currently, the subscription access setting only affects the admin area and Portal on the frontend. There's no helper to check the subscription access on the theme side. At the moment, the only ways to hide those elements would be customizing your theme code, or using CSS in the code injection.
