### ISSUE TITLE
Adding an element after gh-content breaks font

### ISSUE THREAD

**Issue by wilsonowilson** [TryGhost/Casper#857]
I'm trying to follow this tutorial on the ghost site: https://ghost.org/docs/tutorials/adding-a-table-of-contents/

In the tutorial, I'm told to replace this: 

```hbs
<section class="gh-content gh-canvas">
     {{content}}
</section>
```

with this:

```hbs
<section class="gh-content gh-canvas">
    <aside class="toc-container">
        <div class="toc"></div> 
    </aside>
    <section class="post-full-content">
        <div class="post-content">
            {{content}}
        </div>
    </section>
</section>
```

But doing this completely breaks the font. I noticed the same holds true if I wrap the `{{content}}` with any element.

How can I fix this?

**Comment by minimaluminium** [comment]
Hey 👋 . We ask that you please do not use GitHub for support or feature requests 😄. We use GitHub solely for bug-tracking and on-going feature development.

Our [forum](https://forum.ghost.org/) is a great place to get community support, plus it helps create a central location for searching problems/solutions.

Thanks!
