### ISSUE TITLE
Honor options to disable membership / newsletter

### ISSUE THREAD

**Issue by nappy** [TryGhost/Casper#859]
The subscribe button in the header and the subscribe box below posts should be removed when subscription access is disabled under membership.

I think there is not much to add, should be pretty clear already.

**Comment by minimaluminium** [comment]
Hey @nappy. Currently, the subscription access setting only affects the admin area and Portal on the frontend. There's no helper to check the subscription access on the theme side. At the moment, the only ways to hide those elements would be customizing your theme code, or using CSS in the code injection.
