### ISSUE TITLE
Tag page top image

### ISSUE THREAD

**Issue by viriatusX** [TryGhost/Casper#864]
Hi,
I have upgraded to Casper 5.1.0 and noticed that the top image of the "Tag.hbs" page has an excessive blur effect. In Casper 5.0.0 the image looked fine.
Is it a change or a bug?
Honestly I like it very much with the Blur effect, but I would like it to be less aggressive. It's possible modify with CSS?
Thanks !
<img width="1354" alt="Captura de pantalla 2022-05-27 a las 11 57 05" src="https://user-images.githubusercontent.com/64467637/170677814-8af02f0e-8906-4d87-aa14-a8dd531eb8a7.png">
<img width="1295" alt="Captura de pantalla 2022-05-27 a las 11 56 48" src="https://user-images.githubusercontent.com/64467637/170677822-ce8accbd-0baa-4452-85ef-8ac3678f9f17.png">

**Comment by minimaluminium** [comment]
Hi @viriatusX, it's definitely a bug. Good catch, really appreciate it! Fixed in [5.1.1](https://github.com/TryGhost/Casper/releases/tag/v5.1.1) 🙂
