### ISSUE TITLE
post.hbs bug/ incompatibility 

### ISSUE THREAD

**Issue by viriatusX** [TryGhost/Casper#866]
Hello!
I found another possible bug/incompatibility. I followed the Ghost official tutorial (https://ghost.org/tutorials/adding-table-of-contents/)

With Casper 4.x.x there was ".post-full-content" class but not with Casper 5.
If I want to customize "TOC" with CSS element padding now, for example, it affects the rest of the post content. is it possible to add fix it please?
**BUG:** Also, if the Table of Contents has many elements like picture 2, the generated space in the post is too big. I think this is because: <div class="gh-toc"></div> is integrated inside the "gh-content gh-canvas" section. I have tried creating the ".post-full-content" class and integrating it into post.hbs but it doesn't work.

Thanks!

<img width="1400" alt="Captura de pantalla 2022-05-31 a las 20 16 45" src="https://user-images.githubusercontent.com/64467637/171256841-d1f1d179-5f0b-40ce-95b5-753054477ec2.png">
<img width="1279" alt="Captura de pantalla 2022-05-31 a las 22 26 55" src="https://user-images.githubusercontent.com/64467637/171278733-a77da713-0b4f-4e55-8b2d-f4721b6b28c7.png">

**Comment by minimaluminium** [comment]
Hey @viriatusX, the tutorial has been updated for Casper 5. Please follow the new instructions.
