### ISSUE TITLE
style floating portal button

### ISSUE THREAD

**Issue by jalberto** [TryGhost/Casper#871]
I would like to style, even move to a different place, the floating portal button, right now it is an injected iframe with inline styles, but I cannot find where it is injected.

Which is the recommended way to do this?

**Comment by minimaluminium** [comment]
Hey 👋 . We ask that you please do not use GitHub for support or feature requests 😄. We use GitHub solely for bug-tracking and on-going feature development.

Our [forum](https://forum.ghost.org/) is a great place to get community support, plus it helps create a central location for searching problems/solutions.

Thanks!
