### ISSUE TITLE
The post preview on don't render markdown

### ISSUE THREAD

**Issue by rakanskiy** [TryGhost/Casper#872]
The post preview on main page don't render markdown:
Ghost v5.2.2
Casper v5.1.4

Is it something wrong with my installation or post itself, or it a bug?
Preview:
<img width="798" alt="image" src="https://user-images.githubusercontent.com/30781071/173457754-1f6fe3b5-ec53-4ccc-8e11-596602960933.png">
Post page:
<img width="781" alt="image" src="https://user-images.githubusercontent.com/30781071/173458110-0a62b657-a7da-43fe-a835-ade7d1ea2b00.png">

**Comment by minimaluminium** [comment]
Hey @rakanskiy! Would you be able to send the markdown content you're using on this example? And by post preview, did you mean the post card on the homepage?

**Comment by minimaluminium** [comment]
Thanks for the update! I guess we could close the issue for now.
