### ISSUE TITLE
Search Icon Issue on Mobile

### ISSUE THREAD

**Issue by bennwalsh** [TryGhost/Casper#879]
Hi,

If you're viewing a post / article and click the hamburger menu the search icon doesn't show because the logo is in the way. Are you able to fix this?
For the best user experience the search icon should appear in the header next to the hamburger icon.

**Comment by viriatusX** [comment]
Same issue...

**Comment by minimaluminium** [comment]
Hey, thanks for the report! Fixed in [5.2.1](https://github.com/TryGhost/Casper/releases/tag/v5.2.1)
