### ISSUE TITLE
Display login button when subscription access set to invite

### ISSUE THREAD

**Issue by ryansechrest** [TryGhost/Casper#891]
# Current Behavior

The button in the header:

Displays **Subscribe** when...
- Visitor is not logged in
- Subscription access is "Anyone can sign up" or "Only people I invite"

Displays **Account** when...
- Visitor is logged in

Does not display when...
- Subscription access is "Nobody"

# Proposed Behavior

I'm wondering if it would be appropriate to:

Display **Login** when...
- Subscription access is "Only people I invite"

# Reason for Change

The reason being:

1. Visitors won't think to click **Subscribe** to login, since they're already subscribed
2. Visitors have to click twice to login: Once on **Subscribe** and then on **Sign in** in that modal

I'm guessing the notice that appears when visitors click **Subscribe**, and the site is set to "Only people I invite," is to inform them  that they can't register and to contact the owner of the site to get an account.

Do site admins, who configure their site this way, drive public visitors to their site that would be unaware of this, or is the site intended to be private in that case?

If it's the later, the more frequent occurrence would then be for visitors to login vs. being informed that the site is only for subscribers, since those visitors already know that.

In addition, the information that a visitor is required to reach out to the owner for an account could be covered on a static page, which gives the site admin control over the language being used, and an opportunity to include relevant contact information.

This means the button could say **Login** when an unauthenticated visitors arrives and immediately prompt for their email address to receive a login link.

What are your thoughts on this?

**Comment by minimaluminium** [comment]
Hey @ryansechrest, we really appreciate your detailed feedback. We discussed this within the team and agreed this makes more sense for invite-only sites. We'll need to update all official themes to start using this though. In the meantime, you could follow this instruction to make a change on your end.

1. Open `default.hbs` file.
2. Replace [this line](https://github.com/TryGhost/Casper/blob/c7713df88f11bc2ff612457dfb51d6e1909a40e4/default.hbs#L59) with the code below.

```html
{{#unless @site.members_invite_only}}
    <a class="gh-head-button" href="#/portal/signup" data-portal="signup">Subscribe</a>
{{else}}
    <a class="gh-head-button" href="#/portal/signin" data-portal="signin">Login</a>
{{/unless}}
```

**Comment by ryansechrest** [comment]
Hi @minimaluminium That's great news, and thank you for the code snippet!

**Comment by minimaluminium** [comment]
Hi @ryansechrest, just FYI, this logic is now included in all of our official themes. Thanks for a great suggestion!
