### ISSUE TITLE
Search Icon Issue on Mobile (AGAIN)

### ISSUE THREAD

**Issue by viriatusX** [TryGhost/Casper#894]
Hi!
With Casper 5.3.0 the search icon on Mobile appears wrong again (like: [https://github.com/TryGhost/Casper/issues/879](url))
In the 5.3.0 Screen.css appears again the: 

@media (max-width: 991px) {
    .gh-search {
        position: fixed;
        top: 16px;
        left: 16px;
        z-index: 10;
    }
}

Is for this?

**Casper 5.2.1**
<img width="500" alt="Captura de Pantalla 2022-08-15 a las 19 30 39" src="https://user-images.githubusercontent.com/64467637/184685654-8adb82d3-c6a3-4f8c-8806-b61e638149bb.png">

**Casper 5.3.0**
<img width="500" alt="Captura de Pantalla 2022-08-15 a las 19 31 13" src="https://user-images.githubusercontent.com/64467637/184685673-b76cdccd-4fd6-4a06-8113-ef7715439b9a.png">

Fix it please.
Thanks!!

**Comment by minimaluminium** [comment]
Hi @viriatusX, thanks again! Fixed in 5.3.1.
