### ISSUE TITLE
Gists look horrible when using dark mode.

### ISSUE THREAD

**Issue by ziroau** [TryGhost/Casper#895]
![image](https://user-images.githubusercontent.com/60493188/185004549-a0c3412e-7763-411c-a9e4-b7e9c5cbb1cc.png)

Gist HTML embeds look horrendous when using dark mode with casper.
I'm using the latest version from GitHub.

edit: fixed spelling

**Comment by minimaluminium** [comment]
Hey @ziroau, this is now fixed in 5.3.2.
