### ISSUE TITLE
Infinite homepage scroll prevents quick footer access

### ISSUE THREAD

**Issue by ryansechrest** [TryGhost/Casper#900]
When you're on the homepage (or tags page), posts keep loading when you reach the bottom.

That is quite convenient for keeping the visitor engaged, but it does prevent a visitor from accessing links in the footer until all posts on the website have loaded.

One thought is to include a [load more] button that loads more posts after the initial ones.

Then the visitor can quickly reach the footer, but also continue browsing more posts if they're interested.

Does this seem like a good idea or is there a better way for the visitor to access the footer on those particular pages?

**Comment by akshatakulkarni25** [comment]
hey, can i work on this issue??

**Comment by minimaluminium** [comment]
Hey everyone! We added an additional pagination option that can be enabled with some code injection method. The default infinite scrolling stays as it is. However, when the `<html>` element gets an HTML class `no-infinite-scroll`, the pagination falls back to regular `← Previous` and `Next →` style.

The new feature can be enabled by entering this code in the `Site Header` section of the code injection setting.

```html
<script>document.documentElement.classList.add('no-infinite-scroll');</script>
```
