### ISSUE TITLE
Button Text for Paid Posts

### ISSUE THREAD

**Issue by danielherndon** [TryGhost/Casper#901]
Hey folks,

Just discovered (Casper) that when a post is for paying subscribers, and a logged-in free subscriber views it, the text on the button is white and doesn't appear. 

In an effort to ensure I'm seeing the issue clearly, I removed all my code injections to see if my CSS additions were the source of the problem, but that didn't change anything. 

![Screen Shot 2022-10-03 at 5 12 18 PM](https://user-images.githubusercontent.com/114958412/193691394-36bf20da-3701-40ce-b9a3-44d688d14cb8.png)

Excited to finally see what that button says!

**Comment by minimaluminium** [comment]
Hey @danielherndon,

I couldn't reproduce this. Would you be able to give me an URL to the post that has this issue?

**Comment by danielherndon** [comment]
Thanks for checking. 

This link is one where I am seeing this: https://www.danielkherndon.com/cereal-and-ivy-league/

You have to be a logged-in user who is not a paid user.

One thing I have not checked is to see if this was something caused by cache on my browser, although I would be surprised.

**Comment by minimaluminium** [comment]
I confirm that it's reproducible and it's not related with your browser cache. We're aware of this issue and let you know when it's fixed. In the meantime, could you add this CSS as a code injection until it gets fixed?

```html
<style>
    .gh-post-upgrade-cta a.gh-btn {
        color: var(--ghost-accent-color);
    }
</style>
```

**Comment by danielherndon** [comment]
Thank You! I appreciate the help.

**Comment by rishabhgrg** [comment]
Closed with https://github.com/TryGhost/Ghost/commit/e05889cd53fa3b192701dba06d09322ed4da65be, will be out in next Ghost release.
