### ISSUE TITLE
Opening the menu via the button opens empty about:blank window

### ISSUE THREAD

**Issue by Chiil** [TryGhost/Casper#902]
If I open the menu on small screen, an empty about:blank window is opened, rather than the menu in the same window. My website is https://chiel.ghost.io

**Comment by minimaluminium** [comment]
Hey @Chiil, we've recently added navbar options to Casper in [v5.4.0](https://github.com/TryGhost/Casper/releases/tag/v5.4.0) and we've used `<button>` instead of `<a>` tag for the burger menu toggle which should prevent this kind of issue.
