### ISSUE TITLE
New sign-in link doesn't look right on mobile

### ISSUE THREAD

**Issue by Unreal1david** [TryGhost/Casper#913]
Love the new sign in link, however on mobile it looks to be right justified. I'm pretty sure it should either be centered on one line. 

![image](https://user-images.githubusercontent.com/29103693/207922919-72a6e344-979d-4a90-950b-2455318e8575.png)

**Comment by minimaluminium** [comment]
Hey @Unreal1david, thanks for the feedback. It's now fixed in 5.4.4.
