### ISSUE TITLE
Pinning featured posts to the top?

### ISSUE THREAD

**Issue by ryansechrest** [TryGhost/Casper#914]
I may be pushing my luck with all these tickets, so stop me any time. 😂

When I featured a post for the first time, I had expected the post to be pinned to the top of the homepage (and perhaps even the tag page if it was tagged). When I didn't see it there, my initial reaction was that it didn't do anything, but then I spotted the fire emoji with a "Featured" label above the post title.

I then expected that I would be able to click the "Featured" slug to see all of the featured posts, much like when you click a tag.

My question: Is the intention that a featured post simply has the aesthetic addition of the fire emoji and a "Featured" slug, or is there an opportunity to make a functional impact by sending featured posts to the top?

**Comment by minimaluminium** [comment]
Actually, we really appreciate your feedbacks and bug reports. Please keep them coming if you have any 😅

For featured posts, themes use them in multiple ways. Some fetch and display them separately on the top of the recent posts (e.g. [Edition](https://edition.ghost.io)) while others display them in a sidebar (e.g. [Journal](https://journal.ghost.io)). There are themes that gives big style difference to featured posts as well (e.g. [Ruby](https://ruby.ghost.io)).

We intentionally kept the featured post styles very generic for Casper. The post feed ordering has been like this for a long time, so haven't changed its default behavior when we added featured post indicator to Casper.
