### ISSUE TITLE
Sign in, sign up, subscribe do not work

### ISSUE THREAD

**Issue by einazare** [TryGhost/Casper#921]
Hello guys.

I've installed Ghost (`5.26.3`) and Casper theme (`5.4.5`) on my server, with the initial domain: [blog.vatis.tech](blog.vatis.tech).
After that, I decided to add in my NGINX, a proxy pass, to that the blog would be available on [vatis.tech/blog](vatis.tech/blog) route so that it would seem that it is part of the whole website.
Now, the problem is, that before doing the proxy pass, everything was working as expected, when pressing the Sign in button, or the Subscribe button, a modal would appear with the sign-in form, subscribe form, etc.
After the proxy pass, none of the modal buttons work anymore.

Also, in the console, there are a few errors.
<img width="1310" alt="Screenshot 2023-02-07 at 14 28 41" src="https://user-images.githubusercontent.com/26245512/217250600-9bdc521b-baf7-4fca-a1dd-cb66324f02fb.png">
<img width="1029" alt="Screenshot 2023-02-07 at 14 45 10" src="https://user-images.githubusercontent.com/26245512/217250613-c47fc749-58e4-451a-bbd5-9959a4531df8.png">

I hope this is the right place to ask about this, and if you know how this could be solved.

**Comment by einazare** [comment]
Some of the warnings I get:
```
{"errors":[{"message":"Authorization failed","context":"Unable to determine the authenticated member or integration. Check the supplied Content API Key and ensure cookies are being passed through if member auth is failing.","type":"NoPermissionError","details":null,"property":null,"help":null,"code":null,"id":"dfb66fd0-a724-11ed-931c-7f8672f6be1e","ghostErrorCode":null}]}
```
From:
```
curl -v 'https://vatis.tech/blog/ghost/api/content/newsletters/?key=bf9adb54b6e07ecf64bb9f490b&limit=all' \
  -H 'Accept: */*' \
  -H 'Accept-Language: en-GB,en-US;q=0.9,en;q=0.8,ro;q=0.7' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/json' \
  -H 'Cookie: ghost-admin-api-session=s%3Ae-x-5hVeZsIOdeua2V6MnCZ-lqi0Ttet.X%2FmyT0nGHJW6o7LzYI1zuK8xJT3jUGrU59AeFxicKtw; _ga=GA1.2.125480099.1587984466; __stripe_mid=6a9728f5-8b91-4529-9d5d-e47d0b9b52a7bac9fc; _fbp=fb.1.1672228668069.114332600; _gcl_au=1.1.1887982092.1673510381; _gid=GA1.2.1026639467.1675677252' \
  -H 'Referer: https://vatis.tech/blog/' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua: "Not_A Brand";v="99", "Google Chrome";v="109", "Chromium";v="109"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  --compressed
```

**Comment by ryansechrest** [comment]
Hi @einazare I could be wrong, but this sounds like a back-end configuration issue, and not one specific to the Casper theme, which is what this GitHub repo is. You might have better luck getting your question answered over in the Ghost Forum, specifically the Self-Hosted category: https://forum.ghost.org/c/help/self-hosting/18

**Comment by einazare** [comment]
Hello @ryansechrest . Thank you for getting back to me. 
I will do that, and I will ask on the forum. 
Eventually, we moved our blog back to blog.vatis.tech, and everything works again.
