### ISSUE TITLE
Primary navigation hamburger menu not visible

### ISSUE THREAD

**Issue by hkrsmk** [TryGhost/Casper#925]
My settings:
Show publication cover: off
Color scheme: auto
Navigation layout: logo on cover
Ghost version: 5.36.0
Casper version: 5.4.5

Steps to reproduce:
1. Reduce screen size until the primary navigation bar disappears, or view Casper site in mobile
2. Go to the top right where the hamburger menu is supposed to be
3. Observe that you can't see the hamburger menu
4. Clicking on where the hamburger menu is, no dropdown menu seems to appear.

You can see this on my blog https://adventgineering.org

**Comment by officialrajdeepsingh** [comment]
The hamburger menu is not working on your website because you turn dark mode, and the hamburger icon does not change color according to the dark theme. It works fine with your site's light mode ( remove dark mode  ). 

> Enable light theme and your  hamburger menu icon is work fine.

**Comment by officialrajdeepsingh** [comment]
chnage Color scheme: light

**Comment by hkrsmk** [comment]
Three follow ups:
1. That means we should make it work in dark mode by changing the css somewhere. Probably in the screen.css file in the Dark Mode section.
2. Not sure what's wrong with the hamburger, I noticed that even on reduced screens, in the code the area on the website where Primary Navigation should be still links to the correct pages, just that I can no longer click on them. Upon clicking on the hamburger menu, nothing changes in the code.
3. I have issues with switching back to light mode via the ghost admin panel (which I will detail in another issue)

**Comment by minimaluminium** [comment]
Hey @hkrsmk, thanks for the detailed feedback. The burger icon dark mode issue is now fixed in [5.4.6](https://github.com/TryGhost/Casper/releases/tag/v5.4.6). Could you check again?

This is how it works after the fix.

https://user-images.githubusercontent.com/1418797/221766993-2a1349c2-0aea-4e2e-b2fd-b77901f155e2.mp4

**Comment by hkrsmk** [comment]
Yes, it's working great now. Thank you so much!
