### ISSUE TITLE
FAQ for dark mode is no longer accurate

### ISSUE THREAD

**Issue by hkrsmk** [TryGhost/Casper#927]
We no longer need to do code injection for Dark Mode in Casper:

https://ghost.org/help/dark-mode-casper-theme/

This FAQ should probably be changed. You can now set dark mode in Settings > Design > Site-wide > Color Scheme.

Injecting the code mentioned in the FAQ will cause light mode to be disabled; setting the scheme to light mode in admin panel will no longer work.

**Comment by minimaluminium** [comment]
True, this doesn't apply to the current version of Casper. We've just made the article to redirect to a one with more general instructions. Thanks for the report!

**Comment by GauravG8** [comment]
The link that @hkrsmk shared is now showing 404. But thanks for sharing the process @hkrsmk. Was looking for quite a while on how to toggle the dark mode 😅.
