### ISSUE TITLE
Search bar is white in dark mode

### ISSUE THREAD

**Issue by hkrsmk** [TryGhost/Casper#928]
For consistency's sake, should the search bar have inverted colours in dark mode? UX wise I'm personally not very bothered by it even though it's light coloured.

Casper version: 5.4.6

Steps to replicate:
1. Install Casper
2. Use Dark mode
3. Use the default search - pop up and results are in the Light colour scheme, along with relevant buttons and sections etc.

Sample for the search bar:
![image](https://user-images.githubusercontent.com/22993075/221770189-a5d6b6fd-e651-4ac4-9826-6d5e8deca940.png)

Sample for the "show more results" button:
![image](https://user-images.githubusercontent.com/22993075/221770415-02312c07-111a-444c-9096-8bf3f47fab13.png)

**Comment by minimaluminium** [comment]
The search box is independent from the themes (similar as how Portal works), and themes have no control over its style. There's no way to add dark mode support to the search box at the moment.
