### ISSUE TITLE
Suggesting having a page that shows all tags under it and an authors page as part of the future update of the Casper theme

### ISSUE THREAD

**Issue by pauloiys** [TryGhost/Casper#930]
![image](https://user-images.githubusercontent.com/86748882/224482282-271dc1d4-0362-4cb2-b87f-02bf3577793d.png)

**Comment by minimaluminium** [comment]
Hey 👋 . We ask that you please do not use GitHub for support or feature requests 😄. We use GitHub solely for bug-tracking and on-going feature development.

Our [forum](https://forum.ghost.org/) is a great place to get community support, plus it helps create a central location for searching problems/solutions.

Thanks!
