### ISSUE TITLE
Invalid theme

### ISSUE THREAD

**Issue by yannickcof** [TryGhost/Casper#937]
Theme not loading ...
... template file called post.hbs must be present!!!
See screenshot!!
![optimizScreenshot 95](https://user-images.githubusercontent.com/68974923/231599461-2e716244-ee36-4edb-98ff-dacea84aff5f.png)

**Comment by minimaluminium** [comment]
Hey @yannickcof, would you mind sharing how you're trying to install the theme? Are you uploading the theme zip downloaded from GitHub?

**Comment by minimaluminium** [comment]
Closing as the issue wasn't reproducible.
