### ISSUE TITLE
Unable to completely translate the theme "Casper"

### ISSUE THREAD

**Issue by L1TWIN** [TryGhost/Casper#939]
Hello everyone

Sorry for my English)) I write through a translator.

I have encountered such a problem. I decided to translate the topic, I do everything according to the instructions, but there is a problem with some elements on the site. They are missing from the topic. Now I will send examples:
![image](https://user-images.githubusercontent.com/16645444/233258238-09efe02a-6187-4779-a90a-460c72c988e7.png)
![image](https://user-images.githubusercontent.com/16645444/233258725-67fa6774-71b4-48d8-a152-c812f9d80cc0.png)

help me please)

**Comment by jonock** [comment]
@L1TWIN The portal (which your screenshots are showing) is a separate component that is not related to the theme itself. You can turn on the translation in the 'Labs' section of the settings in Ghost.
