### ISSUE TITLE
Header/nav menu doesn’t use brand color in dark mode

### ISSUE THREAD

**Issue by m1chaeljmk** [TryGhost/Casper#942]
Just noticed this happening, not sure how long it’s been that way.

Using Casper 5.4.11

The problem is here:

<img width="312" alt="Screenshot 2023-05-29 at 17 59 54" src="https://github.com/TryGhost/Casper/assets/2099901/e0a4907b-7e84-470d-bdd8-ff9a324a43b7">

In the first selector it should be `background: var(--ghost-accent-color);`

**Comment by minimaluminium** [comment]
Hey @m1chaeljmk, this is now fixed in [5.4.12](https://github.com/TryGhost/Casper/releases/tag/v5.4.12).
