### ISSUE TITLE
Question about new improvements

### ISSUE THREAD

**Issue by tuliocll** [TryGhost/Casper#950]
Hello.
I am using the Casper theme and I've made a fork to create some new features to use in my personal blog and I want to know if this new stuff makes sense to the original project, so I can open some PRs.

- Add social share (twitter, linkedin, copy and paste) on post page
- Improvement on code snippet with highlights (adding new languages, use the `code injection` on Ghost editor)
- Add zoom animation in image post (on home) when hovering the mouse
- Add all posts tags with link in posts list at home
- Add social links on footer with icons
- Add shimmer effect on images background to improve loading effect
- Change `gulp-uglify` to `gulp-uglify-es` to support ES6

Edit:
I just deployed my blog with the new features if anyone wants to see a [preview of these features](https://tuliocalil.com).

**Comment by minimaluminium** [comment]
Hey @tuliocll,

These are all great features you've added to your blog, but we're not planning to add new features, especially when they involve design.

Keep up the good work!

**Comment by tuliocll** [comment]
> Hey @tuliocll,
> 
> 
> 
> These are all great features you've added to your blog, but we're not planning to add new features, especially when they involve design.
> 
> 
> 
> Keep up the good work!

Thank you, if has something that I can contribute let me know. I love Ghost and want to help with something 😁
