### ISSUE TITLE
Using the same header of the post for the home, when activated publication cover

### ISSUE THREAD

**Issue by adtechnology** [TryGhost/Casper#954]
I love your theme. I think, the header of the posts with the accent color is beautiful. I would have an option to use this header on home with having this huge cover.

**Comment by minimaluminium** [comment]
Hey,

It is intentional to keep the navigation transparent on the homepage to make it work well with the cover image, and we're not planning to add an option for this.

If you want to have the accent color navigation on the homepage as well, add this styles to the code injection.

```html
<style>
:is(.home-template,.paged:not(.tag-template):not(.author-template)).has-cover .gh-head {
    position: static;
    background-color: var(--ghost-accent-color);
}
</style>
```
