### ISSUE TITLE
Lightbox iterating all post images

### ISSUE THREAD

**Issue by JanJakes** [TryGhost/Casper#958]
First of all, thanks for adding [the Lightbox support](https://github.com/TryGhost/Casper/commit/43688cfa012911ff70cfe7154a759f982c3a4ff3)!

Simply, I would like to know if there's a way to make the Lightbox iterate through all of the images on a page (i a post), not just each gallery/photo separately.

Thanks!
Jan

**Comment by minimaluminium** [comment]
Hey Jan,

We intentionally made the lightbox feature group images at a time to make it easier to navigate through images for posts with lots of images. It also combines the images of image and gallery cards when they're next to each other.

If you still want to make it open all images at a time, you'd need to play with some JS. All logic related with the grouping is [here](https://github.com/TryGhost/Casper/blob/276e2c9d0140c902e1c8d3760bc194790722fa71/assets/js/lightbox.js#L8-L70). You'd want to remove (or comment out) them, and add this bit of code instead.

```js
document.querySelectorAll('.gh-content img[width][height]').forEach(function (item) {
    items.push({
        src: item.getAttribute('src'),
        msrc: item.getAttribute('src'),
        w: item.getAttribute('width'),
        h: item.getAttribute('height'),
        el: item,
    })
});
```

Obviously, the logic is very generic which loops through all images with width and height attributes in a post, and you might also want to customize the code a bit further to make it fit for your use case.
