### ISSUE TITLE
YouTube videos appear really small when published

### ISSUE THREAD

**Issue by nocturnalmonkey** [TryGhost/Casper#963]
I'm using the default Casper theme and when I add a YouTube link to a post, the embed appears fine in the Editor view but when I hit publish, the embedded video appears really small. Looks to just be using the default iframe dimensions. Am I missing something or is there a way to make YouTube video embeds appear at 100% width of their container (whilst maintaining the aspect ratio)?

**Comment by minimaluminium** [comment]
Hey @nocturnalmonkey, do you have a live link somewhere?

**Comment by nocturnalmonkey** [comment]
Hey @minimaluminium, here's an example: https://blog.nocturnalmonkey.com/be-the-river-not-the-rock/

**Comment by minimaluminium** [comment]
I've just inspected your site source and found that there's an unnecessary jQuery call at the end of the scripts which is not coming from the official release of Casper. Would you be able to remove this additional jQuery call?

![CleanShot 2023-10-11 at 9  48 14@2x](https://github.com/TryGhost/Casper/assets/1418797/70791ed4-c278-488a-97dc-06f1dcb9d432)
